<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'cont_ano',
'cont_nit_contra_ta',
'nombre_cont',
'cont_estado',
'pre_contnumero',
'contnumero',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_periodicidad',
'cont_valorinicial',
'cont_valormensual',
'cont_formapago',
'cont_objeto',
'cont_vigencias_futuras',
'cont_unspsc',
'cont_tipo_rubro',
'cont_munejec',
'cont_fecha_aprobgarantia',
'cont_modifica',
'cont_cesion',
'cont_valorant',
'cont_valormensual_base',
'cont_valormensual_iva' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cont_ano' => array( 'simple_grid_field2',
'simple_grid_field3' ),
'cont_nit_contra_ta' => array( 'simple_grid_field4',
'simple_grid_field7' ),
'nombre_cont' => array( 'simple_grid_field5',
'simple_grid_field8' ),
'cont_estado' => array( 'simple_grid_field6',
'simple_grid_field11' ),
'pre_contnumero' => array( 'simple_grid_field9',
'simple_grid_field12' ),
'contnumero' => array( 'simple_grid_field10',
'simple_grid_field13' ),
'cont_fecha_inicio' => array( 'simple_grid_field17',
'simple_grid_field19' ),
'cont_fechafinal' => array( 'simple_grid_field18',
'simple_grid_field21' ),
'cont_periodicidad' => array( 'simple_grid_field20',
'simple_grid_field22' ),
'cont_valorinicial' => array( 'simple_grid_field23',
'simple_grid_field25' ),
'cont_valormensual' => array( 'simple_grid_field24',
'simple_grid_field26' ),
'cont_formapago' => array( 'simple_grid_field30',
'simple_grid_field31' ),
'cont_objeto' => array( 'grid_field',
'grid_field_label' ),
'cont_vigencias_futuras' => array( 'grid_field3',
'grid_field_label3' ),
'cont_unspsc' => array( 'grid_field4',
'grid_field_label4' ),
'cont_tipo_rubro' => array( 'grid_field5',
'grid_field_label5' ),
'cont_munejec' => array( 'grid_field2',
'grid_field_label2' ),
'cont_fecha_aprobgarantia' => array( 'grid_field6',
'grid_field_label6' ),
'cont_modifica' => array( 'grid_field8',
'grid_field_label8' ),
'cont_cesion' => array( 'grid_field9',
'grid_field_label9' ),
'cont_valorant' => array( 'grid_field11',
'grid_field_label11' ),
'cont_valormensual_base' => array( 'grid_field12',
'grid_field_label12' ),
'cont_valormensual_iva' => array( 'grid_field13',
'grid_field_label13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'back_master',
'masterlist_header' ),
'above-grid' => array(  ),
'grid' => array( 'simple_grid_field31',
'simple_grid_field30',
'simple_grid_field22',
'simple_grid_field20',
'simple_grid_field11',
'simple_grid_field6',
'grid_field_label',
'grid_field',
'simple_grid_field12',
'simple_grid_field9',
'simple_grid_field13',
'grid_field_label3',
'simple_grid_field10',
'grid_field3',
'simple_grid_field7',
'simple_grid_field4',
'simple_grid_field8',
'simple_grid_field5',
'simple_grid_field25',
'simple_grid_field23',
'simple_grid_field26',
'simple_grid_field24',
'simple_grid_field19',
'simple_grid_field17',
'simple_grid_field21',
'simple_grid_field18',
'simple_grid_field3',
'simple_grid_field2',
'grid_field_label4',
'grid_field4',
'grid_field_label5',
'grid_field5',
'grid_field_label2',
'grid_field2',
'grid_field_label6',
'grid_field6',
'grid_field_label8',
'grid_field8',
'grid_field_label9',
'grid_field9',
'grid_field_label11',
'grid_field11',
'grid_field_label12',
'grid_field12',
'grid_field_label13',
'grid_field13' ),
'below-grid' => array(  ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array(  ) ),
'itemForms' => array( 'back_master' => 'top',
'masterlist_header' => 'top',
'simple_grid_field31' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field6' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field13' => 'grid',
'grid_field_label3' => 'grid',
'simple_grid_field10' => 'grid',
'grid_field3' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field2' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label11' => 'grid',
'grid_field11' => 'grid',
'grid_field_label12' => 'grid',
'grid_field12' => 'grid',
'grid_field_label13' => 'grid',
'grid_field13' => 'grid' ),
'itemLocations' => array( 'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'cell_label11' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'cell_label12' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label11' => array( 'location' => 'grid',
'cellId' => 'cell_label15' ),
'grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'grid_field_label12' => array( 'location' => 'grid',
'cellId' => 'cell_label9' ),
'grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field_label13' => array( 'location' => 'grid',
'cellId' => 'cell_label10' ),
'grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'masterlist_header' => array( 'masterlist_header' ),
'back_master' => array( 'back_master' ),
'grid_field' => array( 'simple_grid_field2',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field20',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field30',
'grid_field',
'grid_field3',
'grid_field4',
'grid_field5',
'grid_field2',
'grid_field6',
'grid_field8',
'grid_field9',
'grid_field11',
'grid_field12',
'grid_field13' ),
'grid_field_label' => array( 'simple_grid_field3',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field19',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field31',
'grid_field_label',
'grid_field_label3',
'grid_field_label4',
'grid_field_label5',
'grid_field_label2',
'grid_field_label6',
'grid_field_label8',
'grid_field_label9',
'grid_field_label11',
'grid_field_label12',
'grid_field_label13' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'cont_ano_fieldheadercolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'cont_ano_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'pre_contnumero_fieldheadercolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'pre_contnumero_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'contnumero_fieldheadercolumn',
'cont_vigencias_futuras_fieldheadercolumn' ),
'items' => array( 'simple_grid_field13',
'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'contnumero_fieldcolumn',
'cont_vigencias_futuras_fieldcolumn' ),
'items' => array( 'simple_grid_field10',
'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'cont_nit_contra_ta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'cont_nit_contra_ta_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'nombre_cont_fieldheadercolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'nombre_cont_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'cont_fecha_inicio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'cont_fecha_inicio_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'cont_fechafinal_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'cont_fechafinal_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valorinicial_fieldheadercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valorinicial_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valormensual_fieldheadercolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valormensual_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'cont_formapago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array( 'cont_formapago_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array( 'cont_periodicidad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 6 ),
'tags' => array( 'cont_periodicidad_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'cont_estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array( 'cont_estado_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'cont_objeto_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 8 ),
'tags' => array( 'cont_objeto_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'cont_unspsc_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array( 'cont_unspsc_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array( 'cont_tipo_rubro_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array( 'cont_tipo_rubro_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array( 'cont_munejec_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array( 'cont_munejec_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 2 ),
'rows' => array( 10 ),
'tags' => array( 'cont_fecha_aprobgarantia_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 3 ),
'rows' => array( 10 ),
'tags' => array( 'cont_fecha_aprobgarantia_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array( 'cont_modifica_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array( 'cont_modifica_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label12' => array( 'cols' => array( 2 ),
'rows' => array( 11 ),
'tags' => array( 'cont_cesion_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 3 ),
'rows' => array( 11 ),
'tags' => array( 'cont_cesion_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label15' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array( 'cont_valorant_fieldheadercolumn' ),
'items' => array( 'grid_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array( 'cont_valorant_fieldcolumn' ),
'items' => array( 'grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label16' => array( 'cols' => array( 2 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 3 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array( 'cont_valormensual_base_fieldheadercolumn' ),
'items' => array( 'grid_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array( 'cont_valormensual_base_fieldcolumn' ),
'items' => array( 'grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label10' => array( 'cols' => array( 2 ),
'rows' => array( 13 ),
'tags' => array( 'cont_valormensual_iva_fieldheadercolumn' ),
'items' => array( 'grid_field_label13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 3 ),
'rows' => array( 13 ),
'tags' => array( 'cont_valormensual_iva_fieldcolumn' ),
'items' => array( 'grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 15 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 2,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'masterlist',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterlist',
'type' => 'masterlist',
'layoutId' => 'masterlist',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'back_master',
'masterlist_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 4 ) ),
'section' => 'head' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4',
'colspan' => 3 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_label12' ),
array( 'cell' => 'cell_field12' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label15' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_label16' ),
array( 'cell' => 'cell_field36' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_label10' ),
array( 'cell' => 'cell_field10' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 4 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field31' ),
'field' => 'cont_formapago',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'cont_formapago',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field22' ),
'field' => 'cont_periodicidad',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'cont_periodicidad',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field11' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field12' ),
'field' => 'pre_contnumero',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'pre_contnumero',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field13',
'grid_field_label3' ),
'field' => 'contnumero',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10',
'grid_field3' ),
'field' => 'contnumero',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field7' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field8' ),
'field' => 'nombre_cont',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'nombre_cont',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field25' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field26' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field19' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field21' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field3' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label4' ),
'field' => 'cont_unspsc',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'cont_unspsc',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label5' ),
'field' => 'cont_tipo_rubro',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'cont_tipo_rubro',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label2' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label6' ),
'field' => 'cont_fecha_aprobgarantia',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'cont_fecha_aprobgarantia',
'columnName' => 'field' ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label8' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'cell_label12' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label9' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'cell_label15' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label11' ),
'field' => 'cont_valorant',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'grid_field11' ),
'field' => 'cont_valorant',
'columnName' => 'field' ),
'cell_label16' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label12' ),
'field' => 'cont_valormensual_base',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field12' ),
'field' => 'cont_valormensual_base',
'columnName' => 'field' ),
'cell_label10' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label13' ),
'field' => 'cont_valormensual_iva',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field13' ),
'field' => 'cont_valormensual_iva',
'columnName' => 'field' ) ),
'deferredItems' => array(  ),
'buildType' => 2,
'columnCount' => 2 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'masterlist_header' => array( 'type' => 'masterlist_header' ),
'back_master' => array( 'type' => 'back_master' ),
'simple_grid_field2' => array( 'field' => 'cont_ano',
'type' => 'grid_field' ),
'simple_grid_field3' => array( 'type' => 'grid_field_label',
'field' => 'cont_ano' ),
'simple_grid_field4' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'grid_field' ),
'simple_grid_field5' => array( 'field' => 'nombre_cont',
'type' => 'grid_field' ),
'simple_grid_field6' => array( 'field' => 'cont_estado',
'type' => 'grid_field' ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'cont_nit_contra_ta' ),
'simple_grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'nombre_cont' ),
'simple_grid_field9' => array( 'field' => 'pre_contnumero',
'type' => 'grid_field' ),
'simple_grid_field10' => array( 'field' => 'contnumero',
'type' => 'grid_field' ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'cont_estado' ),
'simple_grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'pre_contnumero' ),
'simple_grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'contnumero' ),
'simple_grid_field17' => array( 'field' => 'cont_fecha_inicio',
'type' => 'grid_field' ),
'simple_grid_field18' => array( 'field' => 'cont_fechafinal',
'type' => 'grid_field' ),
'simple_grid_field19' => array( 'type' => 'grid_field_label',
'field' => 'cont_fecha_inicio' ),
'simple_grid_field20' => array( 'field' => 'cont_periodicidad',
'type' => 'grid_field' ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'cont_fechafinal' ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'cont_periodicidad' ),
'simple_grid_field23' => array( 'field' => 'cont_valorinicial',
'type' => 'grid_field' ),
'simple_grid_field24' => array( 'field' => 'cont_valormensual',
'type' => 'grid_field' ),
'simple_grid_field25' => array( 'type' => 'grid_field_label',
'field' => 'cont_valorinicial' ),
'simple_grid_field26' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual' ),
'simple_grid_field30' => array( 'field' => 'cont_formapago',
'type' => 'grid_field' ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'cont_formapago' ),
'grid_field' => array( 'field' => 'cont_objeto',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'cont_objeto' ),
'grid_field3' => array( 'field' => 'cont_vigencias_futuras',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'cont_vigencias_futuras' ),
'grid_field4' => array( 'field' => 'cont_unspsc',
'type' => 'grid_field' ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'cont_unspsc' ),
'grid_field5' => array( 'field' => 'cont_tipo_rubro',
'type' => 'grid_field' ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'cont_tipo_rubro' ),
'grid_field2' => array( 'field' => 'cont_munejec',
'type' => 'grid_field' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'cont_munejec' ),
'grid_field6' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'grid_field' ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'cont_fecha_aprobgarantia' ),
'grid_field8' => array( 'field' => 'cont_modifica',
'type' => 'grid_field' ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'cont_modifica' ),
'grid_field9' => array( 'field' => 'cont_cesion',
'type' => 'grid_field' ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'cont_cesion' ),
'grid_field11' => array( 'field' => 'cont_valorant',
'type' => 'grid_field' ),
'grid_field_label11' => array( 'type' => 'grid_field_label',
'field' => 'cont_valorant' ),
'grid_field12' => array( 'field' => 'cont_valormensual_base',
'type' => 'grid_field' ),
'grid_field_label12' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual_base' ),
'grid_field13' => array( 'field' => 'cont_valormensual_iva',
'type' => 'grid_field' ),
'grid_field_label13' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual_iva' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>