<?php
			$optionsArray = array( 'details' => array( 'contrato_attached_ov' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'cont_valormensual',
'cont_catalogo_presupuestal',
'cont_fechasistema',
'numregistro',
'prenumero',
'cont_tipo_rubro',
'cont_codrubro',
'cont_periodicidad',
'cont_formapago',
'cont_valorant',
'cont_valorinicial',
'cont_objeto',
'cont_vigencias_futuras',
'cont_acta_liquidacion',
'cont_fechafinal',
'cont_fecha_inicio',
'cont_causalc',
'cont_fecha_aprobgarantia',
'cont_fechaapertura',
'cont_modalidad',
'cont_tipoc',
'cont_munejec',
'contnumero',
'pre_contnumero',
'cont_tipo',
'cont_estado',
'cont_ano',
'cont_nit_contra_ta' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'cont_valormensual' => array( 'integrated_edit_field26' ),
'cont_catalogo_presupuestal' => array( 'integrated_edit_field12' ),
'cont_fechasistema' => array( 'integrated_edit_field46' ),
'numregistro' => array( 'integrated_edit_field6' ),
'prenumero' => array( 'integrated_edit_field5' ),
'cont_tipo_rubro' => array( 'integrated_edit_field21' ),
'cont_codrubro' => array( 'integrated_edit_field11' ),
'cont_periodicidad' => array( 'integrated_edit_field20' ),
'cont_formapago' => array( 'integrated_edit_field40' ),
'cont_valorant' => array( 'integrated_edit_field24' ),
'cont_valorinicial' => array( 'integrated_edit_field25' ),
'cont_objeto' => array( 'integrated_edit_field35' ),
'cont_vigencias_futuras' => array( 'integrated_edit_field17' ),
'cont_acta_liquidacion' => array( 'integrated_edit_field48' ),
'cont_fechafinal' => array( 'integrated_edit_field30' ),
'cont_fecha_inicio' => array( 'integrated_edit_field29' ),
'cont_causalc' => array( 'integrated_edit_field16' ),
'cont_fecha_aprobgarantia' => array( 'integrated_edit_field22' ),
'cont_fechaapertura' => array( 'integrated_edit_field28' ),
'cont_modalidad' => array( 'integrated_edit_field34' ),
'cont_tipoc' => array( 'integrated_edit_field' ),
'cont_munejec' => array( 'integrated_edit_field15' ),
'contnumero' => array( 'integrated_edit_field8' ),
'pre_contnumero' => array( 'integrated_edit_field7' ),
'cont_tipo' => array( 'integrated_edit_field9' ),
'cont_estado' => array( 'integrated_edit_field4' ),
'cont_ano' => array( 'integrated_edit_field10' ),
'cont_nit_contra_ta' => array( 'integrated_edit_field1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'menu' ),
'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'tabs' ),
'section' => array( 'integrated_edit_field1',
'integrated_edit_field10',
'integrated_edit_field4',
'integrated_edit_field9',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field15' ),
'section1' => array( 'integrated_edit_field',
'integrated_edit_field34',
'integrated_edit_field28',
'integrated_edit_field22',
'integrated_edit_field16',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field48',
'integrated_edit_field17' ),
'section2' => array( 'integrated_edit_field35' ),
'section3' => array( 'integrated_edit_field25',
'integrated_edit_field24',
'integrated_edit_field40',
'integrated_edit_field20',
'integrated_edit_field11',
'integrated_edit_field21',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field46',
'integrated_edit_field12',
'integrated_edit_field26' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'tabs' => 'grid',
'integrated_edit_field1' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field15' => 'section',
'integrated_edit_field' => 'section1',
'integrated_edit_field34' => 'section1',
'integrated_edit_field28' => 'section1',
'integrated_edit_field22' => 'section1',
'integrated_edit_field16' => 'section1',
'integrated_edit_field29' => 'section1',
'integrated_edit_field30' => 'section1',
'integrated_edit_field48' => 'section1',
'integrated_edit_field17' => 'section1',
'integrated_edit_field35' => 'section2',
'integrated_edit_field25' => 'section3',
'integrated_edit_field24' => 'section3',
'integrated_edit_field40' => 'section3',
'integrated_edit_field20' => 'section3',
'integrated_edit_field11' => 'section3',
'integrated_edit_field21' => 'section3',
'integrated_edit_field5' => 'section3',
'integrated_edit_field6' => 'section3',
'integrated_edit_field46' => 'section3',
'integrated_edit_field12' => 'section3',
'integrated_edit_field26' => 'section3' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c5' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field15' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field28' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field22' => array( 'location' => 'section1',
'cellId' => 'c5' ),
'integrated_edit_field16' => array( 'location' => 'section1',
'cellId' => 'c9' ),
'integrated_edit_field29' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field30' => array( 'location' => 'section1',
'cellId' => 'c7' ),
'integrated_edit_field48' => array( 'location' => 'section1',
'cellId' => 'c8' ),
'integrated_edit_field17' => array( 'location' => 'section1',
'cellId' => 'c10' ),
'integrated_edit_field35' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field24' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field40' => array( 'location' => 'section3',
'cellId' => 'c6' ),
'integrated_edit_field20' => array( 'location' => 'section3',
'cellId' => 'c7' ),
'integrated_edit_field11' => array( 'location' => 'section3',
'cellId' => 'c8' ),
'integrated_edit_field21' => array( 'location' => 'section3',
'cellId' => 'c9' ),
'integrated_edit_field5' => array( 'location' => 'section3',
'cellId' => 'c10' ),
'integrated_edit_field6' => array( 'location' => 'section3',
'cellId' => 'c11' ),
'integrated_edit_field46' => array( 'location' => 'section3',
'cellId' => 'c12' ),
'integrated_edit_field12' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field26' => array( 'location' => 'section3',
'cellId' => 'c14' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_view' => array( 'edit_view' ),
'tabs' => array( 'tabs' ),
'integrated_edit_field' => array( 'integrated_edit_field26',
'integrated_edit_field12',
'integrated_edit_field46',
'integrated_edit_field6',
'integrated_edit_field5',
'integrated_edit_field21',
'integrated_edit_field11',
'integrated_edit_field20',
'integrated_edit_field40',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field35',
'integrated_edit_field17',
'integrated_edit_field48',
'integrated_edit_field30',
'integrated_edit_field29',
'integrated_edit_field16',
'integrated_edit_field22',
'integrated_edit_field28',
'integrated_edit_field34',
'integrated_edit_field',
'integrated_edit_field15',
'integrated_edit_field8',
'integrated_edit_field7',
'integrated_edit_field9',
'integrated_edit_field4',
'integrated_edit_field10',
'integrated_edit_field1' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'collapse_button' => array( 'collapse_button' ),
'logo' => array( 'logo1' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'adminarea_link' => array( 'adminarea_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field48' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 5 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c10' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field46' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 7 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c4',
'colspan' => 1 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c5',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c4' => array( 'model' => 'c3',
'items' => array( 'tabs' ) ),
'c5' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ) ),
'c9' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ),
'useFullWidth' => true ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field29' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field48' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c14' ),
array( 'cell' => 'c15' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field46' ) ),
'c13' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ) ),
'c15' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save',
'label' => array( 'type' => 0,
'text' => 'Guardar cambios' ),
'icon' => array( 'file' => 'Save as-WF.png' ),
'buttonSize' => 'xtra-small' ),
'edit_back_list' => array( 'type' => 'edit_back_list',
'icon' => array( 'file' => 'In-WF.png' ),
'buttonStyle' => 'info',
'buttonSize' => 'xtra-small' ),
'edit_close' => array( 'type' => 'edit_close',
'icon' => array( 'file' => 'Cross Close.png' ),
'buttonStyle' => 'info',
'buttonSize' => 'xtra-small' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_view' => array( 'type' => 'edit_view' ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Información del contrato',
'type' => 0 ),
array( 'text' => 'Modalidad y fechas',
'type' => 0 ),
array( 'text' => 'Objeto, Obligaciones y Plazo',
'type' => 0 ),
array( 'text' => 'Valor y Pago',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section2',
'section3' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field26' => array( 'field' => 'cont_valormensual',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'cont_catalogo_presupuestal',
'table' => 'contrato',
'type' => 3 ) ),
'integrated_edit_field46' => array( 'field' => 'cont_fechasistema',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'numregistro',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'prenumero',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'cont_tipo_rubro',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'cont_codrubro',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'cont_periodicidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'cont_formapago',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'cont_valorant',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'cont_valorant',
'table' => 'contrato',
'type' => 3 ) ),
'integrated_edit_field25' => array( 'field' => 'cont_valorinicial',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'cont_valorinicial',
'table' => 'contrato',
'type' => 3 ) ),
'integrated_edit_field35' => array( 'field' => 'cont_objeto',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field17' => array( 'field' => 'cont_vigencias_futuras',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'cont_vigencias_futuras',
'table' => null,
'type' => 3 ) ),
'integrated_edit_field48' => array( 'field' => 'cont_acta_liquidacion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'cont_fechafinal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'cont_fecha_inicio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'cont_causalc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'cont_fechaapertura',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'cont_modalidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'cont_tipoc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'cont_munejec',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'contnumero',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'pre_contnumero',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'cont_tipo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'cont_estado',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'cont_ano',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'logo1' => array( 'type' => 'logo' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>