<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'details' => array( 'contrato_attached_ov' => array( 'displayPreview' => 1 ) ),
'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'cont_hash' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ),
'cont_paa_id' => array( 'totalsType' => '' ),
'cont_nit_contra_ta' => array( 'totalsType' => '' ),
'nombre_cont' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'prenumero' => array( 'totalsType' => '' ),
'numregistro' => array( 'totalsType' => '' ),
'pre_contnumero' => array( 'totalsType' => '' ),
'contnumero' => array( 'totalsType' => '' ),
'cont_tipo' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'cont_fecha_inicio' => array( 'totalsType' => '' ),
'cont_fechafinal' => array( 'totalsType' => '' ),
'cont_fechavigencia' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'cont_informessug' => array( 'totalsType' => '' ),
'cont_valorant' => array( 'totalsType' => '' ),
'cont_valorinicial' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'cont_tipoc' => array( 'totalsType' => '' ),
'cont_modalidad' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_tipoproceso' => array( 'totalsType' => '' ),
'cont_formapago' => array( 'totalsType' => '' ),
'cont_fechasistema' => array( 'totalsType' => '' ),
'cont_acta_liquidacion' => array( 'totalsType' => '' ),
'cont_obligaciones' => array( 'totalsType' => '' ),
'cont_plazo' => array( 'totalsType' => '' ),
'cont_vigencias_futuras' => array( 'totalsType' => '' ),
'cont_secop_proceso' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'cont_sigep' => array( 'totalsType' => '' ),
'vf_num_autorizacion' => array( 'totalsType' => '' ),
'vf_fecha' => array( 'totalsType' => '' ),
'vf_valor' => array( 'totalsType' => '' ),
'cont_unspsc' => array( 'totalsType' => '' ),
'cont_tipo_rubro' => array( 'totalsType' => '' ),
'cont_munejec' => array( 'totalsType' => '' ),
'cont_fecha_aprobgarantia' => array( 'totalsType' => '' ),
'cont_numpoliza' => array( 'totalsType' => '' ),
'cont_modifica' => array( 'totalsType' => '' ),
'cont_cesion' => array( 'totalsType' => '' ),
'cont_valorvigente' => array( 'totalsType' => '' ),
'cont_depsup' => array( 'totalsType' => '' ),
'cont_dep' => array( 'totalsType' => '' ),
'cont_valormensual_base' => array( 'totalsType' => '' ),
'cont_valormensual_iva' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cont_ano',
'pre_contnumero',
'cont_nit_contra_ta',
'cont_fecha_inicio',
'cont_estado',
'cont_formapago',
'cont_valorinicial',
'cont_objeto',
'contnumero',
'nombre_cont',
'cont_fechafinal',
'cont_valormensual',
'cont_periodicidad',
'cont_vigencias_futuras',
'cont_tipo_rubro',
'cont_munejec',
'cont_fecha_aprobgarantia',
'cont_modifica',
'cont_cesion',
'cont_valorant',
'cont_valormensual_base',
'cont_valormensual_iva' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cont_ano' => array( 'grid_field_label',
'grid_field' ),
'pre_contnumero' => array( 'grid_field_label2',
'grid_field2' ),
'cont_nit_contra_ta' => array( 'grid_field_label4',
'grid_field4' ),
'cont_fecha_inicio' => array( 'grid_field_label6',
'grid_field6' ),
'cont_estado' => array( 'grid_field12',
'grid_field_label12' ),
'cont_formapago' => array( 'grid_field10',
'grid_field_label10' ),
'cont_valorinicial' => array( 'grid_field8',
'grid_field_label8' ),
'cont_objeto' => array( 'grid_field_label1',
'grid_field1' ),
'contnumero' => array( 'grid_field_label5',
'grid_field5' ),
'nombre_cont' => array( 'grid_field_label7',
'grid_field7' ),
'cont_fechafinal' => array( 'grid_field_label9',
'grid_field9' ),
'cont_valormensual' => array( 'grid_field_label11',
'grid_field11' ),
'cont_periodicidad' => array( 'grid_field_label13',
'grid_field13' ),
'cont_vigencias_futuras' => array( 'grid_field16',
'grid_field_label16' ),
'cont_tipo_rubro' => array( 'grid_field19',
'grid_field_label19' ),
'cont_munejec' => array( 'grid_field15',
'grid_field_label15' ),
'cont_fecha_aprobgarantia' => array( 'grid_field20',
'grid_field_label20' ),
'cont_modifica' => array( 'grid_field22',
'grid_field_label22' ),
'cont_cesion' => array( 'grid_field23',
'grid_field_label23' ),
'cont_valorant' => array( 'grid_field25',
'grid_field_label25' ),
'cont_valormensual_base' => array( 'grid_field26',
'grid_field_label26' ),
'cont_valormensual_iva' => array( 'grid_field27',
'grid_field_label27' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader',
'image' ),
'above-grid' => array( 'print_pages',
'print_pdf' ),
'below-grid' => array(  ),
'grid' => array( 'details_preview9',
'details_preview10',
'details_preview11',
'details_preview5',
'details_preview6',
'details_preview12',
'details_preview13',
'details_preview',
'grid_field_label4',
'grid_field4',
'grid_field_label7',
'grid_field7',
'grid_field_label6',
'grid_field6',
'grid_field_label9',
'grid_field9',
'grid_field_label13',
'grid_field13',
'grid_field_label12',
'grid_field12',
'grid_field_label8',
'grid_field8',
'grid_field_label11',
'grid_field11',
'grid_field_label10',
'grid_field10',
'grid_field_label1',
'grid_field1',
'grid_field_label2',
'grid_field2',
'grid_field_label5',
'grid_field5',
'grid_field_label20',
'grid_field20',
'grid_field_label16',
'grid_field16',
'grid_field_label',
'grid_field',
'grid_field_label19',
'grid_field19',
'grid_field_label15',
'grid_field15',
'grid_field_label22',
'grid_field22',
'grid_field_label23',
'grid_field23',
'grid_field_label25',
'grid_field25',
'grid_field_label26',
'grid_field26',
'grid_field_label27',
'grid_field27' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages',
'pdflink_block' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'image' => 'top',
'print_pages' => 'above-grid',
'print_pdf' => 'above-grid',
'details_preview9' => 'grid',
'details_preview10' => 'grid',
'details_preview11' => 'grid',
'details_preview5' => 'grid',
'details_preview6' => 'grid',
'details_preview12' => 'grid',
'details_preview13' => 'grid',
'details_preview' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label13' => 'grid',
'grid_field13' => 'grid',
'grid_field_label12' => 'grid',
'grid_field12' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label11' => 'grid',
'grid_field11' => 'grid',
'grid_field_label10' => 'grid',
'grid_field10' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_label20' => 'grid',
'grid_field20' => 'grid',
'grid_field_label16' => 'grid',
'grid_field16' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label19' => 'grid',
'grid_field19' => 'grid',
'grid_field_label15' => 'grid',
'grid_field15' => 'grid',
'grid_field_label22' => 'grid',
'grid_field22' => 'grid',
'grid_field_label23' => 'grid',
'grid_field23' => 'grid',
'grid_field_label25' => 'grid',
'grid_field25' => 'grid',
'grid_field_label26' => 'grid',
'grid_field26' => 'grid',
'grid_field_label27' => 'grid',
'grid_field27' => 'grid' ),
'itemLocations' => array( 'details_preview9' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview10' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview11' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview5' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview6' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview12' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview13' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label13' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_label12' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_field_label11' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label10' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_label10' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'grid_field_label20' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'grid_field_label16' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'grid_field_label19' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'grid_field_label15' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'grid_field_label22' => array( 'location' => 'grid',
'cellId' => 'cell_label11' ),
'grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label23' => array( 'location' => 'grid',
'cellId' => 'cell_label12' ),
'grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label25' => array( 'location' => 'grid',
'cellId' => 'cell_label15' ),
'grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'grid_field_label26' => array( 'location' => 'grid',
'cellId' => 'cell_label17' ),
'grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'grid_field_label27' => array( 'location' => 'grid',
'cellId' => 'cell_label18' ),
'grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field_label' => array( 'grid_field_label',
'grid_field_label2',
'grid_field_label4',
'grid_field_label6',
'grid_field_label12',
'grid_field_label10',
'grid_field_label8',
'grid_field_label1',
'grid_field_label5',
'grid_field_label7',
'grid_field_label9',
'grid_field_label11',
'grid_field_label13',
'grid_field_label16',
'grid_field_label19',
'grid_field_label15',
'grid_field_label20',
'grid_field_label22',
'grid_field_label23',
'grid_field_label25',
'grid_field_label26',
'grid_field_label27' ),
'grid_field' => array( 'grid_field',
'grid_field2',
'grid_field4',
'grid_field6',
'grid_field12',
'grid_field10',
'grid_field8',
'grid_field1',
'grid_field5',
'grid_field7',
'grid_field9',
'grid_field11',
'grid_field13',
'grid_field16',
'grid_field19',
'grid_field15',
'grid_field20',
'grid_field22',
'grid_field23',
'grid_field25',
'grid_field26',
'grid_field27' ),
'print_pdf' => array( 'print_pdf' ),
'details_preview' => array( 'details_preview5',
'details_preview9',
'details_preview10',
'details_preview11',
'details_preview6',
'details_preview12',
'details_preview13',
'details_preview' ),
'image' => array( 'image' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'cont_tipo_rubro_fieldheadercolumn' ),
'items' => array( 'grid_field_label19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'cont_tipo_rubro_fieldcolumn' ),
'items' => array( 'grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'cont_munejec_fieldheadercolumn' ),
'items' => array( 'grid_field_label15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'cont_munejec_fieldcolumn' ),
'items' => array( 'grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'cont_fecha_aprobgarantia_fieldheadercolumn' ),
'items' => array( 'grid_field_label20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'cont_fecha_aprobgarantia_fieldcolumn' ),
'items' => array( 'grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'pre_contnumero_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'pre_contnumero_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'contnumero_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'contnumero_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'cont_vigencias_futuras_fieldheadercolumn' ),
'items' => array( 'grid_field_label16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'cont_vigencias_futuras_fieldcolumn' ),
'items' => array( 'grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'cont_ano_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'cont_ano_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'cont_nit_contra_ta_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'cont_nit_contra_ta_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array( 'nombre_cont_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'nombre_cont_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'cont_fecha_inicio_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array( 'cont_fecha_inicio_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array( 'cont_fechafinal_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 6 ),
'tags' => array( 'cont_fechafinal_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'cont_periodicidad_fieldheadercolumn' ),
'items' => array( 'grid_field_label13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array( 'cont_periodicidad_fieldcolumn' ),
'items' => array( 'grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array( 'cont_estado_fieldheadercolumn' ),
'items' => array( 'grid_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array( 'cont_estado_fieldcolumn' ),
'items' => array( 'grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'cont_valorinicial_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array( 'cont_valorinicial_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array( 'cont_valormensual_fieldheadercolumn' ),
'items' => array( 'grid_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 3 ),
'rows' => array( 8 ),
'tags' => array( 'cont_valormensual_fieldcolumn' ),
'items' => array( 'grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'cont_formapago_fieldheadercolumn' ),
'items' => array( 'grid_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array( 'cont_formapago_fieldcolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label10' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array( 'cont_objeto_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 10 ),
'tags' => array( 'cont_objeto_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array( 'cont_modifica_fieldheadercolumn' ),
'items' => array( 'grid_field_label22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array( 'cont_modifica_fieldcolumn' ),
'items' => array( 'grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label12' => array( 'cols' => array( 2 ),
'rows' => array( 11 ),
'tags' => array( 'cont_cesion_fieldheadercolumn' ),
'items' => array( 'grid_field_label23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 3 ),
'rows' => array( 11 ),
'tags' => array( 'cont_cesion_fieldcolumn' ),
'items' => array( 'grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label15' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array( 'cont_valorant_fieldheadercolumn' ),
'items' => array( 'grid_field_label25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array( 'cont_valorant_fieldcolumn' ),
'items' => array( 'grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label16' => array( 'cols' => array( 2 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 3 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label17' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array( 'cont_valormensual_base_fieldheadercolumn' ),
'items' => array( 'grid_field_label26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array( 'cont_valormensual_base_fieldcolumn' ),
'items' => array( 'grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label18' => array( 'cols' => array( 2 ),
'rows' => array( 13 ),
'tags' => array( 'cont_valormensual_iva_fieldheadercolumn' ),
'items' => array( 'grid_field_label27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 3 ),
'rows' => array( 13 ),
'tags' => array( 'cont_valormensual_iva_fieldcolumn' ),
'items' => array( 'grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array( 'details_preview9',
'details_preview10',
'details_preview11',
'details_preview5',
'details_preview6',
'details_preview12',
'details_preview13',
'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 15 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false,
'listColumnsOrderOnPrint' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c2',
'items' => array( 'image' ) ),
'c4' => array( 'model' => 'c4',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'print_pdf' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 4 ) ),
'section' => 'head' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field9' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label10' ),
array( 'cell' => 'cell_field10',
'colspan' => 3 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_label12' ),
array( 'cell' => 'cell_field12' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label15' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_label16' ),
array( 'cell' => 'cell_field24' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label17' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_label18' ),
array( 'cell' => 'cell_field38' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 4 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview9',
'details_preview10',
'details_preview11',
'details_preview5',
'details_preview6',
'details_preview12',
'details_preview13',
'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label4' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label7' ),
'field' => 'nombre_cont',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'nombre_cont',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label6' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label9' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label13' ),
'field' => 'cont_periodicidad',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field13' ),
'field' => 'cont_periodicidad',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label12' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field12' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label8' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label11' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field11' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label10' ),
'field' => 'cont_formapago',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field10' ),
'field' => 'cont_formapago',
'columnName' => 'field' ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label10' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label1' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label2' ),
'field' => 'pre_contnumero',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'pre_contnumero',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label5' ),
'field' => 'contnumero',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'contnumero',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field27' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label20' ),
'field' => 'cont_fecha_aprobgarantia',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'grid_field20' ),
'field' => 'cont_fecha_aprobgarantia',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label16' ),
'field' => 'cont_vigencias_futuras',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'grid_field16' ),
'field' => 'cont_vigencias_futuras',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label19' ),
'field' => 'cont_tipo_rubro',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'grid_field19' ),
'field' => 'cont_tipo_rubro',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label15' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'grid_field15' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label22' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'grid_field22' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'cell_label12' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label23' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field23' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'cell_label15' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label25' ),
'field' => 'cont_valorant',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'grid_field25' ),
'field' => 'cont_valorant',
'columnName' => 'field' ),
'cell_label16' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label17' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label26' ),
'field' => 'cont_valormensual_base',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'grid_field26' ),
'field' => 'cont_valormensual_base',
'columnName' => 'field' ),
'cell_label18' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label27' ),
'field' => 'cont_valormensual_iva',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'grid_field27' ),
'field' => 'cont_valormensual_iva',
'columnName' => 'field' ) ),
'deferredItems' => array(  ),
'buildType' => 2,
'columnCount' => 2 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header',
'title' => array( 'page' => 'print',
'table' => 'contrato',
'type' => 7 ) ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'cont_ano' ),
'grid_field' => array( 'field' => 'cont_ano',
'type' => 'grid_field' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'pre_contnumero' ),
'grid_field2' => array( 'field' => 'pre_contnumero',
'type' => 'grid_field' ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'cont_nit_contra_ta' ),
'grid_field4' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'grid_field' ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'cont_fecha_inicio' ),
'grid_field6' => array( 'field' => 'cont_fecha_inicio',
'type' => 'grid_field' ),
'grid_field12' => array( 'field' => 'cont_estado',
'type' => 'grid_field' ),
'grid_field_label12' => array( 'type' => 'grid_field_label',
'field' => 'cont_estado' ),
'grid_field10' => array( 'field' => 'cont_formapago',
'type' => 'grid_field' ),
'grid_field_label10' => array( 'type' => 'grid_field_label',
'field' => 'cont_formapago' ),
'grid_field8' => array( 'field' => 'cont_valorinicial',
'type' => 'grid_field' ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'cont_valorinicial' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'cont_objeto' ),
'grid_field1' => array( 'field' => 'cont_objeto',
'type' => 'grid_field' ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'contnumero' ),
'grid_field5' => array( 'field' => 'contnumero',
'type' => 'grid_field' ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'nombre_cont' ),
'grid_field7' => array( 'field' => 'nombre_cont',
'type' => 'grid_field' ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'cont_fechafinal' ),
'grid_field9' => array( 'field' => 'cont_fechafinal',
'type' => 'grid_field' ),
'grid_field_label11' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual' ),
'grid_field11' => array( 'field' => 'cont_valormensual',
'type' => 'grid_field' ),
'grid_field_label13' => array( 'type' => 'grid_field_label',
'field' => 'cont_periodicidad' ),
'grid_field13' => array( 'field' => 'cont_periodicidad',
'type' => 'grid_field' ),
'print_pdf' => array( 'type' => 'print_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'grid_field16' => array( 'field' => 'cont_vigencias_futuras',
'type' => 'grid_field' ),
'grid_field_label16' => array( 'type' => 'grid_field_label',
'field' => 'cont_vigencias_futuras' ),
'details_preview5' => array( 'type' => 'details_preview',
'table' => 'q_info_registros',
'items' => array(  ),
'popup' => false ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'Logo_Coldeportes.png',
'source' => 2 ) ),
'grid_field19' => array( 'field' => 'cont_tipo_rubro',
'type' => 'grid_field' ),
'grid_field_label19' => array( 'type' => 'grid_field_label',
'field' => 'cont_tipo_rubro' ),
'grid_field15' => array( 'field' => 'cont_munejec',
'type' => 'grid_field' ),
'grid_field_label15' => array( 'type' => 'grid_field_label',
'field' => 'cont_munejec' ),
'grid_field20' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'grid_field' ),
'grid_field_label20' => array( 'type' => 'grid_field_label',
'field' => 'cont_fecha_aprobgarantia' ),
'grid_field22' => array( 'field' => 'cont_modifica',
'type' => 'grid_field' ),
'grid_field_label22' => array( 'type' => 'grid_field_label',
'field' => 'cont_modifica' ),
'grid_field23' => array( 'field' => 'cont_cesion',
'type' => 'grid_field' ),
'grid_field_label23' => array( 'type' => 'grid_field_label',
'field' => 'cont_cesion' ),
'details_preview9' => array( 'type' => 'details_preview',
'table' => 'contrato_modifica_prorroga',
'items' => array(  ),
'popup' => false,
'pageId' => 'print' ),
'details_preview10' => array( 'type' => 'details_preview',
'table' => 'contrato_modifica_cesion',
'items' => array(  ),
'popup' => false,
'pageId' => 'print' ),
'details_preview11' => array( 'type' => 'details_preview',
'table' => 'contrato_modifica_track',
'items' => array(  ),
'popup' => false ),
'details_preview6' => array( 'type' => 'details_preview',
'table' => 'q_info_obligacion',
'items' => array(  ),
'popup' => false ),
'details_preview12' => array( 'type' => 'details_preview',
'table' => 'q_info_ordenpago',
'items' => array(  ),
'popup' => false ),
'details_preview13' => array( 'type' => 'details_preview',
'table' => 'contrato_dependencia',
'items' => array(  ),
'popup' => false ),
'grid_field25' => array( 'field' => 'cont_valorant',
'type' => 'grid_field' ),
'grid_field_label25' => array( 'type' => 'grid_field_label',
'field' => 'cont_valorant' ),
'grid_field26' => array( 'field' => 'cont_valormensual_base',
'type' => 'grid_field' ),
'grid_field_label26' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual_base' ),
'grid_field27' => array( 'field' => 'cont_valormensual_iva',
'type' => 'grid_field' ),
'grid_field_label27' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual_iva' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'contrato_attached_ov',
'items' => array(  ),
'popup' => false ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>