<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'nit_entidad' => array( 'totalsType' => '' ),
'proceso_de_compra' => array( 'totalsType' => '' ),
'id_contrato' => array( 'totalsType' => '' ),
'referencia_del_contrato' => array( 'totalsType' => '' ),
'estado_contrato' => array( 'totalsType' => '' ),
'codigo_de_categoria_principal' => array( 'totalsType' => '' ),
'descripcion_del_proceso' => array( 'totalsType' => '' ),
'tipo_de_contrato' => array( 'totalsType' => '' ),
'modalidad_de_contratacion' => array( 'totalsType' => '' ),
'justificacion_modalidad_de' => array( 'totalsType' => '' ),
'fecha_de_firma' => array( 'totalsType' => '' ),
'fecha_de_inicio_del_contrato' => array( 'totalsType' => '' ),
'fecha_de_fin_del_contrato' => array( 'totalsType' => '' ),
'fecha_de_inicio_de_ejecucion' => array( 'totalsType' => '' ),
'fecha_de_fin_de_ejecucion' => array( 'totalsType' => '' ),
'condiciones_de_entrega' => array( 'totalsType' => '' ),
'tipodocproveedor' => array( 'totalsType' => '' ),
'documento_proveedor' => array( 'totalsType' => '' ),
'proveedor_adjudicado' => array( 'totalsType' => '' ),
'es_grupo' => array( 'totalsType' => '' ),
'es_pyme' => array( 'totalsType' => '' ),
'habilita_pago_adelantado' => array( 'totalsType' => '' ),
'liquidaci_n' => array( 'totalsType' => '' ),
'obligaci_n_ambiental' => array( 'totalsType' => '' ),
'obligaciones_postconsumo' => array( 'totalsType' => '' ),
'reversion' => array( 'totalsType' => '' ),
'valor_del_contrato' => array( 'totalsType' => '' ),
'valor_de_pago_adelantado' => array( 'totalsType' => '' ),
'valor_facturado' => array( 'totalsType' => '' ),
'valor_pendiente_de_pago' => array( 'totalsType' => '' ),
'valor_pagado' => array( 'totalsType' => '' ),
'valor_amortizado' => array( 'totalsType' => '' ),
'valor_pendiente_de' => array( 'totalsType' => '' ),
'valor_pendiente_de_ejecucion' => array( 'totalsType' => '' ),
'estado_bpin' => array( 'totalsType' => '' ),
'c_digo_bpin' => array( 'totalsType' => '' ),
'anno_bpin' => array( 'totalsType' => '' ),
'saldo_cdp' => array( 'totalsType' => '' ),
'saldo_vigencia' => array( 'totalsType' => '' ),
'espostconflicto' => array( 'totalsType' => '' ),
'urlproceso' => array( 'totalsType' => '' ),
'destino_gasto' => array( 'totalsType' => '' ),
'origen_de_los_recursos' => array( 'totalsType' => '' ),
'd_as_adicionados' => array( 'totalsType' => '' ),
'puntos_del_acuerdo' => array( 'totalsType' => '' ),
'pilares_del_acuerdo' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'nit_entidad',
'proceso_de_compra',
'id_contrato',
'referencia_del_contrato',
'estado_contrato',
'codigo_de_categoria_principal',
'descripcion_del_proceso',
'tipo_de_contrato',
'modalidad_de_contratacion',
'justificacion_modalidad_de',
'fecha_de_firma',
'fecha_de_inicio_del_contrato',
'fecha_de_fin_del_contrato',
'fecha_de_inicio_de_ejecucion',
'fecha_de_fin_de_ejecucion',
'condiciones_de_entrega',
'tipodocproveedor',
'documento_proveedor',
'proveedor_adjudicado',
'es_grupo',
'es_pyme',
'habilita_pago_adelantado',
'liquidaci_n',
'obligaci_n_ambiental',
'obligaciones_postconsumo',
'reversion',
'valor_del_contrato',
'valor_de_pago_adelantado',
'valor_facturado',
'valor_pendiente_de_pago',
'valor_pagado',
'valor_amortizado',
'valor_pendiente_de',
'valor_pendiente_de_ejecucion',
'estado_bpin',
'c_digo_bpin',
'anno_bpin',
'saldo_cdp',
'saldo_vigencia',
'espostconflicto',
'urlproceso',
'destino_gasto',
'origen_de_los_recursos',
'd_as_adicionados',
'puntos_del_acuerdo',
'pilares_del_acuerdo' ),
'exportFields' => array( 'id',
'nit_entidad',
'proceso_de_compra',
'id_contrato',
'referencia_del_contrato',
'estado_contrato',
'codigo_de_categoria_principal',
'descripcion_del_proceso',
'tipo_de_contrato',
'modalidad_de_contratacion',
'justificacion_modalidad_de',
'fecha_de_firma',
'fecha_de_inicio_del_contrato',
'fecha_de_fin_del_contrato',
'fecha_de_inicio_de_ejecucion',
'fecha_de_fin_de_ejecucion',
'condiciones_de_entrega',
'tipodocproveedor',
'documento_proveedor',
'proveedor_adjudicado',
'es_grupo',
'es_pyme',
'habilita_pago_adelantado',
'liquidaci_n',
'obligaci_n_ambiental',
'obligaciones_postconsumo',
'reversion',
'valor_del_contrato',
'valor_de_pago_adelantado',
'valor_facturado',
'valor_pendiente_de_pago',
'valor_pagado',
'valor_amortizado',
'valor_pendiente_de',
'valor_pendiente_de_ejecucion',
'estado_bpin',
'c_digo_bpin',
'anno_bpin',
'saldo_cdp',
'saldo_vigencia',
'espostconflicto',
'urlproceso',
'destino_gasto',
'origen_de_los_recursos',
'd_as_adicionados',
'puntos_del_acuerdo',
'pilares_del_acuerdo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'export_field' ),
'nit_entidad' => array( 'export_field2' ),
'proceso_de_compra' => array( 'export_field10' ),
'id_contrato' => array( 'export_field11' ),
'referencia_del_contrato' => array( 'export_field12' ),
'estado_contrato' => array( 'export_field13' ),
'codigo_de_categoria_principal' => array( 'export_field14' ),
'descripcion_del_proceso' => array( 'export_field15' ),
'tipo_de_contrato' => array( 'export_field16' ),
'modalidad_de_contratacion' => array( 'export_field17' ),
'justificacion_modalidad_de' => array( 'export_field18' ),
'fecha_de_firma' => array( 'export_field19' ),
'fecha_de_inicio_del_contrato' => array( 'export_field20' ),
'fecha_de_fin_del_contrato' => array( 'export_field21' ),
'fecha_de_inicio_de_ejecucion' => array( 'export_field22' ),
'fecha_de_fin_de_ejecucion' => array( 'export_field23' ),
'condiciones_de_entrega' => array( 'export_field24' ),
'tipodocproveedor' => array( 'export_field25' ),
'documento_proveedor' => array( 'export_field26' ),
'proveedor_adjudicado' => array( 'export_field27' ),
'es_grupo' => array( 'export_field28' ),
'es_pyme' => array( 'export_field29' ),
'habilita_pago_adelantado' => array( 'export_field30' ),
'liquidaci_n' => array( 'export_field31' ),
'obligaci_n_ambiental' => array( 'export_field32' ),
'obligaciones_postconsumo' => array( 'export_field33' ),
'reversion' => array( 'export_field34' ),
'valor_del_contrato' => array( 'export_field35' ),
'valor_de_pago_adelantado' => array( 'export_field36' ),
'valor_facturado' => array( 'export_field37' ),
'valor_pendiente_de_pago' => array( 'export_field38' ),
'valor_pagado' => array( 'export_field39' ),
'valor_amortizado' => array( 'export_field40' ),
'valor_pendiente_de' => array( 'export_field41' ),
'valor_pendiente_de_ejecucion' => array( 'export_field42' ),
'estado_bpin' => array( 'export_field43' ),
'c_digo_bpin' => array( 'export_field44' ),
'anno_bpin' => array( 'export_field45' ),
'saldo_cdp' => array( 'export_field46' ),
'saldo_vigencia' => array( 'export_field47' ),
'espostconflicto' => array( 'export_field48' ),
'urlproceso' => array( 'export_field49' ),
'destino_gasto' => array( 'export_field50' ),
'origen_de_los_recursos' => array( 'export_field51' ),
'd_as_adicionados' => array( 'export_field52' ),
'puntos_del_acuerdo' => array( 'export_field53' ),
'pilares_del_acuerdo' => array( 'export_field54' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field2',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field2' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_field40' => 'grid',
'export_field41' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field48' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field51' => 'grid',
'export_field52' => 'grid',
'export_field53' => 'grid',
'export_field54' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field2',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field2',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'nit_entidad',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'proceso_de_compra',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'id_contrato',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'referencia_del_contrato',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'estado_contrato',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'codigo_de_categoria_principal',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'descripcion_del_proceso',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'tipo_de_contrato',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'modalidad_de_contratacion',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'justificacion_modalidad_de',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'fecha_de_firma',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'fecha_de_inicio_del_contrato',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'fecha_de_fin_del_contrato',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'fecha_de_inicio_de_ejecucion',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'fecha_de_fin_de_ejecucion',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'condiciones_de_entrega',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'tipodocproveedor',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'documento_proveedor',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'proveedor_adjudicado',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'es_grupo',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'es_pyme',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'habilita_pago_adelantado',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'liquidaci_n',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'obligaci_n_ambiental',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'obligaciones_postconsumo',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'reversion',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'valor_del_contrato',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'valor_de_pago_adelantado',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'valor_facturado',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'valor_pendiente_de_pago',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'valor_pagado',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'valor_amortizado',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'valor_pendiente_de',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'valor_pendiente_de_ejecucion',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'estado_bpin',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'c_digo_bpin',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'anno_bpin',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'saldo_cdp',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'saldo_vigencia',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'espostconflicto',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'urlproceso',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'destino_gasto',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'origen_de_los_recursos',
'type' => 'export_field' ),
'export_field52' => array( 'field' => 'd_as_adicionados',
'type' => 'export_field' ),
'export_field53' => array( 'field' => 'puntos_del_acuerdo',
'type' => 'export_field' ),
'export_field54' => array( 'field' => 'pilares_del_acuerdo',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>