<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'nit_entidad' => array( 'totalsType' => '' ),
'proceso_de_compra' => array( 'totalsType' => '' ),
'id_contrato' => array( 'totalsType' => '' ),
'referencia_del_contrato' => array( 'totalsType' => '' ),
'estado_contrato' => array( 'totalsType' => '' ),
'codigo_de_categoria_principal' => array( 'totalsType' => '' ),
'descripcion_del_proceso' => array( 'totalsType' => '' ),
'tipo_de_contrato' => array( 'totalsType' => '' ),
'modalidad_de_contratacion' => array( 'totalsType' => '' ),
'justificacion_modalidad_de' => array( 'totalsType' => '' ),
'fecha_de_firma' => array( 'totalsType' => '' ),
'fecha_de_inicio_del_contrato' => array( 'totalsType' => '' ),
'fecha_de_fin_del_contrato' => array( 'totalsType' => '' ),
'fecha_de_inicio_de_ejecucion' => array( 'totalsType' => '' ),
'fecha_de_fin_de_ejecucion' => array( 'totalsType' => '' ),
'condiciones_de_entrega' => array( 'totalsType' => '' ),
'tipodocproveedor' => array( 'totalsType' => '' ),
'documento_proveedor' => array( 'totalsType' => '' ),
'proveedor_adjudicado' => array( 'totalsType' => '' ),
'es_grupo' => array( 'totalsType' => '' ),
'es_pyme' => array( 'totalsType' => '' ),
'habilita_pago_adelantado' => array( 'totalsType' => '' ),
'liquidaci_n' => array( 'totalsType' => '' ),
'obligaci_n_ambiental' => array( 'totalsType' => '' ),
'obligaciones_postconsumo' => array( 'totalsType' => '' ),
'reversion' => array( 'totalsType' => '' ),
'valor_del_contrato' => array( 'totalsType' => '' ),
'valor_de_pago_adelantado' => array( 'totalsType' => '' ),
'valor_facturado' => array( 'totalsType' => '' ),
'valor_pendiente_de_pago' => array( 'totalsType' => '' ),
'valor_pagado' => array( 'totalsType' => '' ),
'valor_amortizado' => array( 'totalsType' => '' ),
'valor_pendiente_de' => array( 'totalsType' => '' ),
'valor_pendiente_de_ejecucion' => array( 'totalsType' => '' ),
'estado_bpin' => array( 'totalsType' => '' ),
'c_digo_bpin' => array( 'totalsType' => '' ),
'anno_bpin' => array( 'totalsType' => '' ),
'saldo_cdp' => array( 'totalsType' => '' ),
'saldo_vigencia' => array( 'totalsType' => '' ),
'espostconflicto' => array( 'totalsType' => '' ),
'urlproceso' => array( 'totalsType' => '' ),
'destino_gasto' => array( 'totalsType' => '' ),
'origen_de_los_recursos' => array( 'totalsType' => '' ),
'd_as_adicionados' => array( 'totalsType' => '' ),
'puntos_del_acuerdo' => array( 'totalsType' => '' ),
'pilares_del_acuerdo' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'documento_proveedor',
'proveedor_adjudicado',
'fecha_de_firma',
'fecha_de_inicio_de_ejecucion',
'fecha_de_fin_de_ejecucion',
'valor_del_contrato',
'c_digo_bpin',
'anno_bpin',
'urlproceso' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'anno_bpin',
'valor_pendiente_de_pago',
'valor_pendiente_de_ejecucion',
'valor_pendiente_de',
'valor_pagado',
'valor_facturado',
'valor_del_contrato',
'valor_de_pago_adelantado',
'valor_amortizado',
'urlproceso',
'tipodocproveedor',
'tipo_de_contrato',
'saldo_vigencia',
'saldo_cdp',
'reversion',
'referencia_del_contrato',
'puntos_del_acuerdo',
'proveedor_adjudicado',
'proceso_de_compra',
'pilares_del_acuerdo',
'origen_de_los_recursos',
'obligaciones_postconsumo',
'obligaci_n_ambiental',
'nit_entidad',
'modalidad_de_contratacion',
'liquidaci_n',
'justificacion_modalidad_de',
'id_contrato',
'id',
'habilita_pago_adelantado',
'fecha_de_inicio_del_contrato',
'fecha_de_inicio_de_ejecucion',
'fecha_de_firma',
'fecha_de_fin_del_contrato',
'fecha_de_fin_de_ejecucion',
'estado_contrato',
'estado_bpin',
'espostconflicto',
'es_pyme',
'es_grupo',
'documento_proveedor',
'destino_gasto',
'descripcion_del_proceso',
'd_as_adicionados',
'condiciones_de_entrega',
'codigo_de_categoria_principal',
'c_digo_bpin' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'documento_proveedor' => array( 'simple_grid_field26',
'simple_grid_field' ),
'proveedor_adjudicado' => array( 'simple_grid_field27',
'simple_grid_field28' ),
'fecha_de_firma' => array( 'simple_grid_field19',
'simple_grid_field20' ),
'fecha_de_inicio_de_ejecucion' => array( 'simple_grid_field22',
'simple_grid_field24' ),
'fecha_de_fin_de_ejecucion' => array( 'simple_grid_field23',
'simple_grid_field25' ),
'valor_del_contrato' => array( 'simple_grid_field35',
'simple_grid_field36' ),
'c_digo_bpin' => array( 'simple_grid_field44',
'simple_grid_field46' ),
'anno_bpin' => array( 'simple_grid_field45',
'simple_grid_field47' ),
'urlproceso' => array( 'simple_grid_field49',
'simple_grid_field50' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'add',
'delete',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ),
'grid' => array( 'simple_grid_field',
'simple_grid_field26',
'simple_grid_field28',
'simple_grid_field27',
'simple_grid_field20',
'simple_grid_field19',
'simple_grid_field24',
'simple_grid_field22',
'simple_grid_field25',
'simple_grid_field23',
'simple_grid_field36',
'simple_grid_field35',
'simple_grid_field46',
'simple_grid_field44',
'simple_grid_field47',
'simple_grid_field45',
'simple_grid_field50',
'simple_grid_field49',
'grid_edit',
'grid_view',
'grid_checkbox_head',
'grid_checkbox' ) ),
'formXtTags' => array( 'above-grid' => array( 'add_link',
'deleteselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field49' => 'grid',
'grid_edit' => 'grid',
'grid_view' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'delete_selected' => array( 'delete_selected' ),
'delete' => array( 'delete' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'export' => array( 'export' ),
'export_selected' => array( 'export_selected' ),
'import' => array( 'import' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field27',
'search_panel_field28',
'search_panel_field30',
'search_panel_field31',
'search_panel_field33',
'search_panel_field34',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52',
'search_panel_field53',
'search_panel_field54' ),
'logo' => array( 'logo1' ),
'userinfo_link' => array( 'userinfo_link' ),
'grid_field' => array( 'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field19',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field35',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field49' ),
'grid_field_label' => array( 'simple_grid_field',
'simple_grid_field28',
'simple_grid_field20',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field36',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field50' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'documento_proveedor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'proveedor_adjudicado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_firma_fieldheadercolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_inicio_de_ejecucion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_fin_de_ejecucion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'valor_del_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'c_digo_bpin_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'anno_bpin_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'urlproceso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'edit_column',
'view_column' ),
'items' => array( 'grid_edit',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'documento_proveedor_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'proveedor_adjudicado_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_firma_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_inicio_de_ejecucion_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_fin_de_ejecucion_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'valor_del_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'c_digo_bpin_fieldcolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'anno_bpin_fieldcolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'urlproceso_fieldcolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 11,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'delete' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'documento_proveedor',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'documento_proveedor',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'proveedor_adjudicado',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'proveedor_adjudicado',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'fecha_de_firma',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'fecha_de_firma',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'fecha_de_inicio_de_ejecucion',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'fecha_de_inicio_de_ejecucion',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'fecha_de_fin_de_ejecucion',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'fecha_de_fin_de_ejecucion',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'valor_del_contrato',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'valor_del_contrato',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'c_digo_bpin',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'c_digo_bpin',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'anno_bpin',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'anno_bpin',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'urlproceso',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'urlproceso',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit',
'grid_view' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export',
'-2',
'import' ) ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'delete' => array( 'type' => 'delete' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field31',
'search_panel_field30',
'search_panel_field28',
'search_panel_field27',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'anno_bpin',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'c_digo_bpin',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field3' => array( 'field' => 'codigo_de_categoria_principal',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'condiciones_de_entrega',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field5' => array( 'field' => 'd_as_adicionados',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field7' => array( 'field' => 'descripcion_del_proceso',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field8' => array( 'field' => 'destino_gasto',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field9' => array( 'field' => 'documento_proveedor',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field11' => array( 'field' => 'es_grupo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'es_pyme',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'espostconflicto',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field14' => array( 'field' => 'estado_bpin',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field15' => array( 'field' => 'estado_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field16' => array( 'field' => 'fecha_de_fin_de_ejecucion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field17' => array( 'field' => 'fecha_de_fin_del_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'fecha_de_firma',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field19' => array( 'field' => 'fecha_de_inicio_de_ejecucion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field20' => array( 'field' => 'fecha_de_inicio_del_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field21' => array( 'field' => 'habilita_pago_adelantado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field22' => array( 'field' => 'id',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'id_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field24' => array( 'field' => 'justificacion_modalidad_de',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field25' => array( 'field' => 'liquidaci_n',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field27' => array( 'field' => 'modalidad_de_contratacion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field28' => array( 'field' => 'nit_entidad',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field30' => array( 'field' => 'obligaci_n_ambiental',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field31' => array( 'field' => 'obligaciones_postconsumo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field33' => array( 'field' => 'origen_de_los_recursos',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field34' => array( 'field' => 'pilares_del_acuerdo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field35' => array( 'field' => 'proceso_de_compra',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field36' => array( 'field' => 'proveedor_adjudicado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field37' => array( 'field' => 'puntos_del_acuerdo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field39' => array( 'field' => 'referencia_del_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field40' => array( 'field' => 'reversion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field41' => array( 'field' => 'saldo_cdp',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field42' => array( 'field' => 'saldo_vigencia',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field44' => array( 'field' => 'tipo_de_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field45' => array( 'field' => 'tipodocproveedor',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field46' => array( 'field' => 'urlproceso',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field47' => array( 'field' => 'valor_amortizado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field48' => array( 'field' => 'valor_de_pago_adelantado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field49' => array( 'field' => 'valor_del_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field50' => array( 'field' => 'valor_facturado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field51' => array( 'field' => 'valor_pagado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field52' => array( 'field' => 'valor_pendiente_de',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field53' => array( 'field' => 'valor_pendiente_de_ejecucion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field54' => array( 'field' => 'valor_pendiente_de_pago',
'type' => 'search_panel_field',
'required' => false ),
'logo1' => array( 'type' => 'logo' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'simple_grid_field26' => array( 'field' => 'documento_proveedor',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'documento_proveedor' ),
'simple_grid_field27' => array( 'field' => 'proveedor_adjudicado',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'proveedor_adjudicado' ),
'simple_grid_field19' => array( 'field' => 'fecha_de_firma',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field20' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_firma' ),
'simple_grid_field22' => array( 'field' => 'fecha_de_inicio_de_ejecucion',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_inicio_de_ejecucion' ),
'simple_grid_field23' => array( 'field' => 'fecha_de_fin_de_ejecucion',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field25' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_fin_de_ejecucion' ),
'simple_grid_field35' => array( 'field' => 'valor_del_contrato',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'valor_del_contrato' ),
'simple_grid_field44' => array( 'field' => 'c_digo_bpin',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'c_digo_bpin' ),
'simple_grid_field45' => array( 'field' => 'anno_bpin',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'anno_bpin' ),
'simple_grid_field49' => array( 'field' => 'urlproceso',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'urlproceso' ),
'grid_edit' => array( 'type' => 'grid_edit' ),
'grid_view' => array( 'type' => 'grid_view' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>