<?php
			$optionsArray = array( 'totals' => array( 'cxc_id' => array( 'totalsType' => '' ),
'de_pre' => array( 'totalsType' => '' ),
'de_num' => array( 'totalsType' => '' ),
'inf_id_fk' => array( 'totalsType' => '' ),
'inf_hash_fk' => array( 'totalsType' => '' ),
'id_cont' => array( 'totalsType' => '' ),
'id_consecutivo' => array( 'totalsType' => '' ),
'cxc_tipocontrato' => array( 'totalsType' => '' ),
'cxc_cont' => array( 'totalsType' => '' ),
'cxc_anio' => array( 'totalsType' => '' ),
'cxc_razonsocial' => array( 'totalsType' => '' ),
'cxc_tipodoc' => array( 'totalsType' => '' ),
'cxc_numdoc' => array( 'totalsType' => '' ),
'cxc_periodoi' => array( 'totalsType' => '' ),
'cxc_periodof' => array( 'totalsType' => '' ),
'cxc_valor' => array( 'totalsType' => '' ),
'cxc_fechaelab' => array( 'totalsType' => '' ),
'cxc_planilla' => array( 'totalsType' => '' ),
'cxc_planillafecha' => array( 'totalsType' => '' ),
'cxc_planillavalor' => array( 'totalsType' => '' ),
'sup_name' => array( 'totalsType' => '' ),
'sup_cargo' => array( 'totalsType' => '' ),
'sup_dep' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_fecha' => array( 'totalsType' => '' ),
'sys_status' => array( 'totalsType' => '' ),
'cxc_fondopenvol' => array( 'totalsType' => '' ),
'cxc_pagoafc' => array( 'totalsType' => '' ),
'sys_radicauser' => array( 'totalsType' => '' ),
'sys_radicadate' => array( 'totalsType' => '' ),
'sys_radicatime' => array( 'totalsType' => '' ),
'sys_radicaperiodo' => array( 'totalsType' => '' ),
'ctrl' => array( 'totalsType' => '' ),
'send_user' => array( 'totalsType' => '' ),
'send_mail' => array( 'totalsType' => '' ),
'send_mail_obs' => array( 'totalsType' => '' ),
'send_date' => array( 'totalsType' => '' ),
'send_dev_mail' => array( 'totalsType' => '' ),
'send_dev_mail_obs' => array( 'totalsType' => '' ),
'send_dev_date' => array( 'totalsType' => '' ),
'send_dev_func' => array( 'totalsType' => '' ),
'evento_type_id_fk' => array( 'totalsType' => '' ),
'cont_fechai' => array( 'totalsType' => '' ),
'cont_fechaf' => array( 'totalsType' => '' ),
'cont_cdp' => array( 'totalsType' => '' ),
'cont_rp' => array( 'totalsType' => '' ),
'cont_rubro' => array( 'totalsType' => '' ),
'cont_uej' => array( 'totalsType' => '' ),
'cont_uso' => array( 'totalsType' => '' ),
'cont_valorcontrato' => array( 'totalsType' => '' ),
'cont_pagomensual' => array( 'totalsType' => '' ),
'cont_banco' => array( 'totalsType' => '' ),
'cont_cuentatipo' => array( 'totalsType' => '' ),
'cont_cuentanumero' => array( 'totalsType' => '' ),
'cont_factura' => array( 'totalsType' => '' ),
'inf_mes' => array( 'totalsType' => '' ),
'inf_tipopago' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_consecutivo',
'cxc_cont',
'cxc_razonsocial',
'cxc_periodoi',
'cxc_periodof',
'cxc_valor',
'cxc_planilla',
'cxc_planillafecha',
'cxc_planillavalor',
'sup_name',
'sup_cargo',
'sup_dep',
'inf_mes',
'inf_tipopago' ),
'exportFields' => array( 'id_consecutivo',
'cxc_cont',
'cxc_razonsocial',
'cxc_periodoi',
'cxc_periodof',
'cxc_valor',
'cxc_planilla',
'cxc_planillafecha',
'cxc_planillavalor',
'sup_name',
'sup_cargo',
'sup_dep',
'inf_mes',
'inf_tipopago' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_consecutivo' => array( 'export_field6' ),
'cxc_cont' => array( 'export_field8' ),
'cxc_razonsocial' => array( 'export_field10' ),
'cxc_periodoi' => array( 'export_field13' ),
'cxc_periodof' => array( 'export_field14' ),
'cxc_valor' => array( 'export_field15' ),
'cxc_planilla' => array( 'export_field17' ),
'cxc_planillafecha' => array( 'export_field18' ),
'cxc_planillavalor' => array( 'export_field19' ),
'sup_name' => array( 'export_field20' ),
'sup_cargo' => array( 'export_field21' ),
'sup_dep' => array( 'export_field22' ),
'inf_mes' => array( 'export_field' ),
'inf_tipopago' => array( 'export_field1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field6',
'export_field8',
'export_field10',
'export_field13',
'export_field14',
'export_field15',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field',
'export_field1' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field6' => 'grid',
'export_field8' => 'grid',
'export_field10' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field6',
'export_field8',
'export_field10',
'export_field13',
'export_field14',
'export_field15',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field',
'export_field1' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field6',
'export_field8',
'export_field10',
'export_field13',
'export_field14',
'export_field15',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field',
'export_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field6' => array( 'field' => 'id_consecutivo',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'cxc_cont',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'cxc_razonsocial',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'cxc_periodoi',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'cxc_periodof',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'cxc_valor',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'cxc_planilla',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'cxc_planillafecha',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'cxc_planillavalor',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'sup_name',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'sup_cargo',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'sup_dep',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'inf_mes',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'inf_tipopago',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>