<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'inf_anexo_id',
'inf_id_fk',
'id_cont_fk',
'anexo_titulo',
'anexo_fecha',
'anexo_hora',
'anexo_usuario',
'ctrl',
'anexo_file_sup',
'anexo_hash',
'anexo_grupo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'inf_anexo_id' => array( 'import_field' ),
'inf_id_fk' => array( 'import_field1' ),
'id_cont_fk' => array( 'import_field2' ),
'anexo_titulo' => array( 'import_field3' ),
'anexo_fecha' => array( 'import_field5' ),
'anexo_hora' => array( 'import_field6' ),
'anexo_usuario' => array( 'import_field7' ),
'ctrl' => array( 'import_field8' ),
'anexo_file_sup' => array( 'import_field9' ),
'anexo_hash' => array( 'import_field4' ),
'anexo_grupo' => array( 'import_field10' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field4',
'import_field10' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field4' => 'grid',
'import_field10' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field4',
'import_field10' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field4',
'import_field10' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'inf_anexo_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'inf_id_fk',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'id_cont_fk',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'anexo_titulo',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'anexo_fecha',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'anexo_hora',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'anexo_usuario',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'ctrl',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'anexo_file_sup',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'anexo_hash',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'anexo_grupo',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>