<?php
			$optionsArray = array( 'totals' => array( 'inf_anexo_id' => array( 'totalsType' => '' ),
'inf_id_fk' => array( 'totalsType' => '' ),
'id_cont_fk' => array( 'totalsType' => '' ),
'anexo_hash' => array( 'totalsType' => '' ),
'anexo_grupo' => array( 'totalsType' => '' ),
'anexo_titulo' => array( 'totalsType' => '' ),
'anexo_file' => array( 'totalsType' => '' ),
'anexo_file_sup' => array( 'totalsType' => '' ),
'anexo_fecha' => array( 'totalsType' => '' ),
'anexo_hora' => array( 'totalsType' => '' ),
'anexo_usuario' => array( 'totalsType' => '' ),
'ctrl' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'inf_anexo_id',
'inf_id_fk',
'id_cont_fk',
'anexo_titulo',
'anexo_fecha',
'anexo_hora',
'anexo_usuario',
'ctrl',
'anexo_file_sup',
'anexo_hash',
'anexo_grupo' ),
'exportFields' => array( 'inf_anexo_id',
'inf_id_fk',
'id_cont_fk',
'anexo_titulo',
'anexo_fecha',
'anexo_hora',
'anexo_usuario',
'ctrl',
'anexo_file_sup',
'anexo_hash',
'anexo_grupo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'inf_anexo_id' => array( 'export_field' ),
'inf_id_fk' => array( 'export_field1' ),
'id_cont_fk' => array( 'export_field2' ),
'anexo_titulo' => array( 'export_field3' ),
'anexo_fecha' => array( 'export_field5' ),
'anexo_hora' => array( 'export_field6' ),
'anexo_usuario' => array( 'export_field7' ),
'ctrl' => array( 'export_field8' ),
'anexo_file_sup' => array( 'export_field9' ),
'anexo_hash' => array( 'export_field4' ),
'anexo_grupo' => array( 'export_field10' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field4',
'export_field10' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field4' => 'grid',
'export_field10' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field4',
'export_field10' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field4',
'export_field10' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'inf_anexo_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'inf_id_fk',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'id_cont_fk',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'anexo_titulo',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'anexo_fecha',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'anexo_hora',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'anexo_usuario',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'ctrl',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'anexo_file_sup',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'anexo_hash',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'anexo_grupo',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>