<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'nit_entidad' => array( 'totalsType' => '' ),
'proceso_de_compra' => array( 'totalsType' => '' ),
'id_contrato' => array( 'totalsType' => '' ),
'referencia_del_contrato' => array( 'totalsType' => '' ),
'estado_contrato' => array( 'totalsType' => '' ),
'codigo_de_categoria_principal' => array( 'totalsType' => '' ),
'descripcion_del_proceso' => array( 'totalsType' => '' ),
'tipo_de_contrato' => array( 'totalsType' => '' ),
'modalidad_de_contratacion' => array( 'totalsType' => '' ),
'justificacion_modalidad_de' => array( 'totalsType' => '' ),
'fecha_de_firma' => array( 'totalsType' => '' ),
'fecha_de_inicio_del_contrato' => array( 'totalsType' => '' ),
'fecha_de_fin_del_contrato' => array( 'totalsType' => '' ),
'fecha_de_inicio_de_ejecucion' => array( 'totalsType' => '' ),
'fecha_de_fin_de_ejecucion' => array( 'totalsType' => '' ),
'condiciones_de_entrega' => array( 'totalsType' => '' ),
'tipodocproveedor' => array( 'totalsType' => '' ),
'documento_proveedor' => array( 'totalsType' => '' ),
'proveedor_adjudicado' => array( 'totalsType' => '' ),
'es_grupo' => array( 'totalsType' => '' ),
'es_pyme' => array( 'totalsType' => '' ),
'habilita_pago_adelantado' => array( 'totalsType' => '' ),
'liquidaci_n' => array( 'totalsType' => '' ),
'obligaci_n_ambiental' => array( 'totalsType' => '' ),
'obligaciones_postconsumo' => array( 'totalsType' => '' ),
'reversion' => array( 'totalsType' => '' ),
'valor_del_contrato' => array( 'totalsType' => '' ),
'valor_de_pago_adelantado' => array( 'totalsType' => '' ),
'valor_facturado' => array( 'totalsType' => '' ),
'valor_pendiente_de_pago' => array( 'totalsType' => '' ),
'valor_pagado' => array( 'totalsType' => '' ),
'valor_amortizado' => array( 'totalsType' => '' ),
'valor_pendiente_de' => array( 'totalsType' => '' ),
'valor_pendiente_de_ejecucion' => array( 'totalsType' => '' ),
'estado_bpin' => array( 'totalsType' => '' ),
'c_digo_bpin' => array( 'totalsType' => '' ),
'anno_bpin' => array( 'totalsType' => '' ),
'saldo_cdp' => array( 'totalsType' => '' ),
'saldo_vigencia' => array( 'totalsType' => '' ),
'espostconflicto' => array( 'totalsType' => '' ),
'urlproceso' => array( 'totalsType' => '' ),
'destino_gasto' => array( 'totalsType' => '' ),
'origen_de_los_recursos' => array( 'totalsType' => '' ),
'd_as_adicionados' => array( 'totalsType' => '' ),
'puntos_del_acuerdo' => array( 'totalsType' => '' ),
'pilares_del_acuerdo' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'nit_entidad',
'proceso_de_compra',
'id_contrato',
'referencia_del_contrato',
'estado_contrato',
'codigo_de_categoria_principal',
'descripcion_del_proceso',
'tipo_de_contrato',
'modalidad_de_contratacion',
'justificacion_modalidad_de',
'fecha_de_firma',
'fecha_de_inicio_del_contrato',
'fecha_de_fin_del_contrato',
'fecha_de_inicio_de_ejecucion',
'fecha_de_fin_de_ejecucion',
'condiciones_de_entrega',
'tipodocproveedor',
'documento_proveedor',
'proveedor_adjudicado',
'es_grupo',
'es_pyme',
'habilita_pago_adelantado',
'liquidaci_n',
'obligaci_n_ambiental',
'obligaciones_postconsumo',
'reversion',
'valor_del_contrato',
'valor_de_pago_adelantado',
'valor_facturado',
'valor_pendiente_de_pago',
'valor_pagado',
'valor_amortizado',
'valor_pendiente_de',
'valor_pendiente_de_ejecucion',
'estado_bpin',
'c_digo_bpin',
'anno_bpin',
'saldo_cdp',
'saldo_vigencia',
'espostconflicto',
'urlproceso',
'destino_gasto',
'origen_de_los_recursos',
'd_as_adicionados',
'puntos_del_acuerdo',
'pilares_del_acuerdo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'simple_grid_field',
'simple_grid_field1' ),
'nit_entidad' => array( 'simple_grid_field2',
'simple_grid_field3' ),
'proceso_de_compra' => array( 'simple_grid_field10',
'simple_grid_field55' ),
'id_contrato' => array( 'simple_grid_field11',
'simple_grid_field56' ),
'referencia_del_contrato' => array( 'simple_grid_field12',
'simple_grid_field57' ),
'estado_contrato' => array( 'simple_grid_field13',
'simple_grid_field58' ),
'codigo_de_categoria_principal' => array( 'simple_grid_field14',
'simple_grid_field59' ),
'descripcion_del_proceso' => array( 'simple_grid_field15',
'simple_grid_field60' ),
'tipo_de_contrato' => array( 'simple_grid_field16',
'simple_grid_field61' ),
'modalidad_de_contratacion' => array( 'simple_grid_field17',
'simple_grid_field62' ),
'justificacion_modalidad_de' => array( 'simple_grid_field18',
'simple_grid_field63' ),
'fecha_de_firma' => array( 'simple_grid_field19',
'simple_grid_field64' ),
'fecha_de_inicio_del_contrato' => array( 'simple_grid_field20',
'simple_grid_field65' ),
'fecha_de_fin_del_contrato' => array( 'simple_grid_field21',
'simple_grid_field66' ),
'fecha_de_inicio_de_ejecucion' => array( 'simple_grid_field22',
'simple_grid_field67' ),
'fecha_de_fin_de_ejecucion' => array( 'simple_grid_field23',
'simple_grid_field68' ),
'condiciones_de_entrega' => array( 'simple_grid_field24',
'simple_grid_field69' ),
'tipodocproveedor' => array( 'simple_grid_field25',
'simple_grid_field70' ),
'documento_proveedor' => array( 'simple_grid_field26',
'simple_grid_field71' ),
'proveedor_adjudicado' => array( 'simple_grid_field27',
'simple_grid_field72' ),
'es_grupo' => array( 'simple_grid_field28',
'simple_grid_field73' ),
'es_pyme' => array( 'simple_grid_field29',
'simple_grid_field74' ),
'habilita_pago_adelantado' => array( 'simple_grid_field30',
'simple_grid_field75' ),
'liquidaci_n' => array( 'simple_grid_field31',
'simple_grid_field76' ),
'obligaci_n_ambiental' => array( 'simple_grid_field32',
'simple_grid_field77' ),
'obligaciones_postconsumo' => array( 'simple_grid_field33',
'simple_grid_field78' ),
'reversion' => array( 'simple_grid_field34',
'simple_grid_field79' ),
'valor_del_contrato' => array( 'simple_grid_field35',
'simple_grid_field80' ),
'valor_de_pago_adelantado' => array( 'simple_grid_field36',
'simple_grid_field81' ),
'valor_facturado' => array( 'simple_grid_field37',
'simple_grid_field82' ),
'valor_pendiente_de_pago' => array( 'simple_grid_field38',
'simple_grid_field83' ),
'valor_pagado' => array( 'simple_grid_field39',
'simple_grid_field84' ),
'valor_amortizado' => array( 'simple_grid_field40',
'simple_grid_field85' ),
'valor_pendiente_de' => array( 'simple_grid_field41',
'simple_grid_field86' ),
'valor_pendiente_de_ejecucion' => array( 'simple_grid_field42',
'simple_grid_field87' ),
'estado_bpin' => array( 'simple_grid_field43',
'simple_grid_field88' ),
'c_digo_bpin' => array( 'simple_grid_field44',
'simple_grid_field89' ),
'anno_bpin' => array( 'simple_grid_field45',
'simple_grid_field90' ),
'saldo_cdp' => array( 'simple_grid_field46',
'simple_grid_field91' ),
'saldo_vigencia' => array( 'simple_grid_field47',
'simple_grid_field92' ),
'espostconflicto' => array( 'simple_grid_field48',
'simple_grid_field93' ),
'urlproceso' => array( 'simple_grid_field49',
'simple_grid_field94' ),
'destino_gasto' => array( 'simple_grid_field50',
'simple_grid_field95' ),
'origen_de_los_recursos' => array( 'simple_grid_field51',
'simple_grid_field96' ),
'd_as_adicionados' => array( 'simple_grid_field52',
'simple_grid_field97' ),
'puntos_del_acuerdo' => array( 'simple_grid_field53',
'simple_grid_field98' ),
'pilares_del_acuerdo' => array( 'simple_grid_field54',
'simple_grid_field99' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader' ),
'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field1',
'simple_grid_field',
'simple_grid_field3',
'simple_grid_field2',
'simple_grid_field55',
'simple_grid_field10',
'simple_grid_field56',
'simple_grid_field11',
'simple_grid_field57',
'simple_grid_field12',
'simple_grid_field58',
'simple_grid_field13',
'simple_grid_field59',
'simple_grid_field14',
'simple_grid_field60',
'simple_grid_field15',
'simple_grid_field61',
'simple_grid_field16',
'simple_grid_field62',
'simple_grid_field17',
'simple_grid_field63',
'simple_grid_field18',
'simple_grid_field64',
'simple_grid_field19',
'simple_grid_field65',
'simple_grid_field20',
'simple_grid_field66',
'simple_grid_field21',
'simple_grid_field67',
'simple_grid_field22',
'simple_grid_field68',
'simple_grid_field23',
'simple_grid_field69',
'simple_grid_field24',
'simple_grid_field70',
'simple_grid_field25',
'simple_grid_field71',
'simple_grid_field26',
'simple_grid_field72',
'simple_grid_field27',
'simple_grid_field73',
'simple_grid_field28',
'simple_grid_field74',
'simple_grid_field29',
'simple_grid_field75',
'simple_grid_field30',
'simple_grid_field76',
'simple_grid_field31',
'simple_grid_field77',
'simple_grid_field32',
'simple_grid_field78',
'simple_grid_field33',
'simple_grid_field79',
'simple_grid_field34',
'simple_grid_field80',
'simple_grid_field35',
'simple_grid_field81',
'simple_grid_field36',
'simple_grid_field82',
'simple_grid_field37',
'simple_grid_field83',
'simple_grid_field38',
'simple_grid_field84',
'simple_grid_field39',
'simple_grid_field85',
'simple_grid_field40',
'simple_grid_field86',
'simple_grid_field41',
'simple_grid_field87',
'simple_grid_field42',
'simple_grid_field88',
'simple_grid_field43',
'simple_grid_field89',
'simple_grid_field44',
'simple_grid_field90',
'simple_grid_field45',
'simple_grid_field91',
'simple_grid_field46',
'simple_grid_field92',
'simple_grid_field47',
'simple_grid_field93',
'simple_grid_field48',
'simple_grid_field94',
'simple_grid_field49',
'simple_grid_field95',
'simple_grid_field50',
'simple_grid_field96',
'simple_grid_field51',
'simple_grid_field97',
'simple_grid_field52',
'simple_grid_field98',
'simple_grid_field53',
'simple_grid_field99',
'simple_grid_field54' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'print_pages' => 'above-grid',
'simple_grid_field1' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field80' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field81' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field82' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field83' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field84' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field85' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field86' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field87' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field88' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field89' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field90' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field91' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field92' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field93' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field94' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field95' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field96' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field97' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field98' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field99' => 'grid',
'simple_grid_field54' => 'grid' ),
'itemLocations' => array( 'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field80' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field81' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field82' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field83' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field84' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field85' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field86' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field87' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field88' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field89' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field90' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'simple_grid_field91' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'simple_grid_field92' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ),
'simple_grid_field93' => array( 'location' => 'grid',
'cellId' => 'headcell_field40' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'cell_field40' ),
'simple_grid_field94' => array( 'location' => 'grid',
'cellId' => 'headcell_field41' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'cell_field41' ),
'simple_grid_field95' => array( 'location' => 'grid',
'cellId' => 'headcell_field42' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'cell_field42' ),
'simple_grid_field96' => array( 'location' => 'grid',
'cellId' => 'headcell_field43' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'cell_field43' ),
'simple_grid_field97' => array( 'location' => 'grid',
'cellId' => 'headcell_field44' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'cell_field44' ),
'simple_grid_field98' => array( 'location' => 'grid',
'cellId' => 'headcell_field45' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'cell_field45' ),
'simple_grid_field99' => array( 'location' => 'grid',
'cellId' => 'headcell_field46' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'cell_field46' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field2',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54' ),
'grid_field_label' => array( 'simple_grid_field1',
'simple_grid_field3',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field79',
'simple_grid_field80',
'simple_grid_field81',
'simple_grid_field82',
'simple_grid_field83',
'simple_grid_field84',
'simple_grid_field85',
'simple_grid_field86',
'simple_grid_field87',
'simple_grid_field88',
'simple_grid_field89',
'simple_grid_field90',
'simple_grid_field91',
'simple_grid_field92',
'simple_grid_field93',
'simple_grid_field94',
'simple_grid_field95',
'simple_grid_field96',
'simple_grid_field97',
'simple_grid_field98',
'simple_grid_field99' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'nit_entidad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'proceso_de_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'id_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'referencia_del_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'estado_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'codigo_de_categoria_principal_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'descripcion_del_proceso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'tipo_de_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'modalidad_de_contratacion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'justificacion_modalidad_de_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_firma_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_inicio_del_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_fin_del_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_inicio_de_ejecucion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'fecha_de_fin_de_ejecucion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'condiciones_de_entrega_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'tipodocproveedor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'documento_proveedor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'proveedor_adjudicado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'es_grupo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'es_pyme_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'habilita_pago_adelantado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'liquidaci_n_fieldheadercolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'obligaci_n_ambiental_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'obligaciones_postconsumo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'reversion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'valor_del_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field80' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'valor_de_pago_adelantado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field81' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'valor_facturado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field82' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'valor_pendiente_de_pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field83' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'valor_pagado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field84' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'valor_amortizado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field85' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'valor_pendiente_de_fieldheadercolumn' ),
'items' => array( 'simple_grid_field86' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'valor_pendiente_de_ejecucion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field87' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'estado_bpin_fieldheadercolumn' ),
'items' => array( 'simple_grid_field88' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'c_digo_bpin_fieldheadercolumn' ),
'items' => array( 'simple_grid_field89' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'anno_bpin_fieldheadercolumn' ),
'items' => array( 'simple_grid_field90' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'saldo_cdp_fieldheadercolumn' ),
'items' => array( 'simple_grid_field91' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'saldo_vigencia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field92' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 0 ),
'tags' => array( 'espostconflicto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field93' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 0 ),
'tags' => array( 'urlproceso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field94' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 0 ),
'tags' => array( 'destino_gasto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field95' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 0 ),
'tags' => array( 'origen_de_los_recursos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field96' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 0 ),
'tags' => array( 'd_as_adicionados_fieldheadercolumn' ),
'items' => array( 'simple_grid_field97' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 0 ),
'tags' => array( 'puntos_del_acuerdo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field98' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 0 ),
'tags' => array( 'pilares_del_acuerdo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field99' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'id_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'nit_entidad_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'proceso_de_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'id_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'referencia_del_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'estado_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'codigo_de_categoria_principal_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'descripcion_del_proceso_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'tipo_de_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'modalidad_de_contratacion_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'justificacion_modalidad_de_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_firma_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_inicio_del_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_fin_del_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_inicio_de_ejecucion_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'fecha_de_fin_de_ejecucion_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'condiciones_de_entrega_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'tipodocproveedor_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'documento_proveedor_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'proveedor_adjudicado_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'es_grupo_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'es_pyme_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'habilita_pago_adelantado_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'liquidaci_n_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'obligaci_n_ambiental_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'obligaciones_postconsumo_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'reversion_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'valor_del_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'valor_de_pago_adelantado_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'valor_facturado_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'valor_pendiente_de_pago_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'valor_pagado_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'valor_amortizado_fieldcolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'valor_pendiente_de_fieldcolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'valor_pendiente_de_ejecucion_fieldcolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'estado_bpin_fieldcolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'c_digo_bpin_fieldcolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'anno_bpin_fieldcolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'saldo_cdp_fieldcolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'saldo_vigencia_fieldcolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 1 ),
'tags' => array( 'espostconflicto_fieldcolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 1 ),
'tags' => array( 'urlproceso_fieldcolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 1 ),
'tags' => array( 'destino_gasto_fieldcolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 1 ),
'tags' => array( 'origen_de_los_recursos_fieldcolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 1 ),
'tags' => array( 'd_as_adicionados_fieldcolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 1 ),
'tags' => array( 'puntos_del_acuerdo_fieldcolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 1 ),
'tags' => array( 'pilares_del_acuerdo_fieldcolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 47,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ),
array( 'cell' => 'headcell_field40' ),
array( 'cell' => 'headcell_field41' ),
array( 'cell' => 'headcell_field42' ),
array( 'cell' => 'headcell_field43' ),
array( 'cell' => 'headcell_field44' ),
array( 'cell' => 'headcell_field45' ),
array( 'cell' => 'headcell_field46' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field43' ),
array( 'cell' => 'cell_field44' ),
array( 'cell' => 'cell_field45' ),
array( 'cell' => 'cell_field46' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ),
array( 'cell' => 'footcell_field40' ),
array( 'cell' => 'footcell_field41' ),
array( 'cell' => 'footcell_field42' ),
array( 'cell' => 'footcell_field43' ),
array( 'cell' => 'footcell_field44' ),
array( 'cell' => 'footcell_field45' ),
array( 'cell' => 'footcell_field46' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'id',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'nit_entidad',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'nit_entidad',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'proceso_de_compra',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'proceso_de_compra',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'id_contrato',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'id_contrato',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'referencia_del_contrato',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'referencia_del_contrato',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'estado_contrato',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'estado_contrato',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'codigo_de_categoria_principal',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'codigo_de_categoria_principal',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'descripcion_del_proceso',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'descripcion_del_proceso',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'tipo_de_contrato',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'tipo_de_contrato',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'modalidad_de_contratacion',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'modalidad_de_contratacion',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'justificacion_modalidad_de',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'justificacion_modalidad_de',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'fecha_de_firma',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'fecha_de_firma',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'fecha_de_inicio_del_contrato',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'fecha_de_inicio_del_contrato',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'fecha_de_fin_del_contrato',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'fecha_de_fin_del_contrato',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'fecha_de_inicio_de_ejecucion',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'fecha_de_inicio_de_ejecucion',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'fecha_de_fin_de_ejecucion',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'fecha_de_fin_de_ejecucion',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'condiciones_de_entrega',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'condiciones_de_entrega',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'tipodocproveedor',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'tipodocproveedor',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'documento_proveedor',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'documento_proveedor',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'proveedor_adjudicado',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'proveedor_adjudicado',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'es_grupo',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'es_grupo',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'es_pyme',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'es_pyme',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'habilita_pago_adelantado',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'habilita_pago_adelantado',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'liquidaci_n',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'liquidaci_n',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'obligaci_n_ambiental',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'obligaci_n_ambiental',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'obligaciones_postconsumo',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'obligaciones_postconsumo',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'reversion',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'reversion',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field80' ),
'field' => 'valor_del_contrato',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'valor_del_contrato',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field81' ),
'field' => 'valor_de_pago_adelantado',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'valor_de_pago_adelantado',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field82' ),
'field' => 'valor_facturado',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'valor_facturado',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field83' ),
'field' => 'valor_pendiente_de_pago',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'valor_pendiente_de_pago',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field84' ),
'field' => 'valor_pagado',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'valor_pagado',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field85' ),
'field' => 'valor_amortizado',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'valor_amortizado',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field86' ),
'field' => 'valor_pendiente_de',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'valor_pendiente_de',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field87' ),
'field' => 'valor_pendiente_de_ejecucion',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'valor_pendiente_de_ejecucion',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field88' ),
'field' => 'estado_bpin',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'estado_bpin',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field89' ),
'field' => 'c_digo_bpin',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'c_digo_bpin',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field90' ),
'field' => 'anno_bpin',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'anno_bpin',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field91' ),
'field' => 'saldo_cdp',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'saldo_cdp',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field92' ),
'field' => 'saldo_vigencia',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'saldo_vigencia',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field40' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field93' ),
'field' => 'espostconflicto',
'columnName' => 'field' ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'espostconflicto',
'columnName' => 'field' ),
'footcell_field40' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field41' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field94' ),
'field' => 'urlproceso',
'columnName' => 'field' ),
'cell_field41' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'urlproceso',
'columnName' => 'field' ),
'footcell_field41' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field42' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field95' ),
'field' => 'destino_gasto',
'columnName' => 'field' ),
'cell_field42' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'destino_gasto',
'columnName' => 'field' ),
'footcell_field42' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field43' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field96' ),
'field' => 'origen_de_los_recursos',
'columnName' => 'field' ),
'cell_field43' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'origen_de_los_recursos',
'columnName' => 'field' ),
'footcell_field43' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field44' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field97' ),
'field' => 'd_as_adicionados',
'columnName' => 'field' ),
'cell_field44' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'd_as_adicionados',
'columnName' => 'field' ),
'footcell_field44' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field45' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field98' ),
'field' => 'puntos_del_acuerdo',
'columnName' => 'field' ),
'cell_field45' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'puntos_del_acuerdo',
'columnName' => 'field' ),
'footcell_field45' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field46' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field99' ),
'field' => 'pilares_del_acuerdo',
'columnName' => 'field' ),
'cell_field46' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'pilares_del_acuerdo',
'columnName' => 'field' ),
'footcell_field46' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field' => array( 'field' => 'id',
'type' => 'grid_field' ),
'simple_grid_field1' => array( 'type' => 'grid_field_label',
'field' => 'id' ),
'simple_grid_field2' => array( 'field' => 'nit_entidad',
'type' => 'grid_field' ),
'simple_grid_field3' => array( 'type' => 'grid_field_label',
'field' => 'nit_entidad' ),
'simple_grid_field10' => array( 'field' => 'proceso_de_compra',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'proceso_de_compra' ),
'simple_grid_field11' => array( 'field' => 'id_contrato',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'id_contrato' ),
'simple_grid_field12' => array( 'field' => 'referencia_del_contrato',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'referencia_del_contrato' ),
'simple_grid_field13' => array( 'field' => 'estado_contrato',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'estado_contrato' ),
'simple_grid_field14' => array( 'field' => 'codigo_de_categoria_principal',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'codigo_de_categoria_principal' ),
'simple_grid_field15' => array( 'field' => 'descripcion_del_proceso',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'descripcion_del_proceso' ),
'simple_grid_field16' => array( 'field' => 'tipo_de_contrato',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'tipo_de_contrato' ),
'simple_grid_field17' => array( 'field' => 'modalidad_de_contratacion',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'modalidad_de_contratacion' ),
'simple_grid_field18' => array( 'field' => 'justificacion_modalidad_de',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'justificacion_modalidad_de' ),
'simple_grid_field19' => array( 'field' => 'fecha_de_firma',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_firma' ),
'simple_grid_field20' => array( 'field' => 'fecha_de_inicio_del_contrato',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_inicio_del_contrato' ),
'simple_grid_field21' => array( 'field' => 'fecha_de_fin_del_contrato',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_fin_del_contrato' ),
'simple_grid_field22' => array( 'field' => 'fecha_de_inicio_de_ejecucion',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_inicio_de_ejecucion' ),
'simple_grid_field23' => array( 'field' => 'fecha_de_fin_de_ejecucion',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'fecha_de_fin_de_ejecucion' ),
'simple_grid_field24' => array( 'field' => 'condiciones_de_entrega',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'condiciones_de_entrega' ),
'simple_grid_field25' => array( 'field' => 'tipodocproveedor',
'type' => 'grid_field' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'tipodocproveedor' ),
'simple_grid_field26' => array( 'field' => 'documento_proveedor',
'type' => 'grid_field' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'documento_proveedor' ),
'simple_grid_field27' => array( 'field' => 'proveedor_adjudicado',
'type' => 'grid_field' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'proveedor_adjudicado' ),
'simple_grid_field28' => array( 'field' => 'es_grupo',
'type' => 'grid_field' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'es_grupo' ),
'simple_grid_field29' => array( 'field' => 'es_pyme',
'type' => 'grid_field' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'es_pyme' ),
'simple_grid_field30' => array( 'field' => 'habilita_pago_adelantado',
'type' => 'grid_field' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'habilita_pago_adelantado' ),
'simple_grid_field31' => array( 'field' => 'liquidaci_n',
'type' => 'grid_field' ),
'simple_grid_field76' => array( 'type' => 'grid_field_label',
'field' => 'liquidaci_n' ),
'simple_grid_field32' => array( 'field' => 'obligaci_n_ambiental',
'type' => 'grid_field' ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'obligaci_n_ambiental' ),
'simple_grid_field33' => array( 'field' => 'obligaciones_postconsumo',
'type' => 'grid_field' ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'obligaciones_postconsumo' ),
'simple_grid_field34' => array( 'field' => 'reversion',
'type' => 'grid_field' ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'reversion' ),
'simple_grid_field35' => array( 'field' => 'valor_del_contrato',
'type' => 'grid_field' ),
'simple_grid_field80' => array( 'type' => 'grid_field_label',
'field' => 'valor_del_contrato' ),
'simple_grid_field36' => array( 'field' => 'valor_de_pago_adelantado',
'type' => 'grid_field' ),
'simple_grid_field81' => array( 'type' => 'grid_field_label',
'field' => 'valor_de_pago_adelantado' ),
'simple_grid_field37' => array( 'field' => 'valor_facturado',
'type' => 'grid_field' ),
'simple_grid_field82' => array( 'type' => 'grid_field_label',
'field' => 'valor_facturado' ),
'simple_grid_field38' => array( 'field' => 'valor_pendiente_de_pago',
'type' => 'grid_field' ),
'simple_grid_field83' => array( 'type' => 'grid_field_label',
'field' => 'valor_pendiente_de_pago' ),
'simple_grid_field39' => array( 'field' => 'valor_pagado',
'type' => 'grid_field' ),
'simple_grid_field84' => array( 'type' => 'grid_field_label',
'field' => 'valor_pagado' ),
'simple_grid_field40' => array( 'field' => 'valor_amortizado',
'type' => 'grid_field' ),
'simple_grid_field85' => array( 'type' => 'grid_field_label',
'field' => 'valor_amortizado' ),
'simple_grid_field41' => array( 'field' => 'valor_pendiente_de',
'type' => 'grid_field' ),
'simple_grid_field86' => array( 'type' => 'grid_field_label',
'field' => 'valor_pendiente_de' ),
'simple_grid_field42' => array( 'field' => 'valor_pendiente_de_ejecucion',
'type' => 'grid_field' ),
'simple_grid_field87' => array( 'type' => 'grid_field_label',
'field' => 'valor_pendiente_de_ejecucion' ),
'simple_grid_field43' => array( 'field' => 'estado_bpin',
'type' => 'grid_field' ),
'simple_grid_field88' => array( 'type' => 'grid_field_label',
'field' => 'estado_bpin' ),
'simple_grid_field44' => array( 'field' => 'c_digo_bpin',
'type' => 'grid_field' ),
'simple_grid_field89' => array( 'type' => 'grid_field_label',
'field' => 'c_digo_bpin' ),
'simple_grid_field45' => array( 'field' => 'anno_bpin',
'type' => 'grid_field' ),
'simple_grid_field90' => array( 'type' => 'grid_field_label',
'field' => 'anno_bpin' ),
'simple_grid_field46' => array( 'field' => 'saldo_cdp',
'type' => 'grid_field' ),
'simple_grid_field91' => array( 'type' => 'grid_field_label',
'field' => 'saldo_cdp' ),
'simple_grid_field47' => array( 'field' => 'saldo_vigencia',
'type' => 'grid_field' ),
'simple_grid_field92' => array( 'type' => 'grid_field_label',
'field' => 'saldo_vigencia' ),
'simple_grid_field48' => array( 'field' => 'espostconflicto',
'type' => 'grid_field' ),
'simple_grid_field93' => array( 'type' => 'grid_field_label',
'field' => 'espostconflicto' ),
'simple_grid_field49' => array( 'field' => 'urlproceso',
'type' => 'grid_field' ),
'simple_grid_field94' => array( 'type' => 'grid_field_label',
'field' => 'urlproceso' ),
'simple_grid_field50' => array( 'field' => 'destino_gasto',
'type' => 'grid_field' ),
'simple_grid_field95' => array( 'type' => 'grid_field_label',
'field' => 'destino_gasto' ),
'simple_grid_field51' => array( 'field' => 'origen_de_los_recursos',
'type' => 'grid_field' ),
'simple_grid_field96' => array( 'type' => 'grid_field_label',
'field' => 'origen_de_los_recursos' ),
'simple_grid_field52' => array( 'field' => 'd_as_adicionados',
'type' => 'grid_field' ),
'simple_grid_field97' => array( 'type' => 'grid_field_label',
'field' => 'd_as_adicionados' ),
'simple_grid_field53' => array( 'field' => 'puntos_del_acuerdo',
'type' => 'grid_field' ),
'simple_grid_field98' => array( 'type' => 'grid_field_label',
'field' => 'puntos_del_acuerdo' ),
'simple_grid_field54' => array( 'field' => 'pilares_del_acuerdo',
'type' => 'grid_field' ),
'simple_grid_field99' => array( 'type' => 'grid_field_label',
'field' => 'pilares_del_acuerdo' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>