<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'sign_mailnot',
'sign_date',
'sign_hash',
'inf_consecutivo',
'inf_estado',
'inf_fecharep_i',
'inf_fecharep_f',
'inf_avgejecucion',
'inf_numerocontrato',
'inf_prenum',
'inf_anio',
'mun_ejec',
'inf_vigencia',
'inf_plazo',
'inf_rubroname',
'inf_rubrocode',
'inf_rp',
'inf_cdp',
'inf_fechacont_f',
'inf_fechacont_i',
'inf_objeto',
'inf_fechasuscripcion',
'id_cont_fk',
'inf_valorcontrato',
'inf_doccontratista',
'inf_nombrecontratista',
'inf_hash',
'inf_fechapresenta',
'inf_mail_a',
'inf_mail_b',
'url_secop',
'inf_actividades',
'inf_declarainconf',
'inf_declarainconf_obs',
'inf_incumplimiento',
'inf_incumplimiento_obs',
'cont_cesion',
'inf_intersup',
'inf_nombre',
'cont_modifica',
'inf_dependencia',
'inf_periodicidad',
'inf_cargo',
'sign_file',
'inf_usopresupuestal',
'cert_process',
'cert_modalidad',
'cert_mes' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'sign_mailnot' => array( 'integrated_edit_field38',
'edit_field_label',
'edit_field_tooltip' ),
'sign_date' => array( 'integrated_edit_field37' ),
'sign_hash' => array( 'integrated_edit_field36' ),
'inf_consecutivo' => array( 'integrated_edit_field1' ),
'inf_estado' => array( 'integrated_edit_field3' ),
'inf_fecharep_i' => array( 'integrated_edit_field6' ),
'inf_fecharep_f' => array( 'integrated_edit_field7' ),
'inf_avgejecucion' => array( 'integrated_edit_field29' ),
'inf_numerocontrato' => array( 'integrated_edit_field8' ),
'inf_prenum' => array( 'integrated_edit_field52' ),
'inf_anio' => array( 'integrated_edit_field51' ),
'mun_ejec' => array( 'integrated_edit_field35' ),
'inf_vigencia' => array( 'integrated_edit_field22' ),
'inf_plazo' => array( 'integrated_edit_field21' ),
'inf_rubroname' => array( 'integrated_edit_field16' ),
'inf_rubrocode' => array( 'integrated_edit_field15' ),
'inf_rp' => array( 'integrated_edit_field14' ),
'inf_cdp' => array( 'integrated_edit_field13' ),
'inf_fechacont_f' => array( 'integrated_edit_field20' ),
'inf_fechacont_i' => array( 'integrated_edit_field19' ),
'inf_objeto' => array( 'integrated_edit_field17' ),
'inf_fechasuscripcion' => array( 'integrated_edit_field18' ),
'id_cont_fk' => array( 'integrated_edit_field' ),
'inf_valorcontrato' => array( 'integrated_edit_field11' ),
'inf_doccontratista' => array( 'integrated_edit_field9' ),
'inf_nombrecontratista' => array( 'integrated_edit_field10' ),
'inf_hash' => array( 'integrated_edit_field2' ),
'inf_fechapresenta' => array( 'integrated_edit_field4' ),
'inf_mail_a' => array( 'integrated_edit_field53' ),
'inf_mail_b' => array( 'integrated_edit_field54' ),
'url_secop' => array( 'integrated_edit_field55' ),
'inf_actividades' => array( 'integrated_edit_field30' ),
'inf_declarainconf' => array( 'integrated_edit_field31' ),
'inf_declarainconf_obs' => array( 'integrated_edit_field32' ),
'inf_incumplimiento' => array( 'integrated_edit_field33' ),
'inf_incumplimiento_obs' => array( 'integrated_edit_field34' ),
'cont_cesion' => array( 'integrated_edit_field12' ),
'inf_intersup' => array( 'integrated_edit_field24' ),
'inf_nombre' => array( 'integrated_edit_field25' ),
'cont_modifica' => array( 'integrated_edit_field23' ),
'inf_dependencia' => array( 'integrated_edit_field27' ),
'inf_periodicidad' => array( 'integrated_edit_field5' ),
'inf_cargo' => array( 'integrated_edit_field26' ),
'sign_file' => array( 'integrated_edit_field39' ),
'inf_usopresupuestal' => array( 'integrated_edit_field28' ),
'cert_process' => array( 'integrated_edit_field40',
'edit_field_label1',
'edit_field_tooltip1' ),
'cert_modalidad' => array( 'integrated_edit_field41' ),
'cert_mes' => array( 'integrated_edit_field42' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'tabs' ),
'section' => array( 'integrated_edit_field1',
'integrated_edit_field3',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field29',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55' ),
'section3' => array( 'integrated_edit_field30',
'section',
'section1',
'integrated_edit_field12',
'integrated_edit_field23' ),
'section4' => array( 'integrated_edit_field31',
'integrated_edit_field32' ),
'section5' => array( 'integrated_edit_field33',
'integrated_edit_field34' ),
'section2' => array( 'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27' ),
'section1' => array( 'integrated_edit_field5',
'integrated_edit_field11',
'integrated_edit_field',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field39',
'integrated_edit_field35',
'integrated_edit_field51',
'integrated_edit_field52' ),
'section6' => array( 'integrated_edit_field36',
'integrated_edit_field37',
'text',
'edit_field_label',
'edit_field_tooltip',
'integrated_edit_field38' ),
'section7' => array( 'edit_field_label1',
'edit_field_tooltip1',
'integrated_edit_field40',
'integrated_edit_field42',
'integrated_edit_field28',
'integrated_edit_field41' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'tabs' => 'grid',
'integrated_edit_field1' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field6' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field29' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field53' => 'section',
'integrated_edit_field54' => 'section',
'integrated_edit_field55' => 'section',
'integrated_edit_field30' => 'section3',
'section' => 'section3',
'section1' => 'section3',
'integrated_edit_field12' => 'section3',
'integrated_edit_field23' => 'section3',
'integrated_edit_field31' => 'section4',
'integrated_edit_field32' => 'section4',
'integrated_edit_field33' => 'section5',
'integrated_edit_field34' => 'section5',
'integrated_edit_field24' => 'section2',
'integrated_edit_field25' => 'section2',
'integrated_edit_field26' => 'section2',
'integrated_edit_field27' => 'section2',
'integrated_edit_field5' => 'section1',
'integrated_edit_field11' => 'section1',
'integrated_edit_field' => 'section1',
'integrated_edit_field18' => 'section1',
'integrated_edit_field17' => 'section1',
'integrated_edit_field19' => 'section1',
'integrated_edit_field20' => 'section1',
'integrated_edit_field13' => 'section1',
'integrated_edit_field14' => 'section1',
'integrated_edit_field15' => 'section1',
'integrated_edit_field16' => 'section1',
'integrated_edit_field21' => 'section1',
'integrated_edit_field22' => 'section1',
'integrated_edit_field39' => 'section1',
'integrated_edit_field35' => 'section1',
'integrated_edit_field51' => 'section1',
'integrated_edit_field52' => 'section1',
'integrated_edit_field36' => 'section6',
'integrated_edit_field37' => 'section6',
'text' => 'section6',
'edit_field_label' => 'section6',
'edit_field_tooltip' => 'section6',
'integrated_edit_field38' => 'section6',
'edit_field_label1' => 'section7',
'edit_field_tooltip1' => 'section7',
'integrated_edit_field40' => 'section7',
'integrated_edit_field42' => 'section7',
'integrated_edit_field28' => 'section7',
'integrated_edit_field41' => 'section7' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field29' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c10' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c11' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c12' ),
'integrated_edit_field53' => array( 'location' => 'section',
'cellId' => 'c13' ),
'integrated_edit_field54' => array( 'location' => 'section',
'cellId' => 'c14' ),
'integrated_edit_field55' => array( 'location' => 'section',
'cellId' => 'c15' ),
'integrated_edit_field30' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'section' => array( 'location' => 'section3',
'cellId' => 'c' ),
'section1' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field12' => array( 'location' => 'section3',
'cellId' => 'c3' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c4' ),
'integrated_edit_field31' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field32' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field33' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field24' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field26' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'integrated_edit_field27' => array( 'location' => 'section2',
'cellId' => 'c5' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field18' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field17' => array( 'location' => 'section1',
'cellId' => 'c5' ),
'integrated_edit_field19' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field20' => array( 'location' => 'section1',
'cellId' => 'c7' ),
'integrated_edit_field13' => array( 'location' => 'section1',
'cellId' => 'c8' ),
'integrated_edit_field14' => array( 'location' => 'section1',
'cellId' => 'c9' ),
'integrated_edit_field15' => array( 'location' => 'section1',
'cellId' => 'c10' ),
'integrated_edit_field16' => array( 'location' => 'section1',
'cellId' => 'c11' ),
'integrated_edit_field21' => array( 'location' => 'section1',
'cellId' => 'c12' ),
'integrated_edit_field22' => array( 'location' => 'section1',
'cellId' => 'c13' ),
'integrated_edit_field39' => array( 'location' => 'section1',
'cellId' => 'c14' ),
'integrated_edit_field35' => array( 'location' => 'section1',
'cellId' => 'c16' ),
'integrated_edit_field51' => array( 'location' => 'section1',
'cellId' => 'c17' ),
'integrated_edit_field52' => array( 'location' => 'section1',
'cellId' => 'c18' ),
'integrated_edit_field36' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field37' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'text' => array( 'location' => 'section6',
'cellId' => 'c' ),
'edit_field_label' => array( 'location' => 'section6',
'cellId' => 'c2' ),
'edit_field_tooltip' => array( 'location' => 'section6',
'cellId' => 'c2' ),
'integrated_edit_field38' => array( 'location' => 'section6',
'cellId' => 'c2' ),
'edit_field_label1' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'edit_field_tooltip1' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field40' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field42' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field28' => array( 'location' => 'section7',
'cellId' => 'c2' ),
'integrated_edit_field41' => array( 'location' => 'section7',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'edit_view' => array( 'edit_view' ),
'edit_field' => array( 'integrated_edit_field38',
'integrated_edit_field40' ),
'integrated_edit_field' => array( 'integrated_edit_field37',
'integrated_edit_field36',
'integrated_edit_field1',
'integrated_edit_field3',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field29',
'integrated_edit_field8',
'integrated_edit_field52',
'integrated_edit_field51',
'integrated_edit_field35',
'integrated_edit_field22',
'integrated_edit_field21',
'integrated_edit_field16',
'integrated_edit_field15',
'integrated_edit_field14',
'integrated_edit_field13',
'integrated_edit_field20',
'integrated_edit_field19',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field',
'integrated_edit_field11',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field12',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field23',
'integrated_edit_field27',
'integrated_edit_field5',
'integrated_edit_field26',
'integrated_edit_field39',
'integrated_edit_field28',
'integrated_edit_field41',
'integrated_edit_field42' ),
'section' => array( 'section',
'section1' ),
'tabs' => array( 'tabs' ),
'text' => array( 'text' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1' ),
'edit_field_tooltip' => array( 'edit_field_tooltip',
'edit_field_tooltip1' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section' => array( 'cells' => array( 'c11' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field53' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field54' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 0,
1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field55' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 8 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section1' => array( 'cells' => array( 'c16' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field51' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field52' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 5 ),
'section6' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field36',
'integrated_edit_field37' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'edit_field_label',
'edit_field_tooltip',
'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 3 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_label1',
'edit_field_tooltip1',
'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'c6',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c4' => array( 'model' => 'c3',
'items' => array( 'tabs' ) ),
'c6' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c15',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field29' ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ),
'useFullWidth' => true ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field53' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field54' ) ),
'c15' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field55' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'useFullWidth' => true ),
'c' => array( 'model' => 'c1',
'items' => array( 'section' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'section1' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field31' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field32' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field33' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c17' ),
array( 'cell' => 'c18' ),
array( 'cell' => 'c19' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ),
array( 'cell' => 'c15' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39' ) ),
'c15' => array( 'model' => 'c1',
'items' => array(  ) ),
'c16' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35' ) ),
'c17' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field51' ) ),
'c18' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field52' ) ),
'c19' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field36',
'integrated_edit_field37' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'useFullWidth' => true ),
'c' => array( 'model' => 'c1',
'items' => array( 'text' ),
'useFullWidth' => true ),
'c2' => array( 'model' => 'c3',
'items' => array( 'edit_field_label',
'edit_field_tooltip',
'integrated_edit_field38' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c3',
'items' => array( 'edit_field_label1',
'edit_field_tooltip1',
'integrated_edit_field40' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'useFullWidth' => true ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field42' ),
'useFullWidth' => true ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ),
'useFullWidth' => true ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field41' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save',
'icon' => array( 'fa' => 'key' ),
'buttonStyle' => 'warning',
'buttonSize' => 'large',
'label' => array( 'type' => 0,
'text' => 'Solicitar clave dinámica' ) ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close',
'icon' => array( 'glyph' => 'remove' ),
'buttonStyle' => 'info',
'buttonSize' => 'large' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field38' => array( 'field' => 'sign_mailnot',
'type' => 'edit_field',
'orientation' => 0,
'label' => array( 'field' => 'sign_mailnot',
'table' => 'informe_intersup',
'type' => 3 ),
'tooltip' => array( 'field' => 'sign_mailnot',
'table' => null,
'type' => 4 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field37' => array( 'field' => 'sign_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'sign_hash',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field1' => array( 'field' => 'inf_consecutivo',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field3' => array( 'field' => 'inf_estado',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 'inf_fecharep_i',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'inf_fecharep_f',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'inf_avgejecucion',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field8' => array( 'field' => 'inf_numerocontrato',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field52' => array( 'field' => 'inf_prenum',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field51' => array( 'field' => 'inf_anio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'mun_ejec',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field22' => array( 'field' => 'inf_vigencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'inf_plazo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'inf_rubroname',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'inf_rubrocode',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'inf_rp',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'inf_cdp',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'inf_fechacont_f',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'inf_fechacont_i',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'inf_objeto',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'inf_fechasuscripcion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'id_cont_fk',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field11' => array( 'field' => 'inf_valorcontrato',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'inf_doccontratista',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'inf_nombrecontratista',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'inf_hash',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'inf_fechapresenta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field53' => array( 'field' => 'inf_mail_a',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field54' => array( 'field' => 'inf_mail_b',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field55' => array( 'field' => 'url_secop',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'inf_actividades',
'type' => 'integrated_edit_field',
'orientation' => 0,
'tooltip' => array( 'field' => 'inf_actividades',
'table' => null,
'type' => 4 ),
'placeholder' => array( 'field' => 'inf_actividades',
'table' => 'informe_intersup',
'type' => 5 ) ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => '¿Declara inconformidad en el cumplimiento del contrato para este periodo reportado?',
'type' => 0 ),
'location' => 'section4',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field31' => array( 'field' => 'inf_declarainconf',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'inf_declarainconf_obs',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'inf_declarainconf_obs',
'table' => 'informe_intersup',
'type' => 3 ),
'placeholder' => array( 'field' => 'inf_declarainconf_obs',
'table' => null,
'type' => 5 ) ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => '¿Declara incumplimiento en el desarrollo del contrato para este periodo reportado?',
'type' => 0 ),
'location' => 'section5',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field33' => array( 'field' => 'inf_incumplimiento',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'inf_incumplimiento_obs',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'inf_incumplimiento_obs',
'table' => 'informe_intersup',
'type' => 3 ),
'placeholder' => array( 'field' => 'inf_incumplimiento_obs',
'table' => null,
'type' => 5 ) ),
'integrated_edit_field12' => array( 'field' => 'cont_cesion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'inf_intersup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'inf_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Clave dinámica',
'type' => 0 ),
array( 'text' => 'Informe',
'type' => 0 ),
array( 'text' => 'CRS',
'type' => 0 ),
array( 'text' => 'Actividades',
'type' => 0 ),
array( 'text' => 'Supervisor',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section6',
'section',
'section7',
'section3',
'section2',
'section1' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field23' => array( 'field' => 'cont_modifica',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'inf_dependencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'inf_periodicidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'inf_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<div class="alert alert-warning" role="alert">
  A continuación se enviará a su correo la clave dinámica, con esta clave usted podrá firmar y validar el informe de supervisión.</div>',
'type' => 0 ) ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'sign_mailnot',
'separated' => true ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'sign_mailnot',
'separated' => true,
'tooltip' => array( 'field' => 'sign_mailnot',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field39' => array( 'field' => 'sign_file',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'inf_usopresupuestal',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field40' => array( 'field' => 'cert_process',
'type' => 'edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'cert_process',
'table' => 'informe_intersup',
'type' => 3 ),
'tooltip' => array( 'field' => 'cert_process',
'table' => null,
'type' => 4 ),
'joined' => false,
'separated' => true ),
'integrated_edit_field41' => array( 'field' => 'cert_modalidad',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'cert_modalidad',
'table' => 'informe_intersup',
'type' => 3 ) ),
'integrated_edit_field42' => array( 'field' => 'cert_mes',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'cert_mes',
'table' => null,
'type' => 3 ) ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'cert_process',
'separated' => true ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'cert_process',
'separated' => true,
'tooltip' => array( 'field' => 'cert_process',
'table' => null,
'type' => 4 ) ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>