<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id',
'nit_entidad',
'proceso_de_compra',
'id_contrato',
'referencia_del_contrato',
'estado_contrato',
'codigo_de_categoria_principal',
'descripcion_del_proceso',
'tipo_de_contrato',
'modalidad_de_contratacion',
'justificacion_modalidad_de',
'fecha_de_firma',
'fecha_de_inicio_del_contrato',
'fecha_de_fin_del_contrato',
'fecha_de_inicio_de_ejecucion',
'fecha_de_fin_de_ejecucion',
'condiciones_de_entrega',
'tipodocproveedor',
'documento_proveedor',
'proveedor_adjudicado',
'es_grupo',
'es_pyme',
'habilita_pago_adelantado',
'liquidaci_n',
'obligaci_n_ambiental',
'obligaciones_postconsumo',
'reversion',
'valor_del_contrato',
'valor_de_pago_adelantado',
'valor_facturado',
'valor_pendiente_de_pago',
'valor_pagado',
'valor_amortizado',
'valor_pendiente_de',
'valor_pendiente_de_ejecucion',
'estado_bpin',
'c_digo_bpin',
'anno_bpin',
'saldo_cdp',
'saldo_vigencia',
'espostconflicto',
'urlproceso',
'destino_gasto',
'origen_de_los_recursos',
'd_as_adicionados',
'puntos_del_acuerdo',
'pilares_del_acuerdo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'import_field' ),
'nit_entidad' => array( 'import_field2' ),
'proceso_de_compra' => array( 'import_field10' ),
'id_contrato' => array( 'import_field11' ),
'referencia_del_contrato' => array( 'import_field12' ),
'estado_contrato' => array( 'import_field13' ),
'codigo_de_categoria_principal' => array( 'import_field14' ),
'descripcion_del_proceso' => array( 'import_field15' ),
'tipo_de_contrato' => array( 'import_field16' ),
'modalidad_de_contratacion' => array( 'import_field17' ),
'justificacion_modalidad_de' => array( 'import_field18' ),
'fecha_de_firma' => array( 'import_field19' ),
'fecha_de_inicio_del_contrato' => array( 'import_field20' ),
'fecha_de_fin_del_contrato' => array( 'import_field21' ),
'fecha_de_inicio_de_ejecucion' => array( 'import_field22' ),
'fecha_de_fin_de_ejecucion' => array( 'import_field23' ),
'condiciones_de_entrega' => array( 'import_field24' ),
'tipodocproveedor' => array( 'import_field25' ),
'documento_proveedor' => array( 'import_field26' ),
'proveedor_adjudicado' => array( 'import_field27' ),
'es_grupo' => array( 'import_field28' ),
'es_pyme' => array( 'import_field29' ),
'habilita_pago_adelantado' => array( 'import_field30' ),
'liquidaci_n' => array( 'import_field31' ),
'obligaci_n_ambiental' => array( 'import_field32' ),
'obligaciones_postconsumo' => array( 'import_field33' ),
'reversion' => array( 'import_field34' ),
'valor_del_contrato' => array( 'import_field35' ),
'valor_de_pago_adelantado' => array( 'import_field36' ),
'valor_facturado' => array( 'import_field37' ),
'valor_pendiente_de_pago' => array( 'import_field38' ),
'valor_pagado' => array( 'import_field39' ),
'valor_amortizado' => array( 'import_field40' ),
'valor_pendiente_de' => array( 'import_field41' ),
'valor_pendiente_de_ejecucion' => array( 'import_field42' ),
'estado_bpin' => array( 'import_field43' ),
'c_digo_bpin' => array( 'import_field44' ),
'anno_bpin' => array( 'import_field45' ),
'saldo_cdp' => array( 'import_field46' ),
'saldo_vigencia' => array( 'import_field47' ),
'espostconflicto' => array( 'import_field48' ),
'urlproceso' => array( 'import_field49' ),
'destino_gasto' => array( 'import_field50' ),
'origen_de_los_recursos' => array( 'import_field51' ),
'd_as_adicionados' => array( 'import_field52' ),
'puntos_del_acuerdo' => array( 'import_field53' ),
'pilares_del_acuerdo' => array( 'import_field54' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field2',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field2' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field51' => 'grid',
'import_field52' => 'grid',
'import_field53' => 'grid',
'import_field54' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field2',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field2',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'nit_entidad',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'proceso_de_compra',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'id_contrato',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'referencia_del_contrato',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'estado_contrato',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'codigo_de_categoria_principal',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'descripcion_del_proceso',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'tipo_de_contrato',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'modalidad_de_contratacion',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'justificacion_modalidad_de',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'fecha_de_firma',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'fecha_de_inicio_del_contrato',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'fecha_de_fin_del_contrato',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'fecha_de_inicio_de_ejecucion',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'fecha_de_fin_de_ejecucion',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'condiciones_de_entrega',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'tipodocproveedor',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'documento_proveedor',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'proveedor_adjudicado',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'es_grupo',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'es_pyme',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'habilita_pago_adelantado',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'liquidaci_n',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'obligaci_n_ambiental',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'obligaciones_postconsumo',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'reversion',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'valor_del_contrato',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'valor_de_pago_adelantado',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'valor_facturado',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'valor_pendiente_de_pago',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'valor_pagado',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'valor_amortizado',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'valor_pendiente_de',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'valor_pendiente_de_ejecucion',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'estado_bpin',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'c_digo_bpin',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'anno_bpin',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'saldo_cdp',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'saldo_vigencia',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'espostconflicto',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'urlproceso',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'destino_gasto',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'origen_de_los_recursos',
'type' => 'import_field' ),
'import_field52' => array( 'field' => 'd_as_adicionados',
'type' => 'import_field' ),
'import_field53' => array( 'field' => 'puntos_del_acuerdo',
'type' => 'import_field' ),
'import_field54' => array( 'field' => 'pilares_del_acuerdo',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>