<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'reorderRows' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => true,
'showHideFields' => true,
'reorderFields' => true,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => true,
'searchSaving' => false ),
'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'CONTRATOID' => array( 'totalsType' => '' ),
'VIGENCIA' => array( 'totalsType' => '' ),
'LOGINLEVEL' => array( 'totalsType' => '' ),
'NUMC' => array( 'totalsType' => '' ),
'cont_unspsc' => array( 'totalsType' => '' ),
'cont_munejec' => array( 'totalsType' => '' ),
'estado_nombre' => array( 'totalsType' => '' ),
'contractor_type' => array( 'totalsType' => '' ),
'DOCID' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'contractor_email_mincit' => array( 'totalsType' => '' ),
'contractor_phone' => array( 'totalsType' => '' ),
'contractor_mobile' => array( 'totalsType' => '' ),
'CODC' => array( 'totalsType' => '' ),
'cont_tipo' => array( 'totalsType' => '' ),
'nombre' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_fase' => array( 'totalsType' => '' ),
'FECHAI' => array( 'totalsType' => '' ),
'FECHAF' => array( 'totalsType' => '' ),
'QTYDIAS' => array( 'totalsType' => '' ),
'QTYMESES' => array( 'totalsType' => '' ),
'VALORI' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'CDP' => array( 'totalsType' => '' ),
'RP' => array( 'totalsType' => '' ),
'cont_tipoproceso' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'periodo_name' => array( 'totalsType' => '' ),
'periodo_value' => array( 'totalsType' => '' ),
'periodo_dias' => array( 'totalsType' => '' ),
'cont_informessug' => array( 'totalsType' => '' ),
'periodo_meses' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_fechavigencia' => array( 'totalsType' => '' ),
'VALORINICIAL' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'iva_regimen' => array( 'totalsType' => '' ),
'cont_iva' => array( 'totalsType' => '' ),
'cont_valormensual_base' => array( 'totalsType' => '' ),
'cont_valormensual_iva' => array( 'totalsType' => '' ),
'CONTVINCULADO' => array( 'totalsType' => '' ),
'cont_paa_id' => array( 'totalsType' => '' ),
'cont_tipoc' => array( 'totalsType' => '' ),
'ct_tipo_nombre' => array( 'totalsType' => '' ),
'cont_modalidad' => array( 'totalsType' => '' ),
'des_mod_proceso' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'ctb_tipo_nombre' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'cont_dep' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'CONTRATOID',
'VIGENCIA',
'cont_unspsc',
'CODC',
'cont_paa_id',
'VALORI',
'FECHAI',
'FECHAF',
'NUMC',
'ct_tipo_nombre',
'VALORINICIAL',
'des_mod_proceso',
'cont_munejec',
'QTYDIAS',
'QTYMESES',
'ctb_tipo_nombre',
'DOCID',
'CDP',
'cont_secop_enlace',
'contractor_nombresfull',
'RP',
'contractor_email',
'cont_iva',
'contractor_email_mincit',
'estado_nombre',
'cont_valormensual_base',
'contractor_phone',
'cont_valormensual_iva',
'contractor_mobile' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'id_cont',
'cont_munejec',
'cont_unspsc',
'cont_valormensual_iva',
'cont_valormensual_base',
'cont_iva',
'cont_secop_enlace',
'ctb_tipo_nombre',
'cont_causalc',
'des_mod_proceso',
'cont_modalidad',
'ct_tipo_nombre',
'cont_tipoc',
'cont_paa_id',
'CONTVINCULADO',
'iva_regimen',
'cont_valormensual',
'VALORINICIAL',
'cont_fechavigencia',
'cont_objeto',
'periodo_meses',
'cont_informessug',
'periodo_dias',
'periodo_value',
'periodo_name',
'cont_periodicidad',
'cont_tipoproceso',
'RP',
'CDP',
'cont_fechaapertura',
'VALORI',
'QTYMESES',
'QTYDIAS',
'FECHAF',
'FECHAI',
'cont_fase',
'cont_catalogo_presupuestal',
'cont_tipopre',
'cont_codrubro',
'nombre',
'cont_tipo',
'NUMC',
'CODC',
'contractor_mobile',
'contractor_phone',
'contractor_email_mincit',
'contractor_email',
'contractor_nombresfull',
'DOCID',
'contractor_type',
'estado_nombre',
'VIGENCIA',
'LOGINLEVEL',
'CONTRATOID' ),
'filterFields' => array( 'VIGENCIA' ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'CONTRATOID' => array( 'simple_grid_field1',
'simple_grid_field2' ),
'VIGENCIA' => array( 'simple_grid_field3',
'simple_grid_field5' ),
'cont_unspsc' => array( 'grid_field',
'grid_field2' ),
'CODC' => array( 'simple_grid_field18',
'simple_grid_field21' ),
'cont_paa_id' => array( 'simple_grid_field4',
'simple_grid_field6' ),
'VALORI' => array( 'simple_grid_field32',
'simple_grid_field33' ),
'FECHAI' => array( 'simple_grid_field26',
'simple_grid_field27' ),
'FECHAF' => array( 'simple_grid_field28',
'simple_grid_field29' ),
'NUMC' => array( 'simple_grid_field19',
'simple_grid_field25' ),
'ct_tipo_nombre' => array( 'simple_grid_field7',
'simple_grid_field8' ),
'VALORINICIAL' => array( 'simple_grid_field47',
'simple_grid_field48' ),
'des_mod_proceso' => array( 'simple_grid_field9',
'simple_grid_field11' ),
'cont_munejec' => array( 'grid_field1',
'grid_field3' ),
'QTYDIAS' => array( 'simple_grid_field30',
'simple_grid_field36' ),
'QTYMESES' => array( 'simple_grid_field31',
'simple_grid_field37' ),
'ctb_tipo_nombre' => array( 'simple_grid_field12',
'simple_grid_field38' ),
'DOCID' => array( 'simple_grid_field10',
'simple_grid_field39' ),
'CDP' => array( 'simple_grid_field34',
'simple_grid_field40' ),
'cont_secop_enlace' => array( 'simple_grid_field20',
'simple_grid_field41' ),
'contractor_nombresfull' => array( 'simple_grid_field13',
'simple_grid_field42' ),
'RP' => array( 'simple_grid_field35',
'simple_grid_field43' ),
'contractor_email' => array( 'simple_grid_field14',
'simple_grid_field44' ),
'cont_iva' => array( 'simple_grid_field22',
'simple_grid_field45' ),
'contractor_email_mincit' => array( 'simple_grid_field15',
'simple_grid_field46' ),
'estado_nombre' => array( 'simple_grid_field',
'simple_grid_field49' ),
'cont_valormensual_base' => array( 'simple_grid_field23',
'simple_grid_field50' ),
'contractor_phone' => array( 'simple_grid_field16',
'simple_grid_field51' ),
'cont_valormensual_iva' => array( 'simple_grid_field24',
'simple_grid_field52' ),
'contractor_mobile' => array( 'simple_grid_field17',
'simple_grid_field53' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'filter_panel',
'details_found',
'page_size',
'columns_control',
'sort_dropdown' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'master_info' ),
'grid' => array( 'simple_grid_field2',
'simple_grid_field1',
'simple_grid_field5',
'simple_grid_field3',
'grid_field2',
'grid_field',
'simple_grid_field21',
'simple_grid_field18',
'simple_grid_field6',
'simple_grid_field4',
'simple_grid_field33',
'simple_grid_field32',
'simple_grid_field27',
'simple_grid_field26',
'simple_grid_field29',
'simple_grid_field28',
'simple_grid_field25',
'simple_grid_field19',
'simple_grid_field8',
'simple_grid_field7',
'simple_grid_field48',
'simple_grid_field47',
'simple_grid_field11',
'simple_grid_field9',
'grid_field3',
'grid_field1',
'simple_grid_field36',
'simple_grid_field30',
'simple_grid_field37',
'simple_grid_field31',
'simple_grid_field38',
'simple_grid_field12',
'simple_grid_field39',
'simple_grid_field10',
'simple_grid_field40',
'simple_grid_field34',
'simple_grid_field41',
'simple_grid_field20',
'simple_grid_field42',
'simple_grid_field13',
'simple_grid_field43',
'simple_grid_field35',
'simple_grid_field44',
'simple_grid_field14',
'simple_grid_field45',
'simple_grid_field22',
'simple_grid_field46',
'simple_grid_field15',
'simple_grid_field49',
'simple_grid_field',
'simple_grid_field50',
'simple_grid_field23',
'simple_grid_field51',
'simple_grid_field16',
'simple_grid_field52',
'simple_grid_field24',
'simple_grid_field53',
'simple_grid_field17' ) ),
'formXtTags' => array( 'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search_field' => 'supertop',
'simple_search_option' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'filter_panel' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'columns_control' => 'above-grid',
'sort_dropdown' => 'above-grid',
'pagination' => 'below-grid',
'master_info' => 'top',
'simple_grid_field2' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field3' => 'grid',
'grid_field2' => 'grid',
'grid_field' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field9' => 'grid',
'grid_field3' => 'grid',
'grid_field1' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field17' => 'grid' ),
'itemLocations' => array( 'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'search_panel_field' => array( 'search_panel_field30',
'search_panel_field28',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field10',
'search_panel_field9',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1',
'search_panel_field',
'search_panel_field56',
'search_panel_field55',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field58',
'search_panel_field59',
'search_panel_field60' ),
'-' => array( '-2',
'-',
'-1',
'-3' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'columns_control' => array( 'columns_control' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'search_panel' => array( 'search_panel' ),
'simple_search_option' => array( 'simple_search_option' ),
'simple_search_field' => array( 'simple_search_field' ),
'sort_dropdown' => array( 'sort_dropdown' ),
'logo' => array( 'logo1' ),
'advsearch_link' => array( 'advsearch_link' ),
'export' => array( 'export' ),
'userinfo_link' => array( 'userinfo_link' ),
'master_info' => array( 'master_info' ),
'filter_panel' => array( 'filter_panel' ),
'filter_panel_field' => array( 'filter_panel_field' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field3',
'grid_field',
'simple_grid_field18',
'simple_grid_field4',
'simple_grid_field32',
'simple_grid_field26',
'simple_grid_field28',
'simple_grid_field19',
'simple_grid_field7',
'simple_grid_field47',
'simple_grid_field9',
'grid_field1',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field12',
'simple_grid_field10',
'simple_grid_field34',
'simple_grid_field20',
'simple_grid_field13',
'simple_grid_field35',
'simple_grid_field14',
'simple_grid_field22',
'simple_grid_field15',
'simple_grid_field',
'simple_grid_field23',
'simple_grid_field16',
'simple_grid_field24',
'simple_grid_field17' ),
'grid_field_label' => array( 'simple_grid_field2',
'simple_grid_field5',
'grid_field2',
'simple_grid_field21',
'simple_grid_field6',
'simple_grid_field33',
'simple_grid_field27',
'simple_grid_field29',
'simple_grid_field25',
'simple_grid_field8',
'simple_grid_field48',
'simple_grid_field11',
'grid_field3',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'CONTRATOID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'VIGENCIA_fieldheadercolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'cont_unspsc_fieldheadercolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'CODC_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'cont_paa_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'VALORI_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'FECHAI_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'FECHAF_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'NUMC_fieldheadercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'ct_tipo_nombre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'VALORINICIAL_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'des_mod_proceso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'cont_munejec_fieldheadercolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'QTYDIAS_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'QTYMESES_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'ctb_tipo_nombre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'DOCID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'CDP_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'cont_secop_enlace_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_nombresfull_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'RP_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_email_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'cont_iva_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_email_mincit_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'estado_nombre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'cont_valormensual_base_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_phone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'cont_valormensual_iva_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_mobile_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'CONTRATOID_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'VIGENCIA_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'cont_unspsc_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'CODC_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'cont_paa_id_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'VALORI_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'FECHAI_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'FECHAF_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'NUMC_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'ct_tipo_nombre_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'VALORINICIAL_fieldcolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'des_mod_proceso_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'cont_munejec_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'QTYDIAS_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'QTYMESES_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'ctb_tipo_nombre_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'DOCID_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'CDP_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'cont_secop_enlace_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_nombresfull_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'RP_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_email_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'cont_iva_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_email_mincit_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'estado_nombre_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'cont_valormensual_base_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_phone_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'cont_valormensual_iva_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_mobile_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 29,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'columns_control' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c4',
'items' => array( 'sort_dropdown' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'CONTRATOID',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'CONTRATOID',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'VIGENCIA',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'VIGENCIA',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field2' ),
'field' => 'cont_unspsc',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'cont_unspsc',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'CODC',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'CODC',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'cont_paa_id',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'cont_paa_id',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'VALORI',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'VALORI',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'FECHAI',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'FECHAI',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'FECHAF',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'FECHAF',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'NUMC',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'NUMC',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'ct_tipo_nombre',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'ct_tipo_nombre',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'VALORINICIAL',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'VALORINICIAL',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'des_mod_proceso',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'des_mod_proceso',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field3' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'QTYDIAS',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'QTYDIAS',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'QTYMESES',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'QTYMESES',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'ctb_tipo_nombre',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'ctb_tipo_nombre',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'DOCID',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'DOCID',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'CDP',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'CDP',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'RP',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'RP',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'contractor_email',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'contractor_email',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'cont_iva',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'cont_iva',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'contractor_email_mincit',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'contractor_email_mincit',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'estado_nombre',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'estado_nombre',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'cont_valormensual_base',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'cont_valormensual_base',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'contractor_phone',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'contractor_phone',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'cont_valormensual_iva',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'cont_valormensual_iva',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'contractor_mobile',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'contractor_mobile',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-3',
'export' ) ),
'search_panel_field30' => array( 'field' => 'QTYDIAS',
'type' => 'search_panel_field' ),
'search_panel_field28' => array( 'field' => 'FECHAF',
'type' => 'search_panel_field' ),
'search_panel_field26' => array( 'field' => 'FECHAI',
'type' => 'search_panel_field' ),
'search_panel_field25' => array( 'field' => 'cont_fase',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field24' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'search_panel_field' ),
'search_panel_field23' => array( 'field' => 'cont_tipopre',
'type' => 'search_panel_field' ),
'search_panel_field22' => array( 'field' => 'cont_codrubro',
'type' => 'search_panel_field' ),
'search_panel_field21' => array( 'field' => 'nombre',
'type' => 'search_panel_field' ),
'search_panel_field20' => array( 'field' => 'cont_tipo',
'type' => 'search_panel_field' ),
'search_panel_field19' => array( 'field' => 'NUMC',
'type' => 'search_panel_field' ),
'search_panel_field18' => array( 'field' => 'CODC',
'type' => 'search_panel_field' ),
'search_panel_field17' => array( 'field' => 'contractor_mobile',
'type' => 'search_panel_field' ),
'search_panel_field16' => array( 'field' => 'contractor_phone',
'type' => 'search_panel_field' ),
'search_panel_field15' => array( 'field' => 'contractor_email_mincit',
'type' => 'search_panel_field' ),
'search_panel_field14' => array( 'field' => 'contractor_email',
'type' => 'search_panel_field' ),
'search_panel_field13' => array( 'field' => 'contractor_nombresfull',
'type' => 'search_panel_field' ),
'search_panel_field10' => array( 'field' => 'DOCID',
'type' => 'search_panel_field' ),
'search_panel_field9' => array( 'field' => 'contractor_type',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'estado_nombre',
'type' => 'search_panel_field' ),
'search_panel_field5' => array( 'field' => 'cont_munejec',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field4' => array( 'field' => 'cont_unspsc',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field3' => array( 'field' => 'VIGENCIA',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field2' => array( 'field' => 'LOGINLEVEL',
'type' => 'search_panel_field' ),
'search_panel_field1' => array( 'field' => 'CONTRATOID',
'type' => 'search_panel_field' ),
'search_panel_field' => array( 'field' => 'id_cont',
'type' => 'search_panel_field' ),
'-2' => array( 'type' => '-' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'search_panel_field56' => array( 'field' => 'cont_secop_enlace',
'type' => 'search_panel_field' ),
'search_panel_field55' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'search_panel_field' ),
'search_panel_field54' => array( 'field' => 'cont_causalc',
'type' => 'search_panel_field' ),
'search_panel_field53' => array( 'field' => 'des_mod_proceso',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field52' => array( 'field' => 'cont_modalidad',
'type' => 'search_panel_field' ),
'search_panel_field51' => array( 'field' => 'ct_tipo_nombre',
'type' => 'search_panel_field' ),
'search_panel_field50' => array( 'field' => 'cont_tipoc',
'type' => 'search_panel_field' ),
'search_panel_field49' => array( 'field' => 'cont_paa_id',
'type' => 'search_panel_field' ),
'search_panel_field48' => array( 'field' => 'CONTVINCULADO',
'type' => 'search_panel_field' ),
'search_panel_field47' => array( 'field' => 'iva_regimen',
'type' => 'search_panel_field' ),
'search_panel_field46' => array( 'field' => 'cont_valormensual',
'type' => 'search_panel_field' ),
'search_panel_field45' => array( 'field' => 'VALORINICIAL',
'type' => 'search_panel_field' ),
'search_panel_field44' => array( 'field' => 'cont_fechavigencia',
'type' => 'search_panel_field' ),
'search_panel_field43' => array( 'field' => 'cont_objeto',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field42' => array( 'field' => 'periodo_meses',
'type' => 'search_panel_field' ),
'search_panel_field41' => array( 'field' => 'cont_informessug',
'type' => 'search_panel_field' ),
'search_panel_field40' => array( 'field' => 'periodo_dias',
'type' => 'search_panel_field' ),
'search_panel_field39' => array( 'field' => 'periodo_value',
'type' => 'search_panel_field' ),
'search_panel_field38' => array( 'field' => 'periodo_name',
'type' => 'search_panel_field' ),
'search_panel_field37' => array( 'field' => 'cont_periodicidad',
'type' => 'search_panel_field' ),
'search_panel_field36' => array( 'field' => 'cont_tipoproceso',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field35' => array( 'field' => 'RP',
'type' => 'search_panel_field' ),
'search_panel_field34' => array( 'field' => 'CDP',
'type' => 'search_panel_field' ),
'search_panel_field33' => array( 'field' => 'cont_fechaapertura',
'type' => 'search_panel_field' ),
'search_panel_field32' => array( 'field' => 'VALORI',
'type' => 'search_panel_field' ),
'search_panel_field31' => array( 'field' => 'QTYMESES',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'columns_control' => array( 'type' => 'columns_control',
'showHide' => true,
'reorder' => true ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field5',
'search_panel_field4',
'search_panel_field60',
'search_panel_field59',
'search_panel_field58',
'search_panel_field56',
'search_panel_field55',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field28',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field10',
'search_panel_field9',
'search_panel_field6',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'simple_search_option' => array( 'type' => 'simple_search_option' ),
'simple_search_field' => array( 'type' => 'simple_search_field' ),
'sort_dropdown' => array( 'type' => 'sort_dropdown' ),
'logo1' => array( 'type' => 'logo' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'export' => array( 'type' => 'export' ),
'-3' => array( 'type' => '-' ),
'search_panel_field58' => array( 'field' => 'cont_iva',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field59' => array( 'field' => 'cont_valormensual_base',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field60' => array( 'field' => 'cont_valormensual_iva',
'type' => 'search_panel_field',
'required' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'informe_intersup_adm' => 'true' ) ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field' ) ),
'filter_panel_field' => array( 'field' => 'VIGENCIA',
'type' => 'filter_panel_field' ),
'simple_grid_field1' => array( 'field' => 'CONTRATOID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field2' => array( 'type' => 'grid_field_label',
'field' => 'CONTRATOID',
'clickSort' => true ),
'simple_grid_field3' => array( 'field' => 'VIGENCIA',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field5' => array( 'type' => 'grid_field_label',
'field' => 'VIGENCIA',
'clickSort' => true ),
'grid_field' => array( 'field' => 'cont_unspsc',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field2' => array( 'type' => 'grid_field_label',
'field' => 'cont_unspsc' ),
'simple_grid_field18' => array( 'field' => 'CODC',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'CODC',
'clickSort' => true ),
'simple_grid_field4' => array( 'field' => 'cont_paa_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'cont_paa_id' ),
'simple_grid_field32' => array( 'field' => 'VALORI',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'VALORI',
'clickSort' => true ),
'simple_grid_field26' => array( 'field' => 'FECHAI',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'FECHAI',
'clickSort' => true ),
'simple_grid_field28' => array( 'field' => 'FECHAF',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'FECHAF',
'clickSort' => true ),
'simple_grid_field19' => array( 'field' => 'NUMC',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field25' => array( 'type' => 'grid_field_label',
'field' => 'NUMC',
'clickSort' => true ),
'simple_grid_field7' => array( 'field' => 'ct_tipo_nombre',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'ct_tipo_nombre' ),
'simple_grid_field47' => array( 'field' => 'VALORINICIAL',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'VALORINICIAL',
'clickSort' => true ),
'simple_grid_field9' => array( 'field' => 'des_mod_proceso',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'des_mod_proceso' ),
'grid_field1' => array( 'field' => 'cont_munejec',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field3' => array( 'type' => 'grid_field_label',
'field' => 'cont_munejec' ),
'simple_grid_field30' => array( 'field' => 'QTYDIAS',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'QTYDIAS',
'clickSort' => true ),
'simple_grid_field31' => array( 'field' => 'QTYMESES',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'QTYMESES',
'clickSort' => true ),
'simple_grid_field12' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'ctb_tipo_nombre' ),
'simple_grid_field10' => array( 'field' => 'DOCID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'DOCID',
'clickSort' => true ),
'simple_grid_field34' => array( 'field' => 'CDP',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'CDP',
'clickSort' => true ),
'simple_grid_field20' => array( 'field' => 'cont_secop_enlace',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_enlace' ),
'simple_grid_field13' => array( 'field' => 'contractor_nombresfull',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'contractor_nombresfull',
'clickSort' => true ),
'simple_grid_field35' => array( 'field' => 'RP',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'RP',
'clickSort' => true ),
'simple_grid_field14' => array( 'field' => 'contractor_email',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'contractor_email',
'clickSort' => true ),
'simple_grid_field22' => array( 'field' => 'cont_iva',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'cont_iva' ),
'simple_grid_field15' => array( 'field' => 'contractor_email_mincit',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'contractor_email_mincit',
'clickSort' => true ),
'simple_grid_field' => array( 'field' => 'estado_nombre',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'estado_nombre' ),
'simple_grid_field23' => array( 'field' => 'cont_valormensual_base',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual_base' ),
'simple_grid_field16' => array( 'field' => 'contractor_phone',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'contractor_phone',
'clickSort' => true ),
'simple_grid_field24' => array( 'field' => 'cont_valormensual_iva',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual_iva' ),
'simple_grid_field17' => array( 'field' => 'contractor_mobile',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'contractor_mobile',
'clickSort' => true ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 14,
'reorderRows' => false,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>