<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => true,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'master' => array( 'contrato_chart_estado' => array( 'preview' => true ),
'contrato_chart_tipocont' => array( 'preview' => true ),
'contrato_chart_dependencia' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'CONTRATOID' => array( 'totalsType' => '' ),
'CONTVINCULADO' => array( 'totalsType' => '' ),
'cont_paa_id' => array( 'totalsType' => '' ),
'VIGENCIA' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'estado_nombre' => array( 'totalsType' => '' ),
'contractor_type' => array( 'totalsType' => '' ),
'DOCID' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'CODC' => array( 'totalsType' => '' ),
'NUMC' => array( 'totalsType' => '' ),
'cont_tipo' => array( 'totalsType' => '' ),
'nombre' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_fase' => array( 'totalsType' => '' ),
'FECHAI' => array( 'totalsType' => '' ),
'FECHAF' => array( 'totalsType' => '' ),
'VALORI' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'CDP' => array( 'totalsType' => '' ),
'RP' => array( 'totalsType' => '' ),
'cont_tipoproceso' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'periodo_name' => array( 'totalsType' => '' ),
'periodo_value' => array( 'totalsType' => '' ),
'periodo_dias' => array( 'totalsType' => '' ),
'cont_informessug' => array( 'totalsType' => '' ),
'periodo_meses' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_fechavigencia' => array( 'totalsType' => '' ),
'VALORINICIAL' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'iva_regimen' => array( 'totalsType' => '' ),
'cont_tipoc' => array( 'totalsType' => '' ),
'ct_tipo_nombre' => array( 'totalsType' => '' ),
'cont_modalidad' => array( 'totalsType' => '' ),
'des_mod_proceso' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'ctb_tipo_nombre' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'cont_dep' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'CONTRATOID',
'VIGENCIA',
'DOCID',
'contractor_nombresfull',
'FECHAI',
'FECHAF',
'VALORI',
'ctb_tipo_nombre',
'cont_secop_enlace' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'ctb_tipo_nombre',
'cont_dep',
'cont_causalc',
'des_mod_proceso',
'cont_modalidad',
'ct_tipo_nombre',
'cont_tipoc',
'iva_regimen',
'cont_valormensual',
'VALORINICIAL',
'cont_fechavigencia',
'cont_objeto',
'periodo_meses',
'cont_informessug',
'periodo_dias',
'periodo_value',
'periodo_name',
'cont_periodicidad',
'cont_tipoproceso',
'RP',
'CDP',
'cont_fechaapertura',
'VALORI',
'FECHAF',
'FECHAI',
'cont_fase',
'cont_catalogo_presupuestal',
'cont_tipopre',
'cont_codrubro',
'nombre',
'cont_tipo',
'NUMC',
'CODC',
'contractor_email',
'contractor_nombresfull',
'DOCID',
'contractor_type',
'estado_nombre',
'cont_estado',
'VIGENCIA',
'cont_paa_id',
'CONTVINCULADO',
'CONTRATOID',
'id_cont',
'cont_secop_enlace' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'CONTRATOID' => array( 'simple_grid_field1',
'simple_grid_field2' ),
'VIGENCIA' => array( 'simple_grid_field3',
'simple_grid_field4' ),
'DOCID' => array( 'simple_grid_field10',
'simple_grid_field11' ),
'contractor_nombresfull' => array( 'simple_grid_field13',
'simple_grid_field14' ),
'FECHAI' => array( 'simple_grid_field26',
'simple_grid_field27' ),
'FECHAF' => array( 'simple_grid_field28',
'simple_grid_field29' ),
'VALORI' => array( 'simple_grid_field32',
'simple_grid_field33' ),
'ctb_tipo_nombre' => array( 'simple_grid_field5',
'simple_grid_field6' ),
'cont_secop_enlace' => array( 'simple_grid_field',
'simple_grid_field7' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'inline_add',
'details_found',
'page_size' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'master_info' ),
'grid' => array( 'simple_grid_field2',
'simple_grid_field1',
'simple_grid_field4',
'simple_grid_field3',
'simple_grid_field11',
'simple_grid_field10',
'simple_grid_field14',
'simple_grid_field13',
'simple_grid_field27',
'simple_grid_field26',
'simple_grid_field29',
'simple_grid_field28',
'simple_grid_field33',
'simple_grid_field32',
'simple_grid_field6',
'simple_grid_field5',
'simple_grid_field7',
'simple_grid_field',
'grid_inline_cancel',
'grid_view' ) ),
'formXtTags' => array( 'above-grid' => array( 'inlineadd_link',
'details_found',
'recsPerPage' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'inline_add' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'below-grid',
'master_info' => 'top',
'simple_grid_field2' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_view' => 'grid' ),
'itemLocations' => array( 'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'search_panel_field' => array( 'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field8',
'search_panel_field7',
'search_panel_field3',
'search_panel_field1',
'search_panel_field6',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field',
'search_panel_field27',
'search_panel_field5',
'search_panel_field38',
'search_panel_field37',
'search_panel_field2',
'search_panel_field36',
'search_panel_field35',
'search_panel_field4',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field44' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'master_info' => array( 'master_info' ),
'search_panel' => array( 'search_panel' ),
'-' => array( '-2',
'-',
'-1',
'-3' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'logo' => array( 'logo1' ),
'advsearch_link' => array( 'advsearch_link' ),
'export' => array( 'export' ),
'userinfo_link' => array( 'userinfo_link' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field3',
'simple_grid_field10',
'simple_grid_field13',
'simple_grid_field26',
'simple_grid_field28',
'simple_grid_field32',
'simple_grid_field5',
'simple_grid_field' ),
'grid_field_label' => array( 'simple_grid_field2',
'simple_grid_field4',
'simple_grid_field11',
'simple_grid_field14',
'simple_grid_field27',
'simple_grid_field29',
'simple_grid_field33',
'simple_grid_field6',
'simple_grid_field7' ),
'grid_view' => array( 'grid_view' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'CONTRATOID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'VIGENCIA_fieldheadercolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'DOCID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_nombresfull_fieldheadercolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'FECHAI_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'FECHAF_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'VALORI_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'ctb_tipo_nombre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'cont_secop_enlace_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inline_cancel',
'view_column' ),
'items' => array( 'grid_inline_cancel',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'CONTRATOID_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'VIGENCIA_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'DOCID_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_nombresfull_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'FECHAI_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'FECHAF_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'VALORI_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'ctb_tipo_nombre_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'cont_secop_enlace_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 10,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'CONTRATOID',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'CONTRATOID',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'VIGENCIA',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'VIGENCIA',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'DOCID',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'DOCID',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'FECHAI',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'FECHAI',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'FECHAF',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'FECHAF',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'VALORI',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'VALORI',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'ctb_tipo_nombre',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'ctb_tipo_nombre',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_cancel',
'grid_view' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-3',
'export' ) ),
'search_panel_field26' => array( 'field' => 'RP',
'type' => 'search_panel_field' ),
'search_panel_field25' => array( 'field' => 'CDP',
'type' => 'search_panel_field' ),
'search_panel_field24' => array( 'field' => 'cont_fechaapertura',
'type' => 'search_panel_field' ),
'search_panel_field23' => array( 'field' => 'VALORI',
'type' => 'search_panel_field' ),
'search_panel_field22' => array( 'field' => 'FECHAF',
'type' => 'search_panel_field' ),
'search_panel_field21' => array( 'field' => 'FECHAI',
'type' => 'search_panel_field' ),
'search_panel_field20' => array( 'field' => 'cont_fase',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field19' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'search_panel_field' ),
'search_panel_field18' => array( 'field' => 'cont_tipopre',
'type' => 'search_panel_field' ),
'search_panel_field17' => array( 'field' => 'cont_codrubro',
'type' => 'search_panel_field' ),
'search_panel_field16' => array( 'field' => 'nombre',
'type' => 'search_panel_field' ),
'search_panel_field15' => array( 'field' => 'cont_tipo',
'type' => 'search_panel_field' ),
'search_panel_field14' => array( 'field' => 'NUMC',
'type' => 'search_panel_field' ),
'search_panel_field13' => array( 'field' => 'CODC',
'type' => 'search_panel_field' ),
'search_panel_field12' => array( 'field' => 'contractor_email',
'type' => 'search_panel_field' ),
'search_panel_field11' => array( 'field' => 'contractor_nombresfull',
'type' => 'search_panel_field' ),
'search_panel_field10' => array( 'field' => 'DOCID',
'type' => 'search_panel_field' ),
'search_panel_field9' => array( 'field' => 'contractor_type',
'type' => 'search_panel_field' ),
'search_panel_field34' => array( 'field' => 'cont_objeto',
'type' => 'search_panel_field' ),
'search_panel_field33' => array( 'field' => 'periodo_meses',
'type' => 'search_panel_field' ),
'search_panel_field32' => array( 'field' => 'cont_informessug',
'type' => 'search_panel_field' ),
'search_panel_field31' => array( 'field' => 'periodo_dias',
'type' => 'search_panel_field' ),
'search_panel_field8' => array( 'field' => 'estado_nombre',
'type' => 'search_panel_field' ),
'search_panel_field7' => array( 'field' => 'cont_estado',
'type' => 'search_panel_field' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'search_panel_field3' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'id_cont',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'VIGENCIA',
'type' => 'search_panel_field' ),
'search_panel_field30' => array( 'field' => 'periodo_value',
'type' => 'search_panel_field' ),
'search_panel_field29' => array( 'field' => 'periodo_name',
'type' => 'search_panel_field' ),
'search_panel_field28' => array( 'field' => 'cont_periodicidad',
'type' => 'search_panel_field' ),
'search_panel_field' => array( 'field' => 'cont_secop_enlace',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field27' => array( 'field' => 'cont_tipoproceso',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'contrato_chart_estado' => 'true',
'contrato_chart_tipocont' => 'true',
'contrato_chart_dependencia' => 'true' ) ),
'search_panel_field5' => array( 'field' => 'cont_paa_id',
'type' => 'search_panel_field' ),
'search_panel_field38' => array( 'field' => 'iva_regimen',
'type' => 'search_panel_field' ),
'search_panel_field37' => array( 'field' => 'cont_valormensual',
'type' => 'search_panel_field' ),
'search_panel_field2' => array( 'field' => 'CONTRATOID',
'type' => 'search_panel_field' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field3',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field2',
'search_panel_field1',
'search_panel_field' ) ),
'search_panel_field36' => array( 'field' => 'VALORINICIAL',
'type' => 'search_panel_field' ),
'search_panel_field35' => array( 'field' => 'cont_fechavigencia',
'type' => 'search_panel_field' ),
'search_panel_field4' => array( 'field' => 'CONTVINCULADO',
'type' => 'search_panel_field' ),
'-2' => array( 'type' => '-' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'search_panel_field43' => array( 'field' => 'cont_causalc',
'type' => 'search_panel_field' ),
'search_panel_field42' => array( 'field' => 'des_mod_proceso',
'type' => 'search_panel_field' ),
'search_panel_field41' => array( 'field' => 'cont_modalidad',
'type' => 'search_panel_field' ),
'search_panel_field40' => array( 'field' => 'ct_tipo_nombre',
'type' => 'search_panel_field' ),
'search_panel_field39' => array( 'field' => 'cont_tipoc',
'type' => 'search_panel_field' ),
'logo1' => array( 'type' => 'logo' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'export' => array( 'type' => 'export' ),
'-3' => array( 'type' => '-' ),
'search_panel_field44' => array( 'field' => 'cont_dep',
'type' => 'search_panel_field',
'required' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'simple_grid_field1' => array( 'field' => 'CONTRATOID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field2' => array( 'type' => 'grid_field_label',
'field' => 'CONTRATOID',
'clickSort' => true ),
'simple_grid_field3' => array( 'field' => 'VIGENCIA',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field4' => array( 'type' => 'grid_field_label',
'field' => 'VIGENCIA',
'clickSort' => true ),
'simple_grid_field10' => array( 'field' => 'DOCID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'DOCID',
'clickSort' => true ),
'simple_grid_field13' => array( 'field' => 'contractor_nombresfull',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'contractor_nombresfull',
'clickSort' => true ),
'simple_grid_field26' => array( 'field' => 'FECHAI',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'FECHAI',
'clickSort' => true ),
'simple_grid_field28' => array( 'field' => 'FECHAF',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'FECHAF',
'clickSort' => true ),
'simple_grid_field32' => array( 'field' => 'VALORI',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'VALORI',
'clickSort' => true ),
'simple_grid_field5' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'ctb_tipo_nombre',
'clickSort' => true ),
'simple_grid_field' => array( 'field' => 'cont_secop_enlace',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_enlace',
'clickSort' => true ),
'grid_view' => array( 'type' => 'grid_view',
'popup' => true ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>