<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'master' => array( 'contrato_chart_estado' => array( 'preview' => false ),
'contrato_chart_tipocont' => array( 'preview' => false ),
'contrato_chart_dependencia' => array( 'preview' => false ) ),
'fields' => array( 'gridFields' => array( 'id_cont',
'CONTRATOID',
'cont_secop_enlace',
'VIGENCIA',
'cont_estado',
'estado_nombre',
'ctb_tipo_nombre',
'contractor_type',
'DOCID',
'contractor_nombresfull',
'contractor_email',
'CODC',
'NUMC',
'cont_tipo',
'nombre',
'cont_codrubro',
'cont_tipopre',
'cont_catalogo_presupuestal',
'cont_fase',
'FECHAI',
'FECHAF',
'VALORI',
'cont_fechaapertura',
'CDP',
'RP',
'cont_modalidad',
'des_mod_proceso',
'cont_tipoproceso',
'cont_periodicidad',
'periodo_name',
'periodo_value',
'periodo_dias',
'cont_informessug',
'periodo_meses',
'cont_objeto',
'cont_fechavigencia',
'cont_valormensual',
'iva_regimen',
'CONTVINCULADO',
'cont_paa_id',
'cont_dep' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_cont' => array( 'integrated_edit_field' ),
'CONTRATOID' => array( 'integrated_edit_field1' ),
'cont_secop_enlace' => array( 'integrated_edit_field2' ),
'VIGENCIA' => array( 'integrated_edit_field3' ),
'cont_estado' => array( 'integrated_edit_field5' ),
'estado_nombre' => array( 'integrated_edit_field6' ),
'ctb_tipo_nombre' => array( 'integrated_edit_field8' ),
'contractor_type' => array( 'integrated_edit_field9' ),
'DOCID' => array( 'integrated_edit_field10' ),
'contractor_nombresfull' => array( 'integrated_edit_field13' ),
'contractor_email' => array( 'integrated_edit_field14' ),
'CODC' => array( 'integrated_edit_field18' ),
'NUMC' => array( 'integrated_edit_field19' ),
'cont_tipo' => array( 'integrated_edit_field20' ),
'nombre' => array( 'integrated_edit_field21' ),
'cont_codrubro' => array( 'integrated_edit_field22' ),
'cont_tipopre' => array( 'integrated_edit_field23' ),
'cont_catalogo_presupuestal' => array( 'integrated_edit_field24' ),
'cont_fase' => array( 'integrated_edit_field25' ),
'FECHAI' => array( 'integrated_edit_field26' ),
'FECHAF' => array( 'integrated_edit_field28' ),
'VALORI' => array( 'integrated_edit_field32' ),
'cont_fechaapertura' => array( 'integrated_edit_field33' ),
'CDP' => array( 'integrated_edit_field34' ),
'RP' => array( 'integrated_edit_field35' ),
'cont_modalidad' => array( 'integrated_edit_field36' ),
'des_mod_proceso' => array( 'integrated_edit_field37' ),
'cont_tipoproceso' => array( 'integrated_edit_field38' ),
'cont_periodicidad' => array( 'integrated_edit_field39' ),
'periodo_name' => array( 'integrated_edit_field40' ),
'periodo_value' => array( 'integrated_edit_field41' ),
'periodo_dias' => array( 'integrated_edit_field42' ),
'cont_informessug' => array( 'integrated_edit_field43' ),
'periodo_meses' => array( 'integrated_edit_field44' ),
'cont_objeto' => array( 'integrated_edit_field45' ),
'cont_fechavigencia' => array( 'integrated_edit_field46' ),
'cont_valormensual' => array( 'integrated_edit_field48' ),
'iva_regimen' => array( 'integrated_edit_field49' ),
'CONTVINCULADO' => array( 'integrated_edit_field50' ),
'cont_paa_id' => array( 'integrated_edit_field51' ),
'cont_dep' => array( 'integrated_edit_field4' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close' ),
'grid' => array( 'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field',
'integrated_edit_field5',
'integrated_edit_field1',
'integrated_edit_field3',
'integrated_edit_field6',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field46',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field8',
'integrated_edit_field45' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array( 'back_button',
'close_button' ) ),
'itemForms' => array( 'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field28' => 'grid',
'integrated_edit_field32' => 'grid',
'integrated_edit_field33' => 'grid',
'integrated_edit_field34' => 'grid',
'integrated_edit_field35' => 'grid',
'integrated_edit_field36' => 'grid',
'integrated_edit_field37' => 'grid',
'integrated_edit_field38' => 'grid',
'integrated_edit_field39' => 'grid',
'integrated_edit_field40' => 'grid',
'integrated_edit_field41' => 'grid',
'integrated_edit_field42' => 'grid',
'integrated_edit_field43' => 'grid',
'integrated_edit_field44' => 'grid',
'integrated_edit_field46' => 'grid',
'integrated_edit_field48' => 'grid',
'integrated_edit_field49' => 'grid',
'integrated_edit_field50' => 'grid',
'integrated_edit_field51' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field45' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c17' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c20' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c21' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'integrated_edit_field28' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'integrated_edit_field32' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field33' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_edit_field34' => array( 'location' => 'grid',
'cellId' => 'c24' ),
'integrated_edit_field35' => array( 'location' => 'grid',
'cellId' => 'c25' ),
'integrated_edit_field36' => array( 'location' => 'grid',
'cellId' => 'c26' ),
'integrated_edit_field37' => array( 'location' => 'grid',
'cellId' => 'c27' ),
'integrated_edit_field38' => array( 'location' => 'grid',
'cellId' => 'c28' ),
'integrated_edit_field39' => array( 'location' => 'grid',
'cellId' => 'c29' ),
'integrated_edit_field40' => array( 'location' => 'grid',
'cellId' => 'c30' ),
'integrated_edit_field41' => array( 'location' => 'grid',
'cellId' => 'c31' ),
'integrated_edit_field42' => array( 'location' => 'grid',
'cellId' => 'c32' ),
'integrated_edit_field43' => array( 'location' => 'grid',
'cellId' => 'c33' ),
'integrated_edit_field44' => array( 'location' => 'grid',
'cellId' => 'c34' ),
'integrated_edit_field46' => array( 'location' => 'grid',
'cellId' => 'c36' ),
'integrated_edit_field48' => array( 'location' => 'grid',
'cellId' => 'c37' ),
'integrated_edit_field49' => array( 'location' => 'grid',
'cellId' => 'c38' ),
'integrated_edit_field50' => array( 'location' => 'grid',
'cellId' => 'c39' ),
'integrated_edit_field51' => array( 'location' => 'grid',
'cellId' => 'c40' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c41' ),
'integrated_edit_field45' => array( 'location' => 'grid',
'cellId' => 'c42' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field4' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c29' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c30' => array( 'cols' => array( 0 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c31' => array( 'cols' => array( 1 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c32' => array( 'cols' => array( 0 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c33' => array( 'cols' => array( 1 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c34' => array( 'cols' => array( 0 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field44' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c35' => array( 'cols' => array( 1 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c36' => array( 'cols' => array( 0 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field46' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c37' => array( 'cols' => array( 1 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field48' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c38' => array( 'cols' => array( 0 ),
'rows' => array( 18 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field49' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c39' => array( 'cols' => array( 1 ),
'rows' => array( 18 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field50' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c40' => array( 'cols' => array( 0 ),
'rows' => array( 19 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field51' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c41' => array( 'cols' => array( 1 ),
'rows' => array( 19 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c42' => array( 'cols' => array( 0,
1 ),
'rows' => array( 20 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field45' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 21 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 21 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 22 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c14' ),
array( 'cell' => 'c15' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c17' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c18' ),
array( 'cell' => 'c19' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c20' ),
array( 'cell' => 'c21' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c22' ),
array( 'cell' => 'c23' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c24' ),
array( 'cell' => 'c25' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c26' ),
array( 'cell' => 'c27' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c28' ),
array( 'cell' => 'c29' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c30' ),
array( 'cell' => 'c31' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c32' ),
array( 'cell' => 'c33' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c34' ),
array( 'cell' => 'c35' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c36' ),
array( 'cell' => 'c37' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c38' ),
array( 'cell' => 'c39' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c40' ),
array( 'cell' => 'c41' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c42',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ) ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field9' ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field10' ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field13' ) ),
'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field14' ) ),
'c13' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field18' ) ),
'c14' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field19' ) ),
'c15' => array( 'model' => 'c3',
'items' => array(  ) ),
'c16' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field20' ) ),
'c17' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field21' ) ),
'c18' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field22' ) ),
'c19' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field23' ) ),
'c20' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field24' ) ),
'c21' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field25' ) ),
'c22' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field26' ) ),
'c23' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field28' ) ),
'c1' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field32' ) ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field33' ) ),
'c24' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field34' ) ),
'c25' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field35' ) ),
'c26' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field36' ) ),
'c27' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field37' ) ),
'c28' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field38' ) ),
'c29' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field39' ) ),
'c30' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field40' ) ),
'c31' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field41' ) ),
'c32' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field42' ) ),
'c33' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field43' ) ),
'c34' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field44' ) ),
'c35' => array( 'model' => 'c3',
'items' => array(  ) ),
'c36' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field46' ) ),
'c37' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field48' ) ),
'c38' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field49' ) ),
'c39' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field50' ) ),
'c40' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field51' ) ),
'c41' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field8' ) ),
'c42' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field45' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'integrated_edit_field' => array( 'field' => 'id_cont',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'CONTRATOID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'cont_secop_enlace',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'VIGENCIA',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'cont_estado',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'estado_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'contractor_type',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'DOCID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'contractor_nombresfull',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'contractor_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'CODC',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'NUMC',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'cont_tipo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'cont_codrubro',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'cont_tipopre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'cont_fase',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'FECHAI',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'FECHAF',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'VALORI',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field33' => array( 'field' => 'cont_fechaapertura',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'CDP',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'RP',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'cont_modalidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'des_mod_proceso',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'cont_tipoproceso',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'cont_periodicidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'periodo_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field41' => array( 'field' => 'periodo_value',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'periodo_dias',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'cont_informessug',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'periodo_meses',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'cont_objeto',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'cont_fechavigencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field48' => array( 'field' => 'cont_valormensual',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field49' => array( 'field' => 'iva_regimen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field50' => array( 'field' => 'CONTVINCULADO',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field51' => array( 'field' => 'cont_paa_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'cont_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>