<?php
			$optionsArray = array( 'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'CONTRATOID' => array( 'totalsType' => '' ),
'LOGINLEVEL' => array( 'totalsType' => '' ),
'VIGENCIA' => array( 'totalsType' => '' ),
'cont_unspsc' => array( 'totalsType' => '' ),
'cont_munejec' => array( 'totalsType' => '' ),
'cont_hash' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'estado_nombre' => array( 'totalsType' => '' ),
'estado_img' => array( 'totalsType' => '' ),
'estado_lnk' => array( 'totalsType' => '' ),
'contractor_type' => array( 'totalsType' => '' ),
'DOCID' => array( 'totalsType' => '' ),
'contractor_name' => array( 'totalsType' => '' ),
'contractor_lname' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'contractor_email_mincit' => array( 'totalsType' => '' ),
'contractor_phone' => array( 'totalsType' => '' ),
'contractor_mobile' => array( 'totalsType' => '' ),
'CODC' => array( 'totalsType' => '' ),
'NUMC' => array( 'totalsType' => '' ),
'cont_tipo' => array( 'totalsType' => '' ),
'nombre' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_fase' => array( 'totalsType' => '' ),
'FECHAI' => array( 'totalsType' => '' ),
'FECHAINICIO' => array( 'totalsType' => '' ),
'FECHAF' => array( 'totalsType' => '' ),
'FECHAFINAL' => array( 'totalsType' => '' ),
'QTYDIAS' => array( 'totalsType' => '' ),
'QTYMESES' => array( 'totalsType' => '' ),
'VALORI' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'CDP' => array( 'totalsType' => '' ),
'RP' => array( 'totalsType' => '' ),
'cont_tipoproceso' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'periodo_name' => array( 'totalsType' => '' ),
'periodo_value' => array( 'totalsType' => '' ),
'periodo_dias' => array( 'totalsType' => '' ),
'cont_informessug' => array( 'totalsType' => '' ),
'periodo_meses' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_fechavigencia' => array( 'totalsType' => '' ),
'VALORINICIAL' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'iva_regimen' => array( 'totalsType' => '' ),
'cont_iva' => array( 'totalsType' => '' ),
'cont_valormensual_base' => array( 'totalsType' => '' ),
'cont_valormensual_iva' => array( 'totalsType' => '' ),
'CONTVINCULADO' => array( 'totalsType' => '' ),
'cont_paa_id' => array( 'totalsType' => '' ),
'cont_tipoc' => array( 'totalsType' => '' ),
'ct_tipo_nombre' => array( 'totalsType' => '' ),
'cont_modalidad' => array( 'totalsType' => '' ),
'des_mod_proceso' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'ctb_tipo_nombre' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'cont_dep' => array( 'totalsType' => '' ),
'contractor_naturaleza' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'CONTRATOID',
'LOGINLEVEL',
'VIGENCIA',
'cont_estado',
'DOCID',
'contractor_nombresfull',
'contractor_email',
'contractor_email_mincit',
'contractor_phone',
'contractor_mobile',
'CODC',
'NUMC',
'FECHAI',
'FECHAF',
'QTYDIAS',
'QTYMESES',
'VALORI',
'CDP',
'RP',
'cont_dep',
'VALORINICIAL',
'cont_secop_enlace',
'ctb_tipo_nombre',
'CONTVINCULADO',
'cont_causalc',
'des_mod_proceso',
'cont_modalidad',
'ct_tipo_nombre',
'cont_tipoc',
'cont_paa_id',
'estado_nombre',
'cont_iva',
'cont_valormensual_base',
'cont_valormensual_iva',
'cont_unspsc',
'cont_munejec',
'contractor_naturaleza' ),
'exportFields' => array( 'CONTRATOID',
'LOGINLEVEL',
'VIGENCIA',
'cont_estado',
'DOCID',
'contractor_nombresfull',
'contractor_email',
'contractor_email_mincit',
'contractor_phone',
'contractor_mobile',
'CODC',
'NUMC',
'FECHAI',
'FECHAF',
'QTYDIAS',
'QTYMESES',
'VALORI',
'CDP',
'RP',
'VALORINICIAL',
'CONTVINCULADO',
'estado_nombre',
'cont_paa_id',
'cont_tipoc',
'ct_tipo_nombre',
'cont_modalidad',
'des_mod_proceso',
'cont_causalc',
'ctb_tipo_nombre',
'cont_secop_enlace',
'cont_dep',
'cont_iva',
'cont_valormensual_base',
'cont_valormensual_iva',
'cont_unspsc',
'cont_munejec',
'contractor_naturaleza' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'CONTRATOID' => array( 'export_field1' ),
'LOGINLEVEL' => array( 'export_field2' ),
'VIGENCIA' => array( 'export_field3' ),
'cont_estado' => array( 'export_field5' ),
'DOCID' => array( 'export_field10' ),
'contractor_nombresfull' => array( 'export_field13' ),
'contractor_email' => array( 'export_field14' ),
'contractor_email_mincit' => array( 'export_field15' ),
'contractor_phone' => array( 'export_field16' ),
'contractor_mobile' => array( 'export_field17' ),
'CODC' => array( 'export_field18' ),
'NUMC' => array( 'export_field19' ),
'FECHAI' => array( 'export_field26' ),
'FECHAF' => array( 'export_field28' ),
'QTYDIAS' => array( 'export_field30' ),
'QTYMESES' => array( 'export_field31' ),
'VALORI' => array( 'export_field32' ),
'CDP' => array( 'export_field34' ),
'RP' => array( 'export_field35' ),
'cont_dep' => array( 'export_field21' ),
'VALORINICIAL' => array( 'export_field47' ),
'cont_secop_enlace' => array( 'export_field20' ),
'ctb_tipo_nombre' => array( 'export_field12' ),
'CONTVINCULADO' => array( 'export_field50' ),
'cont_causalc' => array( 'export_field11' ),
'des_mod_proceso' => array( 'export_field9' ),
'cont_modalidad' => array( 'export_field8' ),
'ct_tipo_nombre' => array( 'export_field7' ),
'cont_tipoc' => array( 'export_field6' ),
'cont_paa_id' => array( 'export_field4' ),
'estado_nombre' => array( 'export_field' ),
'cont_iva' => array( 'export_field22' ),
'cont_valormensual_base' => array( 'export_field23' ),
'cont_valormensual_iva' => array( 'export_field24' ),
'cont_unspsc' => array( 'export_field25' ),
'cont_munejec' => array( 'export_field27' ),
'contractor_naturaleza' => array( 'export_field29' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field10',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field26',
'export_field28',
'export_field30',
'export_field31',
'export_field32',
'export_field34',
'export_field35',
'export_field47',
'export_field50',
'export_field',
'export_field4',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field11',
'export_field12',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field27',
'export_field29' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field5' => 'grid',
'export_field10' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field26' => 'grid',
'export_field28' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field47' => 'grid',
'export_field50' => 'grid',
'export_field' => 'grid',
'export_field4' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field27' => 'grid',
'export_field29' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field10',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field26',
'export_field28',
'export_field30',
'export_field31',
'export_field32',
'export_field34',
'export_field35',
'export_field21',
'export_field47',
'export_field20',
'export_field12',
'export_field50',
'export_field11',
'export_field9',
'export_field8',
'export_field7',
'export_field6',
'export_field4',
'export_field',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field27',
'export_field29' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => true,
'delimiter' => ',',
'selectDelimiter' => true,
'exportFileTypes' => array( 'excel' => true,
'word' => false,
'csv' => true,
'xml' => true ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field10',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field26',
'export_field28',
'export_field30',
'export_field31',
'export_field32',
'export_field34',
'export_field35',
'export_field47',
'export_field50',
'export_field',
'export_field4',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field11',
'export_field12',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field27',
'export_field29' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'CONTRATOID',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'LOGINLEVEL',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'VIGENCIA',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'cont_estado',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'DOCID',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'contractor_nombresfull',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'contractor_email',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'contractor_email_mincit',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'contractor_phone',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'contractor_mobile',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'CODC',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'NUMC',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'FECHAI',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'FECHAF',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'QTYDIAS',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'QTYMESES',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'VALORI',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'CDP',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'RP',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'cont_dep',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'VALORINICIAL',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'cont_secop_enlace',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'CONTVINCULADO',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'cont_causalc',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'des_mod_proceso',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'cont_modalidad',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'ct_tipo_nombre',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'cont_tipoc',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'cont_paa_id',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'estado_nombre',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'cont_iva',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'cont_valormensual_base',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'cont_valormensual_iva',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'cont_unspsc',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'cont_munejec',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'contractor_naturaleza',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => true,
'exportSelectFields' => true,
'fileTypes' => array( 'excel' => true,
'word' => false,
'csv' => true,
'xml' => true ) );
		?>