<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'contractor_type',
'contractor_email_mincit',
'cont_fechafinal',
'cont_valormensual',
'contractor_email',
'cont_fecha_inicio',
'contractor_nombresfull',
'cont_ano',
'cont_valorinicial',
'cont_periodicidad',
'nombre_dependencia',
'cont_tipo_rubro',
'nombre_cargo',
'nombresupfull',
'Departamento_superior',
'cont_objeto',
'cont_nit_contra_ta',
'numcontrato',
'PLAZO',
'cont_estado',
'cont_unspsc',
'numregistro',
'ctb_tipo_nombre',
'cont_codrubro',
'cont_munejec',
'cont_fechaapertura',
'prenumero',
'cont_tipopre',
'cont_causalc',
'cont_secop_enlace',
'cont_secop_proceso',
'cont_fecha_aprobgarantia' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'contractor_type' => array( 'grid_field_label',
'grid_field' ),
'contractor_email_mincit' => array( 'grid_field_label8',
'grid_field8' ),
'cont_fechafinal' => array( 'grid_field_label16',
'grid_field16' ),
'cont_valormensual' => array( 'grid_field_label24',
'grid_field24' ),
'contractor_email' => array( 'grid_field_label6',
'grid_field6' ),
'cont_fecha_inicio' => array( 'grid_field_label14',
'grid_field14' ),
'cont_valorinicial' => array( 'grid_field_label22',
'grid_field22' ),
'nombre_cargo' => array( 'grid_field_label30',
'grid_field30' ),
'nombre_dependencia' => array( 'grid_field_label1',
'grid_field1' ),
'cont_tipo_rubro' => array( 'grid_field_label9',
'grid_field9' ),
'contractor_nombresfull' => array( 'grid_field_label4',
'grid_field4' ),
'cont_ano' => array( 'grid_field_label12',
'grid_field12' ),
'cont_periodicidad' => array( 'grid_field_label20',
'grid_field20' ),
'nombresupfull' => array( 'grid_field_label28',
'grid_field28' ),
'Departamento_superior' => array( 'grid_field_label17',
'grid_field17' ),
'cont_objeto' => array( 'grid_field_label25',
'grid_field25' ),
'cont_unspsc' => array( 'grid_field_label7',
'grid_field7' ),
'numregistro' => array( 'grid_field_label5',
'grid_field5' ),
'cont_nit_contra_ta' => array( 'grid_field_label2',
'grid_field2' ),
'numcontrato' => array( 'grid_field_label10',
'grid_field10' ),
'ctb_tipo_nombre' => array( 'grid_field_label15',
'grid_field15' ),
'cont_codrubro' => array( 'grid_field_label13',
'grid_field13' ),
'PLAZO' => array( 'grid_field_label18',
'grid_field18' ),
'cont_estado' => array( 'grid_field_label26',
'grid_field26' ),
'cont_munejec' => array( 'grid_field_label23',
'grid_field23' ),
'cont_fechaapertura' => array( 'grid_field_label21',
'grid_field21' ),
'cont_causalc' => array( 'grid_field_label31',
'grid_field31' ),
'cont_secop_enlace' => array( 'grid_field_label29',
'grid_field29' ),
'prenumero' => array( 'grid_field_label3',
'grid_field3' ),
'cont_tipopre' => array( 'grid_field_label11',
'grid_field11' ),
'cont_fecha_aprobgarantia' => array( 'grid_field_label19',
'grid_field19' ),
'cont_secop_proceso' => array( 'grid_field_label27',
'grid_field27' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'back_master',
'masterlist_header' ),
'above-grid' => array(  ),
'grid' => array( 'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1',
'grid_field_label2',
'grid_field2',
'grid_field_label3',
'grid_field3',
'grid_field_label4',
'grid_field4',
'grid_field_label5',
'grid_field5',
'grid_field_label6',
'grid_field6',
'grid_field_label7',
'grid_field7',
'grid_field_label8',
'grid_field8',
'grid_field_label9',
'grid_field9',
'grid_field_label10',
'grid_field10',
'grid_field_label11',
'grid_field11',
'grid_field_label12',
'grid_field12',
'grid_field_label13',
'grid_field13',
'grid_field_label14',
'grid_field14',
'grid_field_label15',
'grid_field15',
'grid_field_label16',
'grid_field16',
'grid_field_label17',
'grid_field17',
'grid_field_label18',
'grid_field18',
'grid_field_label19',
'grid_field19',
'grid_field_label20',
'grid_field20',
'grid_field_label21',
'grid_field21',
'grid_field_label22',
'grid_field22',
'grid_field_label23',
'grid_field23',
'grid_field_label24',
'grid_field24',
'grid_field_label25',
'grid_field25',
'grid_field_label26',
'grid_field26',
'grid_field_label27',
'grid_field27',
'grid_field_label28',
'grid_field28',
'grid_field_label29',
'grid_field29',
'grid_field_label30',
'grid_field30',
'grid_field_label31',
'grid_field31' ),
'below-grid' => array(  ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array(  ) ),
'itemForms' => array( 'back_master' => 'top',
'masterlist_header' => 'top',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label10' => 'grid',
'grid_field10' => 'grid',
'grid_field_label11' => 'grid',
'grid_field11' => 'grid',
'grid_field_label12' => 'grid',
'grid_field12' => 'grid',
'grid_field_label13' => 'grid',
'grid_field13' => 'grid',
'grid_field_label14' => 'grid',
'grid_field14' => 'grid',
'grid_field_label15' => 'grid',
'grid_field15' => 'grid',
'grid_field_label16' => 'grid',
'grid_field16' => 'grid',
'grid_field_label17' => 'grid',
'grid_field17' => 'grid',
'grid_field_label18' => 'grid',
'grid_field18' => 'grid',
'grid_field_label19' => 'grid',
'grid_field19' => 'grid',
'grid_field_label20' => 'grid',
'grid_field20' => 'grid',
'grid_field_label21' => 'grid',
'grid_field21' => 'grid',
'grid_field_label22' => 'grid',
'grid_field22' => 'grid',
'grid_field_label23' => 'grid',
'grid_field23' => 'grid',
'grid_field_label24' => 'grid',
'grid_field24' => 'grid',
'grid_field_label25' => 'grid',
'grid_field25' => 'grid',
'grid_field_label26' => 'grid',
'grid_field26' => 'grid',
'grid_field_label27' => 'grid',
'grid_field27' => 'grid',
'grid_field_label28' => 'grid',
'grid_field28' => 'grid',
'grid_field_label29' => 'grid',
'grid_field29' => 'grid',
'grid_field_label30' => 'grid',
'grid_field30' => 'grid',
'grid_field_label31' => 'grid',
'grid_field31' => 'grid' ),
'itemLocations' => array( 'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'cell_label9' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field_label10' => array( 'location' => 'grid',
'cellId' => 'cell_label10' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field_label11' => array( 'location' => 'grid',
'cellId' => 'cell_label11' ),
'grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label12' => array( 'location' => 'grid',
'cellId' => 'cell_label12' ),
'grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label13' => array( 'location' => 'grid',
'cellId' => 'cell_label13' ),
'grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'grid_field_label14' => array( 'location' => 'grid',
'cellId' => 'cell_label14' ),
'grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'grid_field_label15' => array( 'location' => 'grid',
'cellId' => 'cell_label15' ),
'grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'grid_field_label16' => array( 'location' => 'grid',
'cellId' => 'cell_label16' ),
'grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'grid_field_label17' => array( 'location' => 'grid',
'cellId' => 'cell_label17' ),
'grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'grid_field_label18' => array( 'location' => 'grid',
'cellId' => 'cell_label18' ),
'grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'grid_field_label19' => array( 'location' => 'grid',
'cellId' => 'cell_label19' ),
'grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'grid_field_label20' => array( 'location' => 'grid',
'cellId' => 'cell_label20' ),
'grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'grid_field_label21' => array( 'location' => 'grid',
'cellId' => 'cell_label21' ),
'grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'grid_field_label22' => array( 'location' => 'grid',
'cellId' => 'cell_label22' ),
'grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'grid_field_label23' => array( 'location' => 'grid',
'cellId' => 'cell_label23' ),
'grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'grid_field_label24' => array( 'location' => 'grid',
'cellId' => 'cell_label24' ),
'grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'grid_field_label25' => array( 'location' => 'grid',
'cellId' => 'cell_label25' ),
'grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'grid_field_label26' => array( 'location' => 'grid',
'cellId' => 'cell_label26' ),
'grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'grid_field_label27' => array( 'location' => 'grid',
'cellId' => 'cell_label27' ),
'grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'grid_field_label28' => array( 'location' => 'grid',
'cellId' => 'cell_label28' ),
'grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'grid_field_label29' => array( 'location' => 'grid',
'cellId' => 'cell_label29' ),
'grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'grid_field_label30' => array( 'location' => 'grid',
'cellId' => 'cell_label30' ),
'grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'grid_field_label31' => array( 'location' => 'grid',
'cellId' => 'cell_label31' ),
'grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'masterlist_header' => array( 'masterlist_header' ),
'back_master' => array( 'back_master' ),
'grid_field_label' => array( 'grid_field_label',
'grid_field_label8',
'grid_field_label16',
'grid_field_label24',
'grid_field_label6',
'grid_field_label14',
'grid_field_label22',
'grid_field_label30',
'grid_field_label1',
'grid_field_label9',
'grid_field_label4',
'grid_field_label12',
'grid_field_label20',
'grid_field_label28',
'grid_field_label17',
'grid_field_label25',
'grid_field_label7',
'grid_field_label5',
'grid_field_label2',
'grid_field_label10',
'grid_field_label15',
'grid_field_label13',
'grid_field_label18',
'grid_field_label26',
'grid_field_label23',
'grid_field_label21',
'grid_field_label31',
'grid_field_label29',
'grid_field_label3',
'grid_field_label11',
'grid_field_label19',
'grid_field_label27' ),
'grid_field' => array( 'grid_field',
'grid_field8',
'grid_field16',
'grid_field24',
'grid_field6',
'grid_field14',
'grid_field4',
'grid_field12',
'grid_field22',
'grid_field20',
'grid_field1',
'grid_field9',
'grid_field30',
'grid_field28',
'grid_field17',
'grid_field25',
'grid_field2',
'grid_field10',
'grid_field18',
'grid_field26',
'grid_field7',
'grid_field5',
'grid_field15',
'grid_field13',
'grid_field23',
'grid_field21',
'grid_field3',
'grid_field11',
'grid_field31',
'grid_field29',
'grid_field27',
'grid_field19' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_type_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_type_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'nombre_dependencia_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'nombre_dependencia_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'cont_nit_contra_ta_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'cont_nit_contra_ta_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'prenumero_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'prenumero_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'contractor_nombresfull_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'contractor_nombresfull_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'numregistro_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'numregistro_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'contractor_email_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'contractor_email_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'cont_unspsc_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'cont_unspsc_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'contractor_email_mincit_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'contractor_email_mincit_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array( 'cont_tipo_rubro_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'cont_tipo_rubro_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label10' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'numcontrato_fieldheadercolumn' ),
'items' => array( 'grid_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array( 'numcontrato_fieldcolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array( 'cont_tipopre_fieldheadercolumn' ),
'items' => array( 'grid_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 3 ),
'rows' => array( 6 ),
'tags' => array( 'cont_tipopre_fieldcolumn' ),
'items' => array( 'grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label12' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'cont_ano_fieldheadercolumn' ),
'items' => array( 'grid_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array( 'cont_ano_fieldcolumn' ),
'items' => array( 'grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label13' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array( 'cont_codrubro_fieldheadercolumn' ),
'items' => array( 'grid_field_label13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array( 'cont_codrubro_fieldcolumn' ),
'items' => array( 'grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label14' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'cont_fecha_inicio_fieldheadercolumn' ),
'items' => array( 'grid_field_label14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array( 'cont_fecha_inicio_fieldcolumn' ),
'items' => array( 'grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label15' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array( 'ctb_tipo_nombre_fieldheadercolumn' ),
'items' => array( 'grid_field_label15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 3 ),
'rows' => array( 8 ),
'tags' => array( 'ctb_tipo_nombre_fieldcolumn' ),
'items' => array( 'grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label16' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'cont_fechafinal_fieldheadercolumn' ),
'items' => array( 'grid_field_label16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array( 'cont_fechafinal_fieldcolumn' ),
'items' => array( 'grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label17' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array( 'Departamento_superior_fieldheadercolumn' ),
'items' => array( 'grid_field_label17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array( 'Departamento_superior_fieldcolumn' ),
'items' => array( 'grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label18' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array( 'PLAZO_fieldheadercolumn' ),
'items' => array( 'grid_field_label18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array( 'PLAZO_fieldcolumn' ),
'items' => array( 'grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label19' => array( 'cols' => array( 2 ),
'rows' => array( 10 ),
'tags' => array( 'cont_fecha_aprobgarantia_fieldheadercolumn' ),
'items' => array( 'grid_field_label19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 3 ),
'rows' => array( 10 ),
'tags' => array( 'cont_fecha_aprobgarantia_fieldcolumn' ),
'items' => array( 'grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label20' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array( 'cont_periodicidad_fieldheadercolumn' ),
'items' => array( 'grid_field_label20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array( 'cont_periodicidad_fieldcolumn' ),
'items' => array( 'grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label21' => array( 'cols' => array( 2 ),
'rows' => array( 11 ),
'tags' => array( 'cont_fechaapertura_fieldheadercolumn' ),
'items' => array( 'grid_field_label21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 3 ),
'rows' => array( 11 ),
'tags' => array( 'cont_fechaapertura_fieldcolumn' ),
'items' => array( 'grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label22' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array( 'cont_valorinicial_fieldheadercolumn' ),
'items' => array( 'grid_field_label22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array( 'cont_valorinicial_fieldcolumn' ),
'items' => array( 'grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label23' => array( 'cols' => array( 2 ),
'rows' => array( 12 ),
'tags' => array( 'cont_munejec_fieldheadercolumn' ),
'items' => array( 'grid_field_label23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 3 ),
'rows' => array( 12 ),
'tags' => array( 'cont_munejec_fieldcolumn' ),
'items' => array( 'grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label24' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array( 'cont_valormensual_fieldheadercolumn' ),
'items' => array( 'grid_field_label24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array( 'cont_valormensual_fieldcolumn' ),
'items' => array( 'grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label25' => array( 'cols' => array( 2 ),
'rows' => array( 13 ),
'tags' => array( 'cont_objeto_fieldheadercolumn' ),
'items' => array( 'grid_field_label25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 3 ),
'rows' => array( 13 ),
'tags' => array( 'cont_objeto_fieldcolumn' ),
'items' => array( 'grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label26' => array( 'cols' => array( 0 ),
'rows' => array( 14 ),
'tags' => array( 'cont_estado_fieldheadercolumn' ),
'items' => array( 'grid_field_label26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 1 ),
'rows' => array( 14 ),
'tags' => array( 'cont_estado_fieldcolumn' ),
'items' => array( 'grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label27' => array( 'cols' => array( 2 ),
'rows' => array( 14 ),
'tags' => array( 'cont_secop_proceso_fieldheadercolumn' ),
'items' => array( 'grid_field_label27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 3 ),
'rows' => array( 14 ),
'tags' => array( 'cont_secop_proceso_fieldcolumn' ),
'items' => array( 'grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label28' => array( 'cols' => array( 0 ),
'rows' => array( 15 ),
'tags' => array( 'nombresupfull_fieldheadercolumn' ),
'items' => array( 'grid_field_label28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 1 ),
'rows' => array( 15 ),
'tags' => array( 'nombresupfull_fieldcolumn' ),
'items' => array( 'grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label29' => array( 'cols' => array( 2 ),
'rows' => array( 15 ),
'tags' => array( 'cont_secop_enlace_fieldheadercolumn' ),
'items' => array( 'grid_field_label29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 3 ),
'rows' => array( 15 ),
'tags' => array( 'cont_secop_enlace_fieldcolumn' ),
'items' => array( 'grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label30' => array( 'cols' => array( 0 ),
'rows' => array( 16 ),
'tags' => array( 'nombre_cargo_fieldheadercolumn' ),
'items' => array( 'grid_field_label30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 1 ),
'rows' => array( 16 ),
'tags' => array( 'nombre_cargo_fieldcolumn' ),
'items' => array( 'grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label31' => array( 'cols' => array( 2 ),
'rows' => array( 16 ),
'tags' => array( 'cont_causalc_fieldheadercolumn' ),
'items' => array( 'grid_field_label31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 3 ),
'rows' => array( 16 ),
'tags' => array( 'cont_causalc_fieldcolumn' ),
'items' => array( 'grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 17 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 18 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 2,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'masterlist',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterlist',
'type' => 'masterlist',
'layoutId' => 'masterlist',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'back_master',
'masterlist_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 4 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field9' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label10' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label12' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_label13' ),
array( 'cell' => 'cell_field13' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label14' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_label15' ),
array( 'cell' => 'cell_field15' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label16' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_label17' ),
array( 'cell' => 'cell_field17' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label18' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_label19' ),
array( 'cell' => 'cell_field19' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label20' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_label21' ),
array( 'cell' => 'cell_field21' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label22' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_label23' ),
array( 'cell' => 'cell_field23' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label24' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_label25' ),
array( 'cell' => 'cell_field25' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label26' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_label27' ),
array( 'cell' => 'cell_field27' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label28' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_label29' ),
array( 'cell' => 'cell_field29' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label30' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_label31' ),
array( 'cell' => 'cell_field31' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 4 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'contractor_type',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'contractor_type',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label1' ),
'field' => 'nombre_dependencia',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'nombre_dependencia',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label2' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label3' ),
'field' => 'prenumero',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'prenumero',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label4' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label5' ),
'field' => 'numregistro',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'numregistro',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label6' ),
'field' => 'contractor_email',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'contractor_email',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label7' ),
'field' => 'cont_unspsc',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'cont_unspsc',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label8' ),
'field' => 'contractor_email_mincit',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'contractor_email_mincit',
'columnName' => 'field' ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label9' ),
'field' => 'cont_tipo_rubro',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'cont_tipo_rubro',
'columnName' => 'field' ),
'cell_label10' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label10' ),
'field' => 'numcontrato',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field10' ),
'field' => 'numcontrato',
'columnName' => 'field' ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label11' ),
'field' => 'cont_tipopre',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'grid_field11' ),
'field' => 'cont_tipopre',
'columnName' => 'field' ),
'cell_label12' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label12' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field12' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_label13' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label13' ),
'field' => 'cont_codrubro',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'grid_field13' ),
'field' => 'cont_codrubro',
'columnName' => 'field' ),
'cell_label14' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label14' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'grid_field14' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_label15' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label15' ),
'field' => 'ctb_tipo_nombre',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'grid_field15' ),
'field' => 'ctb_tipo_nombre',
'columnName' => 'field' ),
'cell_label16' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label16' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'grid_field16' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_label17' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label17' ),
'field' => 'Departamento_superior',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'grid_field17' ),
'field' => 'Departamento_superior',
'columnName' => 'field' ),
'cell_label18' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label18' ),
'field' => 'PLAZO',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'grid_field18' ),
'field' => 'PLAZO',
'columnName' => 'field' ),
'cell_label19' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label19' ),
'field' => 'cont_fecha_aprobgarantia',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'grid_field19' ),
'field' => 'cont_fecha_aprobgarantia',
'columnName' => 'field' ),
'cell_label20' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label20' ),
'field' => 'cont_periodicidad',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'grid_field20' ),
'field' => 'cont_periodicidad',
'columnName' => 'field' ),
'cell_label21' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label21' ),
'field' => 'cont_fechaapertura',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'grid_field21' ),
'field' => 'cont_fechaapertura',
'columnName' => 'field' ),
'cell_label22' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label22' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'grid_field22' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_label23' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label23' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'grid_field23' ),
'field' => 'cont_munejec',
'columnName' => 'field' ),
'cell_label24' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label24' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'grid_field24' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_label25' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label25' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'grid_field25' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_label26' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label26' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'grid_field26' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'cell_label27' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label27' ),
'field' => 'cont_secop_proceso',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'grid_field27' ),
'field' => 'cont_secop_proceso',
'columnName' => 'field' ),
'cell_label28' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label28' ),
'field' => 'nombresupfull',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'grid_field28' ),
'field' => 'nombresupfull',
'columnName' => 'field' ),
'cell_label29' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label29' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'grid_field29' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_label30' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label30' ),
'field' => 'nombre_cargo',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'grid_field30' ),
'field' => 'nombre_cargo',
'columnName' => 'field' ),
'cell_label31' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label31' ),
'field' => 'cont_causalc',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'grid_field31' ),
'field' => 'cont_causalc',
'columnName' => 'field' ) ),
'deferredItems' => array(  ),
'buildType' => 2,
'columnCount' => 2 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'masterlist_header' => array( 'type' => 'masterlist_header' ),
'back_master' => array( 'type' => 'back_master' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'contractor_type' ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'contractor_email_mincit' ),
'grid_field_label16' => array( 'type' => 'grid_field_label',
'field' => 'cont_fechafinal' ),
'grid_field_label24' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual' ),
'grid_field' => array( 'field' => 'contractor_type',
'type' => 'grid_field' ),
'grid_field8' => array( 'field' => 'contractor_email_mincit',
'type' => 'grid_field' ),
'grid_field16' => array( 'field' => 'cont_fechafinal',
'type' => 'grid_field' ),
'grid_field24' => array( 'field' => 'cont_valormensual',
'type' => 'grid_field' ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'contractor_email' ),
'grid_field_label14' => array( 'type' => 'grid_field_label',
'field' => 'cont_fecha_inicio' ),
'grid_field_label22' => array( 'type' => 'grid_field_label',
'field' => 'cont_valorinicial' ),
'grid_field_label30' => array( 'type' => 'grid_field_label',
'field' => 'nombre_cargo' ),
'grid_field6' => array( 'field' => 'contractor_email',
'type' => 'grid_field' ),
'grid_field14' => array( 'field' => 'cont_fecha_inicio',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'nombre_dependencia' ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'cont_tipo_rubro' ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'contractor_nombresfull' ),
'grid_field_label12' => array( 'type' => 'grid_field_label',
'field' => 'cont_ano' ),
'grid_field_label20' => array( 'type' => 'grid_field_label',
'field' => 'cont_periodicidad' ),
'grid_field_label28' => array( 'type' => 'grid_field_label',
'field' => 'nombresupfull' ),
'grid_field4' => array( 'field' => 'contractor_nombresfull',
'type' => 'grid_field' ),
'grid_field12' => array( 'field' => 'cont_ano',
'type' => 'grid_field' ),
'grid_field_label17' => array( 'type' => 'grid_field_label',
'field' => 'Departamento_superior' ),
'grid_field_label25' => array( 'type' => 'grid_field_label',
'field' => 'cont_objeto' ),
'grid_field22' => array( 'field' => 'cont_valorinicial',
'type' => 'grid_field' ),
'grid_field20' => array( 'field' => 'cont_periodicidad',
'type' => 'grid_field' ),
'grid_field1' => array( 'field' => 'nombre_dependencia',
'type' => 'grid_field' ),
'grid_field9' => array( 'field' => 'cont_tipo_rubro',
'type' => 'grid_field' ),
'grid_field30' => array( 'field' => 'nombre_cargo',
'type' => 'grid_field' ),
'grid_field28' => array( 'field' => 'nombresupfull',
'type' => 'grid_field' ),
'grid_field17' => array( 'field' => 'Departamento_superior',
'type' => 'grid_field' ),
'grid_field25' => array( 'field' => 'cont_objeto',
'type' => 'grid_field' ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'cont_unspsc' ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'numregistro' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'cont_nit_contra_ta' ),
'grid_field_label10' => array( 'type' => 'grid_field_label',
'field' => 'numcontrato' ),
'grid_field_label15' => array( 'type' => 'grid_field_label',
'field' => 'ctb_tipo_nombre' ),
'grid_field_label13' => array( 'type' => 'grid_field_label',
'field' => 'cont_codrubro' ),
'grid_field_label18' => array( 'type' => 'grid_field_label',
'field' => 'PLAZO' ),
'grid_field_label26' => array( 'type' => 'grid_field_label',
'field' => 'cont_estado' ),
'grid_field_label23' => array( 'type' => 'grid_field_label',
'field' => 'cont_munejec' ),
'grid_field_label21' => array( 'type' => 'grid_field_label',
'field' => 'cont_fechaapertura' ),
'grid_field2' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'grid_field' ),
'grid_field10' => array( 'field' => 'numcontrato',
'type' => 'grid_field' ),
'grid_field_label31' => array( 'type' => 'grid_field_label',
'field' => 'cont_causalc' ),
'grid_field_label29' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_enlace' ),
'grid_field18' => array( 'field' => 'PLAZO',
'type' => 'grid_field' ),
'grid_field26' => array( 'field' => 'cont_estado',
'type' => 'grid_field' ),
'grid_field7' => array( 'field' => 'cont_unspsc',
'type' => 'grid_field' ),
'grid_field5' => array( 'field' => 'numregistro',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'prenumero' ),
'grid_field_label11' => array( 'type' => 'grid_field_label',
'field' => 'cont_tipopre' ),
'grid_field15' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'grid_field' ),
'grid_field13' => array( 'field' => 'cont_codrubro',
'type' => 'grid_field' ),
'grid_field_label19' => array( 'type' => 'grid_field_label',
'field' => 'cont_fecha_aprobgarantia' ),
'grid_field_label27' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_proceso' ),
'grid_field23' => array( 'field' => 'cont_munejec',
'type' => 'grid_field' ),
'grid_field21' => array( 'field' => 'cont_fechaapertura',
'type' => 'grid_field' ),
'grid_field3' => array( 'field' => 'prenumero',
'type' => 'grid_field' ),
'grid_field11' => array( 'field' => 'cont_tipopre',
'type' => 'grid_field' ),
'grid_field31' => array( 'field' => 'cont_causalc',
'type' => 'grid_field' ),
'grid_field29' => array( 'field' => 'cont_secop_enlace',
'type' => 'grid_field' ),
'grid_field27' => array( 'field' => 'cont_secop_proceso',
'type' => 'grid_field' ),
'grid_field19' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'grid_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>