<?php
			$optionsArray = array( 'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'contractor_type' => array( 'totalsType' => '' ),
'cont_nit_contra_ta' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'numcontrato' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_fecha_inicio' => array( 'totalsType' => '' ),
'cont_fechafinal' => array( 'totalsType' => '' ),
'PLAZO' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'cont_valorinicial' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'documento_id' => array( 'totalsType' => '' ),
'nombresupfull' => array( 'totalsType' => '' ),
'cargo_id' => array( 'totalsType' => '' ),
'dependencia_id' => array( 'totalsType' => '' ),
'sup_fechanot' => array( 'totalsType' => '' ),
'sup_mailnot' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'contractor_email_mincit' => array( 'totalsType' => '' ),
'prenumero' => array( 'totalsType' => '' ),
'numregistro' => array( 'totalsType' => '' ),
'cont_unspsc' => array( 'totalsType' => '' ),
'cont_tipo_rubro' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'ctb_tipo_nombre' => array( 'totalsType' => '' ),
'nombre_cargo' => array( 'totalsType' => '' ),
'nombre_dependencia' => array( 'totalsType' => '' ),
'Departamento_superior' => array( 'totalsType' => '' ),
'cont_secop_proceso' => array( 'totalsType' => '' ),
'cont_fecha_aprobgarantia' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'cont_munejec' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_cont',
'cont_causalc',
'cont_secop_enlace',
'cont_secop_proceso',
'cont_objeto',
'cont_munejec',
'cont_fechaapertura',
'cont_fecha_aprobgarantia',
'dependencia_id',
'Departamento_superior',
'ctb_tipo_nombre',
'cont_catalogo_presupuestal',
'cont_codrubro',
'cont_tipopre',
'cont_tipo_rubro',
'cont_unspsc',
'numregistro',
'prenumero',
'sup_fechanot',
'nombre_dependencia',
'nombre_cargo',
'sup_mailnot',
'cargo_id',
'nombresupfull',
'documento_id',
'cont_estado',
'cont_valormensual',
'cont_valorinicial',
'cont_periodicidad',
'PLAZO',
'cont_fechafinal',
'cont_fecha_inicio',
'cont_ano',
'numcontrato',
'contractor_email_mincit',
'contractor_email',
'contractor_nombresfull',
'cont_nit_contra_ta',
'contractor_type' ),
'exportFields' => array( 'contractor_type',
'cont_nit_contra_ta',
'contractor_nombresfull',
'contractor_email',
'contractor_email_mincit',
'numcontrato',
'cont_ano',
'cont_fecha_inicio',
'cont_fechafinal',
'PLAZO',
'cont_periodicidad',
'cont_valorinicial',
'cont_valormensual',
'cont_estado',
'documento_id',
'nombresupfull',
'cargo_id',
'sup_mailnot',
'nombre_cargo',
'nombre_dependencia',
'sup_fechanot',
'prenumero',
'numregistro',
'cont_unspsc',
'cont_tipo_rubro',
'cont_tipopre',
'cont_codrubro',
'cont_catalogo_presupuestal',
'ctb_tipo_nombre',
'Departamento_superior',
'dependencia_id',
'cont_fecha_aprobgarantia',
'cont_fechaapertura',
'cont_munejec',
'cont_objeto',
'cont_secop_proceso',
'cont_secop_enlace',
'cont_causalc',
'id_cont' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_cont' => array( 'export_field38' ),
'cont_causalc' => array( 'export_field37' ),
'cont_secop_enlace' => array( 'export_field36' ),
'cont_secop_proceso' => array( 'export_field35' ),
'cont_objeto' => array( 'export_field34' ),
'cont_munejec' => array( 'export_field33' ),
'cont_fechaapertura' => array( 'export_field32' ),
'cont_fecha_aprobgarantia' => array( 'export_field31' ),
'dependencia_id' => array( 'export_field30' ),
'Departamento_superior' => array( 'export_field29' ),
'ctb_tipo_nombre' => array( 'export_field28' ),
'cont_catalogo_presupuestal' => array( 'export_field27' ),
'cont_codrubro' => array( 'export_field26' ),
'cont_tipopre' => array( 'export_field25' ),
'cont_tipo_rubro' => array( 'export_field24' ),
'cont_unspsc' => array( 'export_field23' ),
'numregistro' => array( 'export_field22' ),
'prenumero' => array( 'export_field21' ),
'sup_fechanot' => array( 'export_field20' ),
'nombre_dependencia' => array( 'export_field19' ),
'nombre_cargo' => array( 'export_field18' ),
'sup_mailnot' => array( 'export_field17' ),
'cargo_id' => array( 'export_field16' ),
'nombresupfull' => array( 'export_field15' ),
'documento_id' => array( 'export_field14' ),
'cont_estado' => array( 'export_field13' ),
'cont_valormensual' => array( 'export_field12' ),
'cont_valorinicial' => array( 'export_field11' ),
'cont_periodicidad' => array( 'export_field10' ),
'PLAZO' => array( 'export_field9' ),
'cont_fechafinal' => array( 'export_field8' ),
'cont_fecha_inicio' => array( 'export_field7' ),
'cont_ano' => array( 'export_field6' ),
'numcontrato' => array( 'export_field5' ),
'contractor_email_mincit' => array( 'export_field4' ),
'contractor_email' => array( 'export_field3' ),
'contractor_nombresfull' => array( 'export_field2' ),
'cont_nit_contra_ta' => array( 'export_field1' ),
'contractor_type' => array( 'export_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field38',
'export_field37',
'export_field36',
'export_field35',
'export_field34',
'export_field33',
'export_field32',
'export_field31',
'export_field30',
'export_field29',
'export_field28',
'export_field27',
'export_field26',
'export_field25',
'export_field24',
'export_field23',
'export_field22',
'export_field21',
'export_field20',
'export_field19',
'export_field18',
'export_field17',
'export_field16',
'export_field15',
'export_field14',
'export_field13',
'export_field12',
'export_field11',
'export_field10',
'export_field9',
'export_field8',
'export_field7',
'export_field6',
'export_field5',
'export_field4',
'export_field3',
'export_field2',
'export_field1',
'export_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => false,
'csv' => false,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field38' => array( 'field' => 'id_cont',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'cont_causalc',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'cont_secop_enlace',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'cont_secop_proceso',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'cont_objeto',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'cont_munejec',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'cont_fechaapertura',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'dependencia_id',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'Departamento_superior',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'cont_codrubro',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'cont_tipopre',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'cont_tipo_rubro',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'cont_unspsc',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'numregistro',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'prenumero',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'sup_fechanot',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'nombre_dependencia',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'nombre_cargo',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'sup_mailnot',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'cargo_id',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'nombresupfull',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'documento_id',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'cont_estado',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'cont_valormensual',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'cont_valorinicial',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'cont_periodicidad',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'PLAZO',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'cont_fechafinal',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'cont_fecha_inicio',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'cont_ano',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'numcontrato',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'contractor_email_mincit',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'contractor_email',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'contractor_nombresfull',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'contractor_type',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false,
'fileTypes' => array( 'excel' => true,
'word' => false,
'csv' => false,
'xml' => false ) );
		?>