<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'cont_nit_contra_ta',
'cont_nit_contra_taname',
'cont_estado',
'numcontrato',
'cont_ano',
'cont_codrubro',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_periodicidad',
'cont_valorinicial',
'cont_valormensual',
'cont_secop_enlace',
'contractor_type' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cont_nit_contra_ta' => array( 'simple_grid_field',
'simple_grid_field1' ),
'cont_nit_contra_taname' => array( 'simple_grid_field2',
'simple_grid_field5' ),
'cont_estado' => array( 'simple_grid_field3',
'simple_grid_field6' ),
'numcontrato' => array( 'simple_grid_field4',
'simple_grid_field9' ),
'cont_ano' => array( 'simple_grid_field7',
'simple_grid_field16' ),
'cont_codrubro' => array( 'simple_grid_field8',
'simple_grid_field17' ),
'cont_fecha_inicio' => array( 'simple_grid_field10',
'simple_grid_field18' ),
'cont_fechafinal' => array( 'simple_grid_field11',
'simple_grid_field19' ),
'cont_periodicidad' => array( 'simple_grid_field12',
'simple_grid_field20' ),
'cont_valorinicial' => array( 'simple_grid_field13',
'simple_grid_field21' ),
'cont_valormensual' => array( 'simple_grid_field14',
'simple_grid_field22' ),
'cont_secop_enlace' => array( 'simple_grid_field15',
'simple_grid_field23' ),
'contractor_type' => array( 'grid_field',
'grid_field_label' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'back_master',
'masterlist_header' ),
'above-grid' => array(  ),
'grid' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field18',
'simple_grid_field10',
'simple_grid_field5',
'simple_grid_field2',
'simple_grid_field19',
'simple_grid_field11',
'simple_grid_field6',
'simple_grid_field3',
'simple_grid_field20',
'simple_grid_field12',
'simple_grid_field9',
'simple_grid_field4',
'simple_grid_field21',
'simple_grid_field13',
'simple_grid_field16',
'simple_grid_field7',
'simple_grid_field22',
'simple_grid_field14',
'simple_grid_field17',
'simple_grid_field8',
'simple_grid_field23',
'simple_grid_field15',
'grid_field_label',
'grid_field' ),
'below-grid' => array(  ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array(  ) ),
'itemForms' => array( 'back_master' => 'top',
'masterlist_header' => 'top',
'simple_grid_field' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field15' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_label9' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_label10' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_label11' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_label12' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'masterlist_header' => array( 'masterlist_header' ),
'back_master' => array( 'back_master' ),
'grid_field_label' => array( 'simple_grid_field',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field9',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'grid_field_label' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'grid_field' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'cont_nit_contra_ta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'cont_nit_contra_ta_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'cont_fecha_inicio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'cont_fecha_inicio_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'cont_nit_contra_taname_fieldheadercolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'cont_nit_contra_taname_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'cont_fechafinal_fieldheadercolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'cont_fechafinal_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'cont_estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'cont_estado_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'cont_periodicidad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'cont_periodicidad_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'numcontrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'numcontrato_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'cont_valorinicial_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'cont_valorinicial_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'cont_ano_fieldheadercolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'cont_ano_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valormensual_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valormensual_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label10' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'cont_codrubro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array( 'cont_codrubro_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array( 'cont_secop_enlace_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 3 ),
'rows' => array( 6 ),
'tags' => array( 'cont_secop_enlace_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label12' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'contractor_type_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array( 'contractor_type_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label13' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 9 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 2,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'masterlist',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterlist',
'type' => 'masterlist',
'layoutId' => 'masterlist',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'back_master',
'masterlist_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 4 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field9' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label10' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label12' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_label13' ),
array( 'cell' => 'cell_field13' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 4 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'cont_nit_contra_ta',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field18' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field5' ),
'field' => 'cont_nit_contra_taname',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'cont_nit_contra_taname',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field19' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field6' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'cont_estado',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field20' ),
'field' => 'cont_periodicidad',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'cont_periodicidad',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field9' ),
'field' => 'numcontrato',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'numcontrato',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field21' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field16' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field22' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_label10' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field17' ),
'field' => 'cont_codrubro',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'cont_codrubro',
'columnName' => 'field' ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field23' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_label12' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'contractor_type',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'contractor_type',
'columnName' => 'field' ),
'cell_label13' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'buildType' => 2,
'columnCount' => 2 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'masterlist_header' => array( 'type' => 'masterlist_header' ),
'back_master' => array( 'type' => 'back_master' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'cont_nit_contra_ta' ),
'simple_grid_field1' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'grid_field' ),
'simple_grid_field2' => array( 'field' => 'cont_nit_contra_taname',
'type' => 'grid_field' ),
'simple_grid_field3' => array( 'field' => 'cont_estado',
'type' => 'grid_field' ),
'simple_grid_field4' => array( 'field' => 'numcontrato',
'type' => 'grid_field' ),
'simple_grid_field5' => array( 'type' => 'grid_field_label',
'field' => 'cont_nit_contra_taname' ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'cont_estado' ),
'simple_grid_field7' => array( 'field' => 'cont_ano',
'type' => 'grid_field' ),
'simple_grid_field8' => array( 'field' => 'cont_codrubro',
'type' => 'grid_field' ),
'simple_grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'numcontrato' ),
'simple_grid_field10' => array( 'field' => 'cont_fecha_inicio',
'type' => 'grid_field' ),
'simple_grid_field11' => array( 'field' => 'cont_fechafinal',
'type' => 'grid_field' ),
'simple_grid_field12' => array( 'field' => 'cont_periodicidad',
'type' => 'grid_field' ),
'simple_grid_field13' => array( 'field' => 'cont_valorinicial',
'type' => 'grid_field' ),
'simple_grid_field14' => array( 'field' => 'cont_valormensual',
'type' => 'grid_field' ),
'simple_grid_field15' => array( 'field' => 'cont_secop_enlace',
'type' => 'grid_field' ),
'simple_grid_field16' => array( 'type' => 'grid_field_label',
'field' => 'cont_ano' ),
'simple_grid_field17' => array( 'type' => 'grid_field_label',
'field' => 'cont_codrubro' ),
'simple_grid_field18' => array( 'type' => 'grid_field_label',
'field' => 'cont_fecha_inicio' ),
'simple_grid_field19' => array( 'type' => 'grid_field_label',
'field' => 'cont_fechafinal' ),
'simple_grid_field20' => array( 'type' => 'grid_field_label',
'field' => 'cont_periodicidad' ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'cont_valorinicial' ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual' ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_enlace' ),
'grid_field' => array( 'field' => 'contractor_type',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'contractor_type' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>