<?php
			$optionsArray = array( 'totals' => array( 'idusrglobal_fk' => array( 'totalsType' => '' ),
'NUMCONTRATOS' => array( 'totalsType' => '' ),
'NOMBRESUPERVISOR' => array( 'totalsType' => '' ),
'usr_email' => array( 'totalsType' => '' ),
'usr_dep' => array( 'totalsType' => '' ),
'usr_cargo' => array( 'totalsType' => '' ),
'nombre_dependencia' => array( 'totalsType' => '' ),
'id_depto_superior' => array( 'totalsType' => '' ),
'nombre_cargo' => array( 'totalsType' => '' ),
'Departamento_superior' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'NOMBRESUPERVISOR',
'usr_email',
'nombre_cargo',
'NUMCONTRATOS',
'Departamento_superior',
'nombre_dependencia',
'cont_ano' ),
'exportFields' => array( 'NOMBRESUPERVISOR',
'usr_email',
'nombre_cargo',
'NUMCONTRATOS',
'Departamento_superior',
'nombre_dependencia',
'cont_ano' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'NOMBRESUPERVISOR' => array( 'export_field' ),
'usr_email' => array( 'export_field1' ),
'nombre_cargo' => array( 'export_field2' ),
'NUMCONTRATOS' => array( 'export_field3' ),
'Departamento_superior' => array( 'export_field4' ),
'nombre_dependencia' => array( 'export_field5' ),
'cont_ano' => array( 'export_field6' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => false,
'csv' => false,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'NOMBRESUPERVISOR',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'usr_email',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'nombre_cargo',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'NUMCONTRATOS',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Departamento_superior',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'nombre_dependencia',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'cont_ano',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false,
'fileTypes' => array( 'excel' => true,
'word' => false,
'csv' => false,
'xml' => false ) );
		?>