<?php
			$optionsArray = array( 'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'CONTRATOID' => array( 'totalsType' => '' ),
'VIGENCIA' => array( 'totalsType' => '' ),
'contractor_type' => array( 'totalsType' => '' ),
'DOCID' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'nombresupfull' => array( 'totalsType' => '' ),
'sup_mailnot' => array( 'totalsType' => '' ),
'FECHAI' => array( 'totalsType' => '' ),
'FECHAF' => array( 'totalsType' => '' ),
'VALORI' => array( 'totalsType' => '' ),
'PAGO_MES' => array( 'totalsType' => '' ),
'NUMPAGOS' => array( 'totalsType' => '' ),
'VALOR_CONTRATO' => array( 'totalsType' => '' ),
'VALOR_PAGADO' => array( 'totalsType' => '' ),
'SALDO' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'CONTRATOID',
'VIGENCIA',
'contractor_type',
'DOCID',
'contractor_nombresfull',
'contractor_email',
'nombresupfull',
'sup_mailnot',
'FECHAI',
'FECHAF',
'VALORI',
'PAGO_MES',
'NUMPAGOS',
'VALOR_PAGADO',
'SALDO' ),
'exportFields' => array( 'CONTRATOID',
'VIGENCIA',
'contractor_type',
'DOCID',
'contractor_nombresfull',
'contractor_email',
'nombresupfull',
'sup_mailnot',
'FECHAI',
'FECHAF',
'VALORI',
'PAGO_MES',
'NUMPAGOS',
'VALOR_PAGADO',
'SALDO' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'CONTRATOID' => array( 'export_field1' ),
'VIGENCIA' => array( 'export_field2' ),
'contractor_type' => array( 'export_field3' ),
'DOCID' => array( 'export_field4' ),
'contractor_nombresfull' => array( 'export_field5' ),
'contractor_email' => array( 'export_field6' ),
'nombresupfull' => array( 'export_field7' ),
'sup_mailnot' => array( 'export_field8' ),
'FECHAI' => array( 'export_field9' ),
'FECHAF' => array( 'export_field10' ),
'VALORI' => array( 'export_field11' ),
'PAGO_MES' => array( 'export_field12' ),
'NUMPAGOS' => array( 'export_field13' ),
'VALOR_PAGADO' => array( 'export_field15' ),
'SALDO' => array( 'export_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field15',
'export_field' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field15' => 'grid',
'export_field' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field15',
'export_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field15',
'export_field' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'CONTRATOID',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'VIGENCIA',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'contractor_type',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'DOCID',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'contractor_nombresfull',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'contractor_email',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'nombresupfull',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'sup_mailnot',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'FECHAI',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'FECHAF',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'VALORI',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'PAGO_MES',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'NUMPAGOS',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'VALOR_PAGADO',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'SALDO',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>