<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'VALOR_PAGADO',
'SALDO' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'VALOR_PAGADO' => array( 'report_grid_field1',
'report_group_field3' ),
'SALDO' => array( 'report_grid_field2',
'report_group_field2' ),
'contractor_nombresfull' => array( 'report_group_field' ),
'NUMPAGOS' => array( 'report_group_field1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_grid_field1',
'report_grid_field2' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_group_field2' => 'grid',
'report_group_field3' => 'grid',
'report_grid_field1' => 'grid',
'report_grid_field2' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'report_grid_field' => array( 'report_grid_field1',
'report_grid_field2' ),
'report_group_field' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'rprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => false,
'field' => 'contractor_nombresfull',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 1 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'NUMPAGOS',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 0 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'SALDO',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 0 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'VALOR_PAGADO',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 0 ) ),
'fields' => array( array( 'field' => 'VALOR_PAGADO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => true ),
array( 'field' => 'SALDO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => true ) ),
'showData' => true,
'pageSummary' => false,
'globalSummary' => false,
'crosstab' => true,
'colors' => array(  ),
'horizSummary' => true,
'layout' => 'plain',
'vertSummary' => true ) ) );
			$pageArray = array( 'id' => 'rprint',
'type' => 'rprint',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field1',
'report_grid_field2' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => false,
'field' => 'contractor_nombresfull',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 1 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'NUMPAGOS',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 0 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'SALDO',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 0 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'VALOR_PAGADO',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 0 ) ),
'fields' => array( array( 'field' => 'VALOR_PAGADO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => true ),
array( 'field' => 'SALDO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => true ) ),
'showData' => true,
'pageSummary' => false,
'globalSummary' => false,
'crosstab' => true,
'colors' => array(  ),
'horizSummary' => true,
'layout' => 'plain',
'vertSummary' => true ) ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header',
'title' => array( 'page' => 'rprint',
'table' => 'q_s_ctrl_pagado_001 Report',
'type' => 7 ) ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'report_grid_field1' => array( 'field' => 'VALOR_PAGADO',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => true ),
'report_grid_field2' => array( 'field' => 'SALDO',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => true ),
'report_group_field' => array( 'field' => 'contractor_nombresfull',
'type' => 'report_group_field',
'summary' => false,
'axis' => 1,
'interval' => 0 ),
'report_group_field1' => array( 'field' => 'NUMPAGOS',
'type' => 'report_group_field',
'summary' => false,
'axis' => 0,
'interval' => 0 ),
'report_group_field2' => array( 'field' => 'SALDO',
'type' => 'report_group_field',
'summary' => false,
'axis' => 0,
'interval' => 0 ),
'report_group_field3' => array( 'field' => 'VALOR_PAGADO',
'type' => 'report_group_field',
'summary' => false,
'axis' => 0,
'interval' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>