<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_contrato_modifica  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["BeforeMoveNextList"]=true;

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		$sql = DB::prepareSQL("SELECT
contrato.cont_valorvigente,
contrato.cont_valorinicial,
q_mod_adiciones.total,
q_mod_reducciones.total
FROM
contrato
INNER JOIN q_mod_adiciones ON contrato.id_cont = q_mod_adiciones.id_cont_fk
INNER JOIN q_mod_reducciones ON contrato.id_cont = q_mod_reducciones.id_cont_fk;");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		$sql = DB::prepareSQL("SELECT
contrato.cont_valorvigente,
contrato.cont_valorinicial,
q_mod_adiciones.total,
q_mod_reducciones.total
FROM
contrato
INNER JOIN q_mod_adiciones ON contrato.id_cont = q_mod_adiciones.id_cont_fk
INNER JOIN q_mod_reducciones ON contrato.id_cont = q_mod_reducciones.id_cont_fk;");
DB::Exec( $sql );


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		$sql = DB::prepareSQL("SELECT
contrato.cont_valorvigente,
contrato.cont_valorinicial,
q_mod_adiciones.total,
q_mod_reducciones.total
FROM
contrato
INNER JOIN q_mod_adiciones ON contrato.id_cont = q_mod_adiciones.id_cont_fk
INNER JOIN q_mod_reducciones ON contrato.id_cont = q_mod_reducciones.id_cont_fk;");
DB::Exec( $sql );


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
