<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_contrato_ov  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		if($data['cont_estado'] == 2)
{
$record["cont_estado_css"]='background:yellow;color:black;';
}

if($data['cont_estado'] == 3)
{
$record["cont_estado_css"]='background:green;color:white;';
}

// Finaliza contratos de forma automática, cuendo la fecha actual es mayo a la fecha de finalización del contrato

$sql = DB::prepareSQL("UPDATE
dbct.contrato
SET
dbct.contrato.cont_estado = 3
WHERE dbct.contrato.cont_fechafinal < CURDATE();");
DB::Exec( $sql );

$sql = DB::prepareSQL("UPDATE dbct.contrato
INNER JOIN dbct.q_discrimina_iva ON dbct.contrato.cont_nit_contra_ta = dbct.q_discrimina_iva.contractor_doc_id 
SET dbct.contrato.cont_iva = 1;");
DB::Exec( $sql );
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		//**********  Insert a record into another table  ************

$data = array();
$data["id_cont_fk"] = $oldvalues['id_cont'];
$data["cont_nit_contra_ta"] = $oldvalues['cont_nit_contra_ta'];
$data["cont_fecha_inicio"] = $oldvalues['cont_fecha_inicio'];
$data["cont_fechafinal"] = $oldvalues['cont_fechafinal'];
$data["cont_valorinicial"] = $oldvalues['cont_valorinicial'];
$data["cont_valormensual"] = $oldvalues['cont_valormensual'];
$data["cont_cesion"] = $values['cont_cesion'];
$data["cont_modifica"] = $values['cont_modifica'];
DB::Insert("contrato_modifica_track", $data );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
