<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'codeField' => '',
'emailField' => 'usr_email',
'extUserIdField' => '',
'fullnameField' => 'usr_name',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Password',
'phoneField' => '',
'resetDateField' => '',
'resetTokenField' => '',
'table' => array( 'connId' => 'dbusers_at_localhost',
'table' => 'global_users' ),
'twoFactorField' => '',
'userGroupField' => 'groupid',
'usernameField' => 'Username',
'userpicField' => '' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'FNnt4D7qPY1XyKf6dyOK',
'JWTSecret' => '8OirhmZH0VTJ1YzHKfnX' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 1,
'hashAlgorithm' => 1,
'adminEmail' => '',
'caseInsensitiveLogin' => false,
'changePasswordPage' => false,
'hashPassword' => true,
'notifyAdmin' => false,
'notifyUser' => false,
'registerPage' => false,
'remindPasswordPage' => false,
'sendActivationLink' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'notificaciones@mincit.gov.co',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => '172.18.0.22',
'SMTPPort' => 25,
'SMTPUser' => '',
'SMTPPassword' => '',
'securityProtocol' => 0 ),
'advancedSecurity' => array( 'allowGuestLogin' => false,
'tables' => array( '002_producto' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => 'active' ),
'002_producto_dbsep' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'005_catalogo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'006_compromisos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'007_cdp' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'ViewSECOP' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_members' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_rights' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_users' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cargo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => 'active' ),
'contractor_master' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contractor_master_vinc' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_attached' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_attached_ant' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_attached_ov' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_attached_type' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_cdp' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_chart_dependencia' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_chart_estado' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_chart_supjer' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_chart_tipocont' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_chart_tiporubro' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_dependencia' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_estados' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_forma_pago' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_modifica' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_modifica_cesion' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_modifica_prorroga' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_modifica_track' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_modifica_type' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_oe' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_ov' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_pre' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_rp' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_tipo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_tipo_unidad' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'dependencia' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'dependencias_001' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'divipola' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_status' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_unspsc' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_users' => array( 'mainOwnerIDField' => 'idusrglobal',
'securityOption' => 0,
'userOwnerIDField' => 'idusrglobal' ),
'global_users_sup' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'hoja_ruta_2020_adm' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'info_secop' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup2' => array( 'mainOwnerIDField' => 'inf_intersup',
'securityOption' => 1,
'userOwnerIDField' => 'usr_personalid' ),
'informe_intersup2r' => array( 'mainOwnerIDField' => 'inf_intersup',
'securityOption' => 1,
'userOwnerIDField' => 'usr_personalid' ),
'informe_intersup3' => array( 'mainOwnerIDField' => 'inf_intersup',
'securityOption' => 1,
'userOwnerIDField' => 'usr_personalid' ),
'informe_intersup4' => array( 'mainOwnerIDField' => 'inf_intersup',
'securityOption' => 1,
'userOwnerIDField' => 'usr_personalid' ),
'informe_intersup_adm' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => 'usr_personalid' ),
'informe_intersup_anexos_adm' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_anexos_supervisor' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_cxc_adm' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_estado' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_oe' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_oe_adm' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_oe_borrar' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => 'active' ),
'informe_intersup_oe_supervisor' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_plan_pagos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_plan_pagos_adm' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_plan_pagos_st' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_tipo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'interventor_interno' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'interventor_periodos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nomina_cont_meses' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_dbgp_4' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'polizas_aseguradoras' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'polizas_master' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'polizas_tipo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_000_control_informes' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_001_dashboard' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_001_dashboard_info' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_bandejaentrada_supervisores' => array( 'mainOwnerIDField' => 'idusrglobal_fk',
'securityOption' => 1,
'userOwnerIDField' => 'idusrglobal' ),
'q_bandejaentrada_supervisores1' => array( 'mainOwnerIDField' => 'idusrglobal_fk',
'securityOption' => 1,
'userOwnerIDField' => 'idusrglobal' ),
'q_bandejaentrada_supervisores2' => array( 'mainOwnerIDField' => 'idusrglobal_fk',
'securityOption' => 0,
'userOwnerIDField' => 'idusrglobal' ),
'q_bandejaentrada_supervisores3' => array( 'mainOwnerIDField' => 'idusrglobal_fk',
'securityOption' => 1,
'userOwnerIDField' => 'idusrglobal' ),
'q_bandejaentrada_supervisores_consulta' => array( 'mainOwnerIDField' => 'idusrglobal_fk',
'securityOption' => 0,
'userOwnerIDField' => 'idusrglobal' ),
'q_consulta_op' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_divipola' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_gestion_infosup_pagos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_global_supervisores_activos_group' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_global_supervisores_ecarrillo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_obligacion' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_ordenpago' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_registros' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_informe_secop_publicados' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_informes_con_anexos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_oe_ordinal' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_rubros' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_s_ctrl_pagado_001' => array( 'mainOwnerIDField' => 'sup_mailnot',
'securityOption' => 1,
'userOwnerIDField' => 'usr_email' ),
'q_s_ctrl_pagado_001 Report' => array( 'mainOwnerIDField' => 'sup_mailnot',
'securityOption' => 1,
'userOwnerIDField' => 'usr_email' ),
'q_usos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'rep_prg001_catalogopresupuestal' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'secop' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tipo_banco' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tipo_contrato' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tipo_cta_banco' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tipo_docidentidad' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tipo_si_no' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_habilita' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_sn' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_sn_oe' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipo_ct_000' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipo_ct_001' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipo_ct_002' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipo_ct_regimen_tribut' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipo_ct_rubro' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'vigencia' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ) ) ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'dbct_at_localhost',
'table' => 'gestioncontratos_ver_103_audit' ),
'lockingTable' => array( 'connId' => 'dbct_at_localhost',
'table' => 'gestioncontratos_ver_103_locking' ),
'tables' => array( '002_producto' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'002_producto_dbsep' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'005_catalogo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'006_compromisos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'007_cdp' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'ViewSECOP' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'admin_members' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'admin_rights' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'admin_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cargo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contractor_master' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contractor_master_vinc' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_attached' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_attached_ant' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_attached_ov' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_attached_type' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_audit' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_cdp' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_dependencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_estados' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_forma_pago' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_modifica' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_modifica_cesion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_modifica_prorroga' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_modifica_suspension' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_modifica_track' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_modifica_type' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_oe' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_ov' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_paa' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_pre' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_rp' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_tipo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_tipo_unidad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dependencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dependencias_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'divipola' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_duracion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_status' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_unspsc' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_users_sup' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'hoja_ruta_2020_adm' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'info_secop' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup2' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup2r' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup3' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup4' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_adm' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_anexos_adm' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_anexos_supervisor' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_cxc_adm' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_estado' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_oe' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_oe_adm' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_oe_borrar' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_oe_supervisor' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_plan_pagos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_plan_pagos_adm' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_plan_pagos_st' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_tipo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'interventor_interno' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'interventor_periodos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nomina_cont_meses' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_dbgp_4' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'polizas_aseguradoras' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'polizas_master' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'polizas_tipo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_000_control_informes' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_001_dashboard' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_001_dashboard_info' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_001_dashboard_master' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_bandejaentrada_supervisores' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_bandejaentrada_supervisores1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_bandejaentrada_supervisores2' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_bandejaentrada_supervisores3' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_bandejaentrada_supervisores_consulta' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_consulta_op' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_divipola' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_gestion_infosup_pagos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_global_supervisores_activos_group' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_global_supervisores_ecarrillo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_info_obligacion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_info_ordenpago' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_info_registros' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_informe_secop_publicados' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_informe_secop_publicados_dbgpaa' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_informes_con_anexos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_oe_ordinal' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_rubros' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_s_ctrl_pagado_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_usos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'rep_prg001_catalogopresupuestal' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'secop' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_banco' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_contrato' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_cta_banco' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_docidentidad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_si_no' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_habilita' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_sn' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_sn_oe' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_000' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_002' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_regimen_tribut' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_rubro' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipopago' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'vigencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => true ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'GestionContratos_v1091',
'loginDataSource' => 'global_users',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'gestioncontratos_ver_103_',
'dpTableConnId' => 'dbusers_at_localhost',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'codeField' => '',
'emailField' => 'usr_email',
'extUserIdField' => '',
'fullnameField' => 'usr_name',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Password',
'phoneField' => '',
'resetDateField' => '',
'resetTokenField' => '',
'table' => array( 'connId' => 'dbusers_at_localhost',
'table' => 'global_users' ),
'twoFactorField' => '',
'userGroupField' => 'groupid',
'usernameField' => 'Username',
'userpicField' => '' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>